### ISSUE TITLE
Support for doc, xls and ppt

### ISSUE THREAD

**Issue by lolobosse** [sindresorhus/file-type#112]
Hi there,

The lib detects `docx`, `xlsx`, `pptx` (:tada:) but not the older format: `doc`, `xls`, `ppt` (:cry:).

I think it's not possible to distinguish them from another because they're all based on the `Compound File Binary Format` ([Wikipedia says that](https://en.wikipedia.org/wiki/List_of_file_signatures)) and there is a very well documented thread on [Microsoft](https://social.msdn.microsoft.com/Forums/en-US/343d09e3-5fdf-4b4a-9fa6-8ccb37a35930/developing-a-tool-to-recognise-ms-office-file-types-doc-xls-mdb-ppt-?forum=os_binaryfile). 😠 

However I'm not sure that there isn't a way by reading the 4100 first bytes (I will have a deeper look).

To me it would a very cool feature because users would be able to detect if the `.doc` uploaded is somehow legit. 🙏 

Even the information that this is a `Compound File Binary Format` would be enough in my case (but I will do that only on my fork because I think that it out of the scope of this library).

Any thoughts on that feature?

**Comment by karlhiramoto** [comment]
I've seen some tools detect this a a mime type "application/ole"  just by looking at the first few bytes.  

To determine the sub type you need to parse a lot more parsing these files can sometimes get complex see A python library that  does this:
* https://github.com/decalage2/olefile
* https://github.com/decalage2/officeparser

**Comment by reviewher** [comment]
To detect the general class, the magic number is `0xD0 0xCF 0x11 0xE0`.

To determine the specific type you need to parse the container using a module like https://www.npmjs.com/package/cfb and check for the particular subfile: XLS contains a `/Workbook` or `/Book` file, PPT has `/PowerPoint Document`, DOC has `/WordDocument`.  [Here's an example from the test suite](https://github.com/SheetJS/js-cfb/blob/master/test.js#L45)

**Comment by sindresorhus** [comment]
I don't think I want support for that here. Those are very much obsolete formats and better done as a `file-type-legacy` module or something.

**Comment by robertparkinson** [comment]
@reviewher where you able to actually use cfb to detect the file? I keep getting the following error and can't find any examples or documentation explaining what it means 

Error: Header Signature: Expected d0cf11e0a1b11ae1 saw fef6abfdfa2575ea

**Comment by reviewher** [comment]
@robertparkinson you have to check if it's an office file first.  the magic number is `0xD0 0xCF 0x11 0xE0`
