### ISSUE TITLE
m4a from android phone

### ISSUE THREAD

**Issue by Frezzaldo** [sindresorhus/file-type#122]
I have used the audio recorder on my android phone to record a m4a-file. When i run it through the filetype-function it returns null (it cant find a match).

The Uint8Array for my m4a-file starts with:
0, 0, 0, 24, 102, 116, 121, 112, 51, 103, 112, 52, 0, 0, 0, 0

In the the filetype-function m4a-check:
check([0x66, 0x74, 0x79, 0x70, 0x4D, 0x34, 0x41], {offset: 4}) ||
check([0x4D, 0x34, 0x41, 0x20])

Is it something special with the m4a file I get from the phone recorder or should this be updated?

**Comment by mifi** [comment]
is it correctly identified by unix `file`?

**Comment by mifi** [comment]
this could be related to #99

**Comment by karlhiramoto** [comment]
@Frezzaldo  Can you attach a small example file.

**Comment by sindresorhus** [comment]
Closing for lack of response.
