### ISSUE TITLE
CRA build fails to minify

### ISSUE THREAD

**Issue by maksimdegtyarev** [sindresorhus/file-type#130]
According to https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify, please can you publish pre-compiled version of the package?
I use CRA and when i try to create build, it throws an error: 
`Failed to compile.
`
`Failed to minify the code from this file: 
`
`	./node_modules/file-type/index.js:2 `

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
