### ISSUE TITLE
Add `4100` as a constant

### ISSUE THREAD

**Issue by FranckFreiburger** [sindresorhus/file-type#131]
It could be convenient to know the minimum amount of data to read in order to detect the file type.
Currently the doc states 'It only needs the first 4100 bytes.'
Can you provide a constant that contains this value.

benefits may be:
- can be used programatically
- reliable value even if new formats that need more than 4100 first bytes are supported

thanks.

**Comment by sindresorhus** [comment]
Good idea. PR welcome :)
