### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by coderdiaz** [sindresorhus/file-type#132]
Hello,
This package it's good but do you plan to support typescript?

**Comment by SamVerschueren** [comment]
It works in TS with `import * as fileType from 'file-type';`. However, it does not have type definitions if that's what you meant. Feel free to add types for this package to DefinitelyTyped and we're happy to :+1: the PR but no, we will not add it to the package directly.

**Comment by coderdiaz** [comment]
@SamVerschueren Thanks 👍

**Comment by Tjommel** [comment]
if someone runs into the typescript error:
error TS2349: Cannot invoke an expression whose type lacks a call signature.

This is the solution that worked for me:
    const fnFileType: any = fileType;
    const oFiletype: any = fnFileType(readChunk.sync(sFilepath, 0, 262));

**Comment by sindresorhus** [comment]
@Tjommel That's definitely not the correct way to resolve your issue.

**Comment by Tjommel** [comment]
Absolutely not^^.

But it works and my clients are happy .....
