### ISSUE TITLE
master branch linting fails

### ISSUE THREAD

**Issue by karlhiramoto** [sindresorhus/file-type#137]
`npm test`  will fail:

```
  ✖    2:22  Prefer the spread operator over Array.from().  unicorn/prefer-spread
  ✖  281:32  Prefer the spread operator over Array.from().  unicorn/prefer-spread
```

The first one is `const toBytes = s => Array.from(s).map(c => c.charCodeAt(0));`

Is there a reason for not using a Uint8Array?  I believe nodejs 4+ supports it.

**Comment by sindresorhus** [comment]
> Is there a reason for not using a Uint8Array?

We are using that. What part of the code are you referring to?
