### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Daniyal83** [sindresorhus/file-type#144]
Using this
```
http.get(link, res => {
    res.once('data', chunk => {
      res.destroy();
      console.log(fileType(chunk));
      //=> {ext: 'gif', mime: 'image/gif'}
    });
  })
```
and it doesn't work. 
As example link 'http://portal.pangea.global/file.txt'
It doesn't even work with the same link in your example.

**Comment by mifi** [comment]
can u clearify "doesn't work"?

**Comment by Daniyal83** [comment]
Nothing happens. I'm using it like this

router.get('/wordcount', async (req, res) => {
var link = req.query.web;
http.get(link, resp => {
    resp.once('data', chunk => {
      resp.destroy();
      console.log(fileType(chunk));
    });
  })
//here is my whole logic...
res.send('done')
});

And I get nothing in the console. I don't even get any error mesage. I tried to debug and 'resp' is empty at all.

**Comment by mifi** [comment]
null is expected for unrecognized type. code in the example works for me. the example .txt url you provided is not a particular file type and does not contain any magic number

**Comment by Daniyal83** [comment]
So not any type is supported?

**Comment by mifi** [comment]
the supported types are listed in readme. txt is not a identifiable file type
