### ISSUE TITLE
.xlsx from linux is accepting the file type as  application/zip

### ISSUE THREAD

**Issue by MuthukumarHelios** [sindresorhus/file-type#155]
i have Uploading the File to the aws i am checking my file type from the buffer 
My buffer Out put value with index
buffer[2] 3
buffer[3] 4
i think it's failing in [see file type code check funciton](https://github.com/sindresorhus/file-type/blob/master/index.js#L193)

>what i need is 
i need to check my xlsx file type using the buffer 
why it's returning .zip format 

-----

[i need to achieve this case ](https://github.com/sindresorhus/file-type/blob/master/index.js#L181)

**Comment by sindresorhus** [comment]
Probably same as https://github.com/sindresorhus/file-type/issues/103
