### ISSUE TITLE
No changelog listing breaking changes

### ISSUE THREAD

**Issue by nikwen** [sindresorhus/file-type#161]
Please consider adding a file that lists all breaking changes. When you have a project with 50+ dependencies, it is really troublesome to go through the commit history of each when updating them.

**Comment by sindresorhus** [comment]
The commit history is clean: https://github.com/sindresorhus/file-type/commits/master The changelog would just be the same as the commit history anyway.

**Comment by nikwen** [comment]
@sindresorhus While in general I agree with you, some commits still require manual review.

Take https://github.com/sindresorhus/file-type/commit/eed45ffc00b8f01593e4d5db5d94441aeac38756 as an example. In a changelog, it would simply be omitted, while in the commit history I see "Meta tweaks". I don't know what that means, so I have to manually check what was changed and whether it contains any changes that are relevant to my usage of the library.

Having to do this for multiple libraries and commits, it quickly adds up. Plus, changelogs usually have a "breaking changes" section, which most of the time is all that I am looking for.
