### ISSUE TITLE
False-positives for the `msi` detection

### ISSUE THREAD

**Issue by fazouane-marouane** [sindresorhus/file-type#162]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/file-type/issues/162)

Hello

It seems that doc files (in fact all files that are CFB based, meaning: msi, doc, xls, ppt, oft...) are recognized as "msi" files.
Example of a doc file: http://www.softdoteducation.com/upload/study-notes/STNOTES_DOC_5.doc

Checking the code, I found the following:

```js
	if (check([0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1])) {
		return {
			ext: 'msi',
			mime: 'application/x-msi'
		};
	}
```

The issue here is that `0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1` is the header signature for CFB format not msi specifically. https://msdn.microsoft.com/en-us/library/dd941946.aspx

Can we please remove this entry and discuss other ways of recognizing such files?
Thanks

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#225 reduce msi false positives (longer check)](https://issuehunt.io/r/sindresorhus/file-type/pull/225)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/file-type/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by karlhiramoto** [comment]
Old office docs, and msi files are all OLE/CFBF container files  
*  https://www.forensicswiki.org/wiki/OLE_Compound_File
*  https://en.wikipedia.org/wiki/Compound_File_Binary_Format

**Comment by thehappycoder** [comment]
`mmmagic` detects .doc files correctly as `application/msword`

**Comment by fazouane-marouane** [comment]
I have something that detects doc/xls/ppt/msi... but it needs to parse the whole cfb container file and doesn’t use magic values which is not that perfect for most people. (+1ko gzipped if my memory serves me right)

**Comment by ilsundal** [comment]
I have the same issue.

wrong: (using "file-type-cli")
$ node cli.js my.doc 
msi
application/x-msi

correct: (using Ubuntu's "file" command)
$ file --mime-type -b my.doc
application/msword

**Comment by ilsundal** [comment]
> I have something that detects doc/xls/ppt/msi... but it needs to parse the whole cfb container file and doesn’t use magic values which is not that perfect for most people. (+1ko gzipped if my memory serves me right)

If this is the only way then so be it :)

Note that Ubuntu's "file" command/utility also works nicely (and super-fast). One option could be to investigate how it does it and then do the same in the "file-type" library.

**Comment by PhantomSophia** [comment]
FYI, if it is OK to same accuracy to libmagic (cf: http://man7.org/linux/man-pages/man3/libmagic.3.html), you can find "magic byte" list from following page: 
https://github.com/threatstack/libmagic/blob/1249b5cd02c3b6fb9b917d16c76bc76c862932b6/magic/Magdir/msdos#L484

**Comment by sindresorhus** [comment]
The fix would not be to add `doc` support, which I'm not interested in, but rather improve the `msi` detection.

**Comment by HugoDF** [comment]
Hi, is anyone able to provide true positive .msi files?

Using the following check I've been able to detect `msi` without having a false positive on `.doc`, `.xls` or `.ppt`

```js
check([0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x04, 0x00, 0xFE, 0xFF, 0x0C, 0x00, 0x06])
```
