### ISSUE TITLE
Test for DNG files

### ISSUE THREAD

**Issue by ItalyPaleAle** [sindresorhus/file-type#164]
DNG ("Digital Negative") is Adobe's open standard for RAW images. It is based on TIFF, but it has some additional tags. Full specification (for latest version) is here: https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf

Currently, using file-type DNG files are reported as TIFF ones, and that's incorrect. It might be necessary to add a test similar to the CR2 one to distinguish DNG from "normal" TIFF files.

I have still not fully understood what bytes can be used to distinguish DNG from TIFF :(

**Comment by mifi** [comment]
can `file` utility distinguish?

**Comment by mifi** [comment]
maybe it's actually compatible with tiff, so it doesn't make so much sense to differentiate?

**Comment by ItalyPaleAle** [comment]
Well, DNG is built around TIFF. The image is encoded as TIFF, and the DNG standard defines some specific tags that can be used to represent information commonly found in RAW images.

In fact, it should be easy to distinguish DNG's from "plain TIFFs" by looking at the tags, but tags aren't found at a specific byte mark, and so it would be necessary to do some extra parsing. Not sure if that's something you're interested in...

In terms of compatibility... They're generally compatible, but not always. For example, I'm feeding those images to ImageMagick, and it doesn't work unless I explicitly set the input file as DNG. If I pass ImageMagick a DNG file saying it's a generic TIFF one, errors appear.

**Comment by mifi** [comment]
If it can be distinguished by looking at the first few bytes I think we could add support for it. I don't have time to research how to do this now tho.

**Comment by ItalyPaleAle** [comment]
No, doesn't look like it can. You'd have to parse the TIFF tags and look for DNG-specific ones. Definitely much more than checking for a few bytes.

I could look into this and maybe opening a PR, but it will require adding quite a bunch of code and at least a couple of dependencies to extract/parse tags. Not sure if this would be outside of the scope of this library, then.

**Comment by mifi** [comment]
Yea I don't think we want to add dependencies to this lib. It already has 0 deps, and only does simple byte range matchings.

**Comment by sindresorhus** [comment]
Yeah, better make it a separate `is-dng` package. Happy to link to it from our readme if you end up making it ;)
