### ISSUE TITLE
DCM

### ISSUE THREAD

**Issue by jssuttles** [sindresorhus/file-type#166]
You would probably help out the medical community if you could add DICOM to your list. 'DICM' is at offset of 128.

**Comment by sindresorhus** [comment]
Can you link to a source for the DICOM format and its "magic bytes"?

**Comment by jssuttles** [comment]
Not sure if I can find you the dicom standard exactly... but here's a pretty good source on the matter:
https://support.dcmtk.org/docs/dcmftest.html

**Comment by amichal** [comment]
👍 The spec is here http://dicom.nema.org/dicom/2013/output/chtml/part10/chapter_7.html its simply the ascii sequence `DICM` exactly 128 bytes from the start of the files. I'd be more the happy to implement it given some other examples which I'll look at now

**Comment by amichal** [comment]
For the record here is the IANA registration confirming the magic bytes. https://www.iana.org/assignments/media-types/application/dicom

**Comment by amichal** [comment]
I noticed the README lists supported formats with links to reference documents. I wasn't sure what the convention on sources was so I didn't add a link. Wikipedia https://en.wikipedia.org/wiki/DICOM is a bit broad I expect. However, at the moment, it does link to the standard section that contains the chapter i cited above...
