### ISSUE TITLE
Certain .xlsx files are detected as .zip

### ISSUE THREAD

**Issue by kbeckster** [sindresorhus/file-type#178]
Only certain .xlsx files are being scanned as .zip files. 

Appears to be random - anyone know if this happens for a reason? Not sure if something is being done to the file before I get it but I can confirm there are no macros or code within the file.

Result from uploading .xlsx:
`{"ext":"zip","mime":"application/zip"}`

**Comment by MaxLeiter** [comment]
Can you provide an example file?

**Comment by kbeckster** [comment]
Update - even though the data in the file appears fine (just numbers and values) after deleting the data and scanning again the scan works as expected. 

I'm going to close the issue but if anyone has any insight on what might make a .xlsx file get a mime type of zip without any noticeable signs. Please let me know.

**Comment by racario** [comment]
[example.pptx](https://github.com/sindresorhus/file-type/files/2679971/example.pptx)

I have the issue when i try it with this file

**Comment by rafaneri** [comment]
Hello @kbeckster and @MaxLeiter,

I have the same problem here. It's an [sample](https://github.com/sindresorhus/file-type/files/6808154/campanha-felipe.xlsx) file with problem.

Thk's!
