### ISSUE TITLE
Please fix the error 'spread non-iterable instance'

### ISSUE THREAD

**Issue by hu382337381** [sindresorhus/file-type#181]
when I use file-type in react-native,I met the javascriptError 'invalid attempt to spread non-iterable instance',I must update the line 2 and line 309 of index.js like this,you can see the issues at here https://github.com/facebook/react-native/issues/21734
line 2:
const toBytes = s => Array.from(s).map(c => c.charCodeAt(0));
line 309:
const findDocType = type => Array.from(type).every((c, i) => sliced[docTypePos + i] === c.charCodeAt(0));

**Comment by sindresorhus** [comment]
This module mainly targets Node.js. It's up to you to make it work in React Native.
