### ISSUE TITLE
Typescript definitions caused backwards incompatible changes

### ISSUE THREAD

**Issue by aequasi** [sindresorhus/file-type#189]
Unfortunately hard to do anything about it now, but adding the typescript definitions should have been a major release.

import now has a default, and types are expected instead of implicit any's

**Comment by sindresorhus** [comment]
Type definitions now ship with this package and might differ from the ones at DefinitelyTyped. Introducing type definitions to a package is not a breaking change. It's the fault of TypeScript that it picks the typings from the package over the ones from DefinitelyTyped. See: https://github.com/Microsoft/TypeScript/issues/19283 I would encourage you to open a new TypeScript issue about this and refer to my issue.

**Comment by aequasi** [comment]
I wasn't using any type definitions before. Implementing anything that changes the type (as was the case here, from "any" to something specific), is a contract change, and a bc break.

**Comment by sindresorhus** [comment]
No, it's not a breaking change, because there was no contract.

**Comment by aequasi** [comment]
There was an implicit contract, as by default, if the types not defined during an import, it's an implicit any.

**Comment by aequasi** [comment]
To be clear, this is what the typescript dif ends up being:

```typescript
export const fileType = (input: any): any => {
    // ...
}
```

Which is implemented as follows:
```typescript
import * as fileType from 'file-type';
```

As there was no default export before.

Now, it's this:
```typescript
export const fileType = (input: string): FileTypeResult => {
    // ...
}
export default fileType;
```

Which is implemented as:
```typescript
import fileType from 'file-type'; // No `* as`, as there's now a default. `* as` actually causes an issue.
```

This change also breaks the following code:
```typescript
let type = fileType(someFileType);
if (!type) {
    type = {ext: 'txt', mime: 'text/plain'};
}
```

As the response from fileType is now `FileTypeResult`, instead of `any`.
