### ISSUE TITLE
Getting null as result

### ISSUE THREAD

**Issue by george-norris-salesforce** [sindresorhus/file-type#190]
[![Image from Gyazo](https://i.gyazo.com/8e7feea501f45e52fac3788bf9119468.gif)](https://gyazo.com/8e7feea501f45e52fac3788bf9119468)

As you can see from the Gif, I have a Buffer and I'm passing that to fileType, which returns null. The file is a json file. 

EDIT: You don't support JSON?

**Comment by sindresorhus** [comment]
> EDIT: You don't support JSON?

It's not listed in the "Supported file types" section, so no.

**Comment by sindresorhus** [comment]
This module is for binary files. For JSON, you can just do `JSON.parse()` inside a `try/catch` to check if it's valid JSON.
