### ISSUE TITLE
Support for Node.js v11

### ISSUE THREAD

**Issue by fstoerkle** [sindresorhus/file-type#196]
In Node.js v11, the `callback` parameter to `pipeline` was made obligatory: https://github.com/nodejs/node/pull/21054

Subsequently, running file-type with Node.js v11 fails with this error:
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
```

I ran the test suite on Travis CI, which confirms this: https://travis-ci.com/fstoerkle/file-type/jobs/190598883

**Comment by jfinkhaeuser** [comment]
bump

**Comment by siman** [comment]
Hey @sindresorhus, can you make a minor release w/ this fix, please?
