### ISSUE TITLE
Support for streams?

### ISSUE THREAD

**Issue by goloroden** [sindresorhus/file-type#20]
Currently, you need a buffer for detecting the mime type.

It would be awesome if streams could also be used as input. In this case, `file-type` might act as a `Transform` stream that basically passes everything through, but captures the first 262 bytes and then emits a `mimeType` event with the detected mime type.

What do you think about this?

**Comment by goloroden** [comment]
Forget about this, [this](https://github.com/sindresorhus/file-type#nodejs) worked for me perfectly :-)

**Comment by olalonde** [comment]
```
http.get(url, res => {
    res.once('data', chunk => {
        res.destroy();
        console.log(fileType(chunk));
        //=> {ext: 'gif', mime: 'image/gif'}
    });
});
```

Is it guaranteed that the first chunk will have enough bytes for file-type to work properly?

**Comment by olalonde** [comment]
Just wrote https://github.com/blockai/file-type-stream

**Comment by CodeMan99** [comment]
sindresorhus also has [first-chunk-stream](//github.com/sindresorhus/first-chunk-stream).
