### ISSUE TITLE
Question: can this package be used to detect .tiff file's compression method?

### ISSUE THREAD

**Issue by adame21** [sindresorhus/file-type#217]
Hi, 
Just a quick question:
If I have a tiff file and I use node's fs (filesystem) to read it, now I have an array buffer.
Can I use this package to find out how is the tiff file compressed? (like lzw or zip or not compressed) 
Thanks.

**Comment by sindresorhus** [comment]
No, that's outside the scope of the module.

You might find some useful modules here: https://npms.io/search?q=tiff
