### ISSUE TITLE
Add support for Fujifilm RAF & Panasonic RW2 format

### ISSUE THREAD

**Issue by przemyslawpluta** [sindresorhus/file-type#218]
At the moment `file-type` returns `undefined` when testing against [raf](https://img.photographyblog.com/reviews/fujifilm_xf_16mm_f2_8_r_wr/photos/fujifilm_xf_16mm_f2_8_r_wr_01.raf) format and [rw2](https://img.photographyblog.com/reviews/panasonic_s1r/photos/panasonic_s1r_01.rw2)

**Comment by sindresorhus** [comment]
PR welcome :)

https://github.com/sindresorhus/file-type/blob/master/.github/pull_request_template.md

**Comment by mceachen** [comment]
I can do it right now.
