### ISSUE TITLE
Checking against NEF, ARW, DNG returns image/tiff

### ISSUE THREAD

**Issue by przemyslawpluta** [sindresorhus/file-type#219]
Based on https://github.com/sindresorhus/file-type/pull/213 when testing against [nef](https://img.photographyblog.com/reviews/nikon_d850/sample_images/nikon_d850_01.nef), [arw](https://img.photographyblog.com/reviews/sony_a7r_iii/sample_images/sony_a7r_iii_01.arw) and [dng](https://img.photographyblog.com/reviews/pentax_k_1_mark_ii/sample_images/pentax_k_1_mark_ii_01.dng) you'd expect `file-type` to return:

```js
{ ext: 'nef', mime: 'image/x-nikon-nef' }
{ ext: 'arw', mime: 'image/x-sony-arw' }
{ ext: 'dng', mime: 'image/x-adobe-dng' }
```
but it returns instead:

```js
{ ext: 'tif', mime: 'image/tiff' }
```

**Comment by sindresorhus** [comment]
// @mceachen

**Comment by mceachen** [comment]
Do you have example files you can share that aren't working?

**Comment by przemyslawpluta** [comment]
@mceachen links in the original case

**Comment by mceachen** [comment]
@przemyslawpluta those links return 403.

**Comment by mceachen** [comment]
OK, I found the reviews and am updating the fixtures and tests.
