### ISSUE TITLE
gz but its gif

### ISSUE THREAD

**Issue by Usernameisalreadytaken5** [sindresorhus/file-type#222]
Its way its GZ but its GIF

climbers.pl/1_partyanimsm2.gif

**Comment by sindresorhus** [comment]
Please spend some more effort on this issue. I have no idea what you're talking about.

**Comment by Usernameisalreadytaken5** [comment]
I'm use this library for mitm project

**OK its working alright just my bad please close**

some gz request are made before real request 

![image](https://user-images.githubusercontent.com/36273555/59844730-1f642d80-934b-11e9-819c-9b4e6116d16c.png)
