### ISSUE TITLE
'SCRIPT1010: Expected identifier' on IE11

### ISSUE THREAD

**Issue by brunomfv** [sindresorhus/file-type#230]
Hi,

We're using file-type on our angular 7 app and everything works fine except on IE11, where we can't even run it since we've installed this package.

We get the above mentioned error that takes us to this line of code when clicked:
`const {stringToBytes, readUInt64LE, tarHeaderChecksumMatches, uint8ArrayUtf8ByteString} = __webpack_require__(/*! ./util */ "./node_modules/file-type/util.js");`

Is this familiar to anyone?

Thank you in advance!

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
