### ISSUE TITLE
fileType undefined when using stream

### ISSUE THREAD

**Issue by midnightcodr** [sindresorhus/file-type#246]
I have the following simple code but the result is `undefined`, why?

```js
const fileType = require('file-type')
const fs = require('fs')

;(async () => {
  const read = fs.createReadStream('/tmp/test.txt')
  const fileTypeStream = await fileType.stream(read)
  console.log(fileTypeStream.fileType)
  // => undefined
})()
```

where /tmp/test.txt contains the following content
```hi```

Tested with both node v12.9.1 and v11.3.0.

**Comment by bencmbrook** [comment]
No file type was detected. That `test.txt` file only has two bytes: `0x68` and `0x69`, or `h` and `i`. There's nothing this library can infer about the file type based on those two bytes. 

Depending on your implementation, you may be able to get the file type through other means. If you're actually using your file system, you can lookup the extension `path.extname('index.html')`, or the content type with [this package](https://github.com/broofa/node-mime).

**Comment by midnightcodr** [comment]
@bencmbrook thanks for the response. However, detecting the file type of a text file that's long enough would also return undefined (instead of the expected `text/plain`). I've created this gist that will detect the file type with a http server (using hapijs) https://gist.github.com/midnightcodr/0e569b6f20b2ddd8b5a376a4f7e5a320, it works for most of the file types but when it comes to text files, regardless of their length, the result is 500 error. In my humble opinion, `file-type` should be able to detect file type `text/plain`. I am bringing this up because I am building a file-upload server that would only permit certain image files and pdfs files. Having to use another module or resorting to using `path.extname` in order to detect the file uploaded is text file (as you suggested) or not  first seems to be counter-productive, or unreliable as file extension can be easily manipulated in the case of file upload.

**Comment by midnightcodr** [comment]
@bencmbrook  never mind, I think in my use case I can simply draw conclusion that the file uploaded is not supported once `undefined` is returned from the stream lookup result.
