### ISSUE TITLE
Add Esri Shapefile support?

### ISSUE THREAD

**Issue by tmcw** [sindresorhus/file-type#247]
I'd like to include support for the [Esri Shapefile format](https://en.wikipedia.org/wiki/Shapefile), which is one of the most popular ways to share geospatial data. It has a few caveats, though:

- The file format is actually 3 files - shp, shx, and dbf. The dbf file is [a dBase file](https://www.dbf2002.com/dbf-file-format.html).
- The `shp` file can be easily detected (with `check([0x27, 0x0A], {offset: 2})`), but it does not have a mime-type reserved.

Does file-type aim to support files that don't have associate mime types?

**Comment by sindresorhus** [comment]
Sure. PR welcome. When a file type doesn’t have a mime type, we just make one up with `x-` prefix. I googled it and saw that some KDE stuff used `application/x-esri-shape`.
