### ISSUE TITLE
ARW files report as TIF

### ISSUE THREAD

**Issue by bentron2000** [sindresorhus/file-type#249]
Hi!

I'm parsing some .ARW files and they report as:
`{ ext: 'tif', mime: 'image/tiff' }`

Is this what is expected for this format?

Cheers

B

**Comment by sindresorhus** [comment]
Can you share an `.ARW` file that reproduces this?

// @mceachen

**Comment by bentron2000** [comment]
Here you go. 
Hope you can recreate.

[_DSC1000.ARW.zip](https://github.com/sindresorhus/file-type/files/3746447/_DSC1000.ARW.zip)

**Comment by mceachen** [comment]
Fixed by #251.
