### ISSUE TITLE
Support for tracked/module file formats

### ISSUE THREAD

**Issue by TheEssem** [sindresorhus/file-type#254]
Hello,
I would like to request support for detecting [music tracker/module file formats](https://en.wikipedia.org/wiki/Module_file) such as .mod, .xm, .s3m, and .it. I've already figured out the headers/magic numbers for some of these formats, which are listed below:

XM: `45 78 74 65 6E 64 65 64 20 4D 6F 64 75 6C 65 3A` **(Extended Module:)**
S3M: `53 43 52 4D` **(SCRM)** [offset 0x2C]
IT: `49 4D 50 4D` **(IMPM)**
MPTM: Same as IT, might be a bit more difficult to detect

I haven't yet figured out a good way to detect MOD files, since they don't seem to have a file signature. If you want some files to test with, you can find them at [the Mod Archive](https://modarchive.org).

Thank you.

**Comment by Borewit** [comment]
You can help me by attaching (zipped) sample fixtures to the issues.

A (nearly) empty `.xm`, `.s3m`, `.it' and `.mptm` would be ideal. Please don't cut the sample fixture.

**Comment by TheEssem** [comment]
Alright, here are some (nearly) empty sample files:
[emptymods.zip](https://github.com/sindresorhus/file-type/files/4054519/emptymods.zip)

**Comment by Borewit** [comment]
It is indeed very difficult to detect MPTM, I [this code](https://github.com/OpenMPT/openmpt/blob/master/mptrack/MPTHacks.cpp) is related to that detection.

However, I think I got the `.mod` detection working:
```js
if (checkString('M.K.', {offset: 1080}) || checkString('M!K!', {offset: 1080})) {
  return {
    ext: 'mod',
    mime: 'audio/x-mod'
  };
}
```
