### ISSUE TITLE
.aac is detected as .mp4 (audio/mpeg) 

### ISSUE THREAD

**Issue by lsheva-bs** [sindresorhus/file-type#259]
*.aac file is detected as `{ ext: 'mp4', mime:' audio/mpeg' }` instead of `{ ext: 'aac', mime:' audio/aac' }`

**Comment by Borewit** [comment]
After #248 is implemented I will investigate.

**Comment by Borewit** [comment]
Maybe related to #208, #210

**Comment by Borewit** [comment]
Can you provide me a sample @lsheva-bs?

**Comment by lsheva-bs** [comment]
[sample-speech.zip](https://github.com/sindresorhus/file-type/files/3916068/sample-speech.zip)

**Comment by Borewit** [comment]
Should be solved with #286.

Related fixtures:
1. [fixture-adts-mpeg2.aac](https://github.com/sindresorhus/file-type/blob/master/fixture/fixture-adts-mpeg2.aac)
2. [fixture-adts-mpeg4-2.aac](https://github.com/sindresorhus/file-type/blob/master/fixture/fixture-adts-mpeg4-2.aac)
3. [fixture-adts-mpeg4.aac](https://github.com/sindresorhus/file-type/blob/master/fixture/fixture-adts-mpeg4.aac)
