### ISSUE TITLE
Ability to detect audio WebM

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#271]
WebM audio file detected as: 

```js
{ 
  ext: 'webm',
  mime: 'video/webm' 
}
```

expected:
```js
{ 
  ext: 'webm',
  mime: 'audio/webm' 
}
```
Sample file: 
[02 - Poxfil - Solid Ground (5 sec).opus.webm.zip](https://github.com/sindresorhus/file-type/files/3983390/02.-.Poxfil.-.Solid.Ground.5.sec.opus.webm.zip)

**Comment by sindresorhus** [comment]
I think we should wait to add more formats until the tokenizer branch has been merged into `master`.

**Comment by Borewit** [comment]
[WebM](https://en.wikipedia.org/wiki/WebM) is a sub format (_based on the profile_) of Matroska. It requires to parse the [Matroska](https://www.matroska.org/index.html) file. Given the complexity of that format, I am not sure if it belongs in the "core" of file-type. Similar to the MS-CFB (.msi, .doc) It may be better to move this into a plugin. You can use [music-metadata](https://github.com/borewit/music-metadata) (which I am the author of) to retrieve further information about your Matroska file. Maybe I'll write a file-type audio extension plugin using from that recipe one day. Anyway for now I will close this issue. Feel free to reply.

**Comment by pejuam** [comment]
The sample file still gives me video/webm.

**Comment by Borewit** [comment]
@pejuam, @guizzo, you are right, file-type can distinct sub-type WebM from other EBML, but indeed it cannnot distinct between `'video/webm` and `audio/webm`.

 Not sure if that distinction is feasible in file-type. Even in [music-metadata](https://github.com/Borewit/music-metadata) I do not have an `isVideo` detection, as [suggested here](https://github.com/Borewit/music-metadata/issues/2286#issuecomment-2879569968). Reason being this is not a trivial thing to implement.
