### ISSUE TITLE
Pixelation on specific channels

### ISSUE THREAD

**Issue by MuhammadShozab** [sindresorhus/file-type#282]
I am new on this platform and i need guidance. We have developed an app for Android TVs which runs multicast live channels UDP://239.x.x.x. Player being used is VXG. All channels are fine (around 170) but only a few channels are having major freezing/pixelation whenever we switch to those channels (around 7 in number). As per my understanding, there must be some parameter in video, which is disturbing only these 7 channels are rest are all fine. i have compared every parameter that i know using media info, but there is nothing common in those 7 channels which make them unique from rest of the channels. Moreover, we re-encode these 7 channels on same codecs, they start working fine. i am attaching media info of fine and issued both channels.
![fine channel 2](https://user-images.githubusercontent.com/59352120/71568397-c68b0400-2ae8-11ea-94f7-63af0aa1deec.png)
![issued channel 1 with reencoding](https://user-images.githubusercontent.com/59352120/71568398-c68b0400-2ae8-11ea-8a6b-b65727760761.png)
![issued channel 1](https://user-images.githubusercontent.com/59352120/71568399-c68b0400-2ae8-11ea-950f-4ab2b8f6a1e0.png)
![issued channel 2](https://user-images.githubusercontent.com/59352120/71568400-c7239a80-2ae8-11ea-8b8f-1b81269f7e4d.png)
![issued channel 3](https://user-images.githubusercontent.com/59352120/71568401-c7239a80-2ae8-11ea-86a7-f6dd22ffac91.png)
![fine channel 1](https://user-images.githubusercontent.com/59352120/71568402-c7239a80-2ae8-11ea-962e-db92f38bc4db.png)

**Comment by MuhammadShozab** [comment]
issue looks like this. on other player like VLC issue is minimum. But i need that specific parameter which can cause this issue. one more thing can be observed that issue is not present on the channel logo because it was static. the moving frames have issue basically.
![actual issue](https://user-images.githubusercontent.com/59352120/71569926-2b982700-2af4-11ea-99c9-b45816b49917.jpg)

**Comment by sindresorhus** [comment]
I think you opened this on the wrong repo.
