### ISSUE TITLE
OGV file identified as audio/ogg

### ISSUE THREAD

**Issue by brunobg** [sindresorhus/file-type#29]
Tried to identify an OGV file and it was interpreted as audio:

{ ext: 'ogg', mime: 'audio/ogg' }

**Comment by sindresorhus** [comment]
The OGG container has the same magic number (marker to identify the type) for both audio and video. So not sure whether there's any way to tell them apart.

https://en.wikipedia.org/wiki/Ogg

**Comment by brunobg** [comment]
Apparently you have to read the ogg container data. It certainly is possible. `file` does it: 

```$ file video.ogv
video.ogv: Ogg data, Theora video```

If you can't, I suggest you return `application/ogg` instead of `audio/ogg` at least, and keep the original file extension instead of converting it to ".ogg".

**Comment by Alcotana** [comment]
I encountered this problem too.
