### ISSUE TITLE
ASF/.asf detection is missing / broken

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#290]
I believe there is no `.asf` detection, currently.

The [ASF](https://en.wikipedia.org/wiki/Advanced_Systems_Format) media container is now always mapped to `.wma` or `.wmv`, depending on the stream time.

If `.asf` is provided, it will be incorrectly detected as `.wma` or `.wmv`.

The way, I thinkt, it should work:
1. ASF using Windows Media Audio and Video codecs should map to `.wma` and `.wmv`.
1. Other ASF files should map to `.asf`.

Blocks #240.

ASF / `.wmv` video:
![image](https://user-images.githubusercontent.com/23255260/71770656-63a5cc80-2f2f-11ea-8667-68b2b1d280b4.png)

ASF / `.asf` video:
![image](https://user-images.githubusercontent.com/23255260/71770662-859f4f00-2f2f-11ea-858f-4045c6faa7c2.png)

**Comment by Borewit** [comment]
I will add ASF codec support first in [music-metadata#392](https://github.com/Borewit/music-metadata/issues/392).

**Comment by Borewit** [comment]
@sindresorhus, I think we should detect as `.asf` and drop support for `.wma` or `.wmv.`

Similar as:
- Matroska: #271, #272 
- MS-CFB: #377

I think we should detect the container format, and not guess the specific type if we are not sure.

**Comment by sindresorhus** [comment]
> I think we should detect the container format, and not guess the specific type if we are not sure.

👍🏻
