### ISSUE TITLE
.sub file is detected as video/mpeg

### ISSUE THREAD

**Issue by Asuanin** [sindresorhus/file-type#303]
I have file with subtitles in format .sub, bud is detected as 'video/mpeg'.
MediaInfo:
General
Complete name          : \...\subtitle.sub
Format                        : MPEG-PS
File size                       : 4,60 MiB
Duration                     : 1 h 29 min
Overall bit rate           : 7 196 b/s
FileExtension_Invalid  : mpeg mpg m2p vob vro pss evo

Text
ID                               : 189 (0xBD)-32 (0x20)
Format                       : RLE
Format/Info               : Run-length encoding
Muxing mode            : DVD-Video
Duration                    : 1 h 29 min

Node.js: 8.11.3
File-type: 8.1.0
[subtitle.zip](https://github.com/sindresorhus/file-type/files/4050551/subtitle.zip)

**Comment by Borewit** [comment]
It looks like the container is an [MPEG program stream](https://en.wikipedia.org/wiki/MPEG_program_stream). I don't think it supported yet. The closest thing supported is probably `video/mpeg`, therefor I don't think this is a bug.
