### ISSUE TITLE
Docx files being detected as a zip

### ISSUE THREAD

**Issue by BradleyDHobbs** [sindresorhus/file-type#312]
I am using this library on an AWS ec2 instance. It seems that some docx files are being detected as zip files. I searched through closed issues and there are multiple closed issues and merged PRs about this topic. However, I assume most people aren't using the Windows 10 Office 365 dekstop apps. 

Here's the version of Word I'm using:
![image](https://user-images.githubusercontent.com/8106932/72751383-8110a280-3b8d-11ea-979a-f77e65236e2b.png)

Here is one of the closed issues I referenced above: https://github.com/sindresorhus/file-type/issues/103

I haven't tried other document types using other Office 365 desktop apps (Excel, Powerpoint) but I have a feeling it could be the same issue. I'm going to do some more research and update this post if other file types fail as well. 

For now, I'm attaching a sample docx that is being detected as a zip. This document was created using built in templates on the home page of word. I just chose one of their Resume templates for testing purposes.

Thank you

~~[SampleResume.zip](https://github.com/sindresorhus/file-type/files/4087540/SampleResume.zip)~~
 [UofTCSCoop.docx](https://github.com/sindresorhus/file-type/files/1289212/UofTCSCoop.docx)

**Comment by Borewit** [comment]
I am getting the following type:
```
MIME-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
Extension: docx
```

**Comment by Borewit** [comment]
I gave it another try with the original sample of #103, which gave me an error. Created issue: #313.

**Comment by BradleyDHobbs** [comment]
I can confirm this issue occurs with Powerpoint and Excel too. Both are part of the Office 365 suite.

Here are some samples:

[SamplePowerpoint.pptx](https://github.com/sindresorhus/file-type/files/4091483/SamplePowerpoint.pptx)
[SampleExcel.xlsx](https://github.com/sindresorhus/file-type/files/4091486/SampleExcel.xlsx)
