### ISSUE TITLE
End-Of-Stream error thrown parsing docx

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#313]
Reading the sample file from issue #103 [UofTCSCoop.docx](https://github.com/sindresorhus/file-type/files/1289212/UofTCSCoop.docx), an _End-Of-Stream_ exception is thrown.

Related: #312

**Comment by Borewit** [comment]
First get PR #315 in.

**Comment by alecgibson** [comment]
We're getting a similar thing on a `.png` image, although unfortunately I can't share the image.

**Comment by Borewit** [comment]
@alecgibson, I can prevent the error, I cannot fix the recognition of your PNG, for that I need a sample.
If you manage to find picture you can share, please open a new issue.

**Comment by alecgibson** [comment]
@Borewit Looks like that's fixed our `.png` issue 👌 Thanks for the quick response! 🙌

**Comment by lozthiensu** [comment]
I still get the error with the png file``
`
node-| error Error: End-Of-Stream
node-|     at ReadStream.StreamReader.s.once (/home/node/xproject/node_modules/peek-readable/lib/index.js:28:46)
node-|     at Object.onceWrapper (events.js:286:20)
node-|     at ReadStream.emit (events.js:203:15)
node-|     at ReadStream.EventEmitter.emit (domain.js:448:20)
node-|     at endReadableNT (_stream_readable.js:1143:12)
node-|     at process._tickCallback (internal/process/next_tick.js:63:19)

`
