### ISSUE TITLE
index.js in published package only has fromFile

### ISSUE THREAD

**Issue by DanielHeath** [sindresorhus/file-type#314]
The compiled/distributed package on npm (v13.1.1) has an `index.js` which only exports `fromFile`. 

You can work around this by using `import x from 'file-type/core'`, but it's a bit of an odd wrinkle.

**Comment by sindresorhus** [comment]
We do: https://github.com/sindresorhus/file-type/blob/fd1f32da048135fe6cf9a2df80cf54f1a8173f84/index.js#L18

**Comment by DanielHeath** [comment]
Huh. Apparently I can't read; disregard that.
