### ISSUE TITLE
SVG files are misidentified

### ISSUE THREAD

**Issue by brunobg** [sindresorhus/file-type#32]
ext=m4v, mime=video/x-m4v

**Comment by sindresorhus** [comment]
SVG files aren't supported. If you pass a text file it's always a chance it's going to incorrectly match a binary pattern.

**Comment by arthurvr** [comment]
@sindresorhus Should this be closed?

**Comment by niftylettuce** [comment]
Just ran into this problem, I was using <https://github.com/oliver-moran/jimp> because https://github.com/lovell/sharp has many cross-platform issues.  Jimp uses `file-type`, and I was passing it an SVG and it was not detecting a file type.

**Comment by niftylettuce** [comment]
Nevermind, Jimp doesn't support SVG
