### ISSUE TITLE
stream.unshift() after end event

### ISSUE THREAD

**Issue by HitkoDev** [sindresorhus/file-type#330]
In some cases calling `readableStream.read` can reach the end of the stream (e.g. on a short file, or when stream emits everything in a single chunk), or stream may end for other reasons, causing `readableStream.unshift` to throw an error.

**Comment by Borewit** [comment]
@HitkoDev Can you provide a file and description how to reproduce this issue?

**Comment by HitkoDev** [comment]
Sure:

```js
const buff = Buffer.fom(whatever);

class MyStream extends Readable {
  _read() {
    this.push(buff);
    this.push(null); 
  }
}

const s = new MyStream();
fileType.stream(s).then(res => console.log(res.fileType));
```

**Comment by bencmbrook** [comment]
Interesting.. Our test fixtures should definitely cover this case. Did anything change with the `.stream` tests?

**Comment by bencmbrook** [comment]
@HitkoDev are you reading from your stream _before_ calling `fileType.stream`?

**Comment by HitkoDev** [comment]
@bencmbrook I'm not reading from source stream, I'm always reading from the stream returned by fileType. As I said, this usually happens when dealing with really small files, file uploads, or any other readable stream where everything is returned in a single buffer and there's nothing left after https://github.com/sindresorhus/file-type/blob/99beda86b18965cc2245b3a4db54c08fe4e491b0/core.js#L1287

**Comment by bencmbrook** [comment]
Fixed it on my branch, thanks. 

Hey @sindresorhus, any chance I can get repo permissions to PR without a fork?

**Comment by sindresorhus** [comment]
@bencmbrook Oh yeah. I must have forgotten to do that previously... Done. Prefer PRs over pushing directly to master though.

**Comment by Borewit** [comment]
Are you taking care of this one @bencmbrook?

**Comment by bencmbrook** [comment]
@Borewit yes I have a fix, but @sindresorhus I don't think I received the access rights?

```
git push --set-upstream  origin bencmbrook/short-stream
```

```
ERROR: Permission to sindresorhus/file-type.git denied to bencmbrook.
fatal: Could not read from remote repository.
```

**Comment by bencmbrook** [comment]
In the interest of time, my change to `core.js` is 

https://github.com/sindresorhus/file-type/blob/99beda86b18965cc2245b3a4db54c08fe4e491b0/core.js#L1295

to:
```js
		if (readableStream.readableEnded || readableStream._readableState.ended) {
			readableStream.unshift();
		} else {
			readableStream.unshift(chunk);
		}
```

and a test for `test.js`
```js
test('.stream() method - short stream', async t => {
	const buffer = Buffer.from([0, 1, 0, 1]);
	class MyStream extends stream.Readable {
		_read() {
			this.push(buffer);
			this.push(null);
		}
	}

	const shortStream = new MyStream();
	const newStream = await FileType.stream(shortStream);
	t.is(newStream.fileType, undefined);
});
```

**Comment by Borewit** [comment]
Hmm, via comments, is not really the way I guess. but it is good news you took care of the issue.

Maybe push it via [your cloned file-type repo](https://github.com/bencmbrook/file-type)?

**Comment by sindresorhus** [comment]
@bencmbrook You have to accept the invitation.

**Comment by bencmbrook** [comment]
Hah, my bad. Received, thank you.
