### ISSUE TITLE
Support PGP 

### ISSUE THREAD

**Issue by BrendanBall** [sindresorhus/file-type#336]
When I use the unix file command on a pgp encrypted file, it successfully detects it as `PGP RSA encrypted session key ...`
however using this package it returns `undefined`.

Is it possible to support pgp?

**Comment by sindresorhus** [comment]
Sure. PR welcome :)

**Comment by BrendanBall** [comment]
does this reimplement libmagic from scratch in pure javascript? I see there's another package `mmmagic` that just straight uses libmagic, it just unfortunately seems to be unmaintained. E.g. there's an old PR open to add a promise API.

**Comment by Borewit** [comment]
> does this re-implement libmagic from scratch in pure javascript?

[file-type](https://github.com/sindresorhus/file-type) is written in pure JavaScript indeed.

**Comment by Borewit** [comment]
Can you provide fixtures @BrendanBall?

**Comment by BrendanBall** [comment]
sure
