### ISSUE TITLE
m4a from android phone recognizes as 'video/mp4', but should 'audio/x-m4a'

### ISSUE THREAD

**Issue by matvey-b** [sindresorhus/file-type#343]
[Sample m4a file](https://drive.google.com/file/d/1T0Ww6tioQ8Fpje-wgCIMgr_gwDPKQMh9/view?usp=sharing)

Unix `file` util output:
```
matvey-b@laptop-matvey:~/Загрузки$ file sample.m4a 
sample.m4a: ISO Media, MP4 v2 [ISO 14496-14]
```

p.s. thanks for help :slightly_smiling_face:

**Comment by bencmbrook** [comment]
I know MPEG-4s are tricky to distinguish. Should look into what is resolving here for the above sample file
https://github.com/sindresorhus/file-type/blob/cf34c7bc4d41852f82faab7e3f3b058becbf4412/core.js#L437

**Comment by matvey-b** [comment]
I think I misunderstood the problem. In fact, according to [this](https://en.wikipedia.org/wiki/MPEG-4_Part_14) article, this is still an MP4 container :disappointed: And m4a is a special case of mp4. This all means that your library is working properly.

**Comment by bencmbrook** [comment]
That's right - file-type is not wrong to say video/mp4, but sometimes it can be more specific, based on the File Type Box (https://en.wikipedia.org/wiki/ISO_base_media_file_format). I checked this particular file and the ftyp is set to mp42, so we can't be more specific for this file. Closing this issue as it's more a matter of the file itself.
