### ISSUE TITLE
image/mp4?

### ISSUE THREAD

**Issue by avillarubia** [sindresorhus/file-type#345]
Good day,

I saw from your readme file as seen in your npm documentation says

```js
const fs = require('fs');
const FileType = require('file-type');
 
(async () => {
    const stream = fs.createReadStream('Unicorn.mp4');
 
    console.log(await FileType.fromStream(stream));
    //=> {ext: 'mp4', mime: 'image/mp4'}
}
)();
```
is the output really an image for mp4?

Stay Home and Keep Safe everyone.

**Comment by avillarubia** [comment]
@sindresorhus hi there, why close? We haven't got any answers yet.

**Comment by sindresorhus** [comment]
Please look at the close reason. It was fixed in the readme.

**Comment by avillarubia** [comment]
@sindresorhus oh thank you.
