### ISSUE TITLE
Returns End-Of-Stream Error while Uploading .zip file

### ISSUE THREAD

**Issue by DominicAmal** [sindresorhus/file-type#346]
Team, 
I am uploading a **zip file** to find the type of a file and mime-type, for most of the zip file I can get the type but for a few files, I could not get the type but it returns  **End-Of-Stream Error**.

To find the file type I am sending a file as the buffer to the **_fromBuffer()_** method

![2020-04-06 png  1139×92 ](https://user-images.githubusercontent.com/13975445/78564749-8ac7af00-783a-11ea-8856-351dbf7ebf98.png)

Sample file
[raj.zip](https://github.com/sindresorhus/file-type/files/4438833/raj.zip)

**Comment by osdiab** [comment]
If anyone else runs into this it happened to us because we were using `fileTypeFromBuffer` and just downloading the first 4100 bytes of the file; in the case of zip it seems that it needs to decompress the file, which means chopping the file like that breaks things.
