### ISSUE TITLE
Excel (.xls) files detected as application/x-msi

### ISSUE THREAD

**Issue by iffa** [sindresorhus/file-type#348]
Related to #162, #225 

.xls files seem to be detected as msi files, even after msi false-positive fixes. Confirmed on files from Office 2016+, Mac & Windows.

See files: https://drive.google.com/open?id=1OqynCO-kHMolp4QFkiS3dAiBfJ58DYXi

**Comment by sindresorhus** [comment]
From the readme:

> The following file types will not be accepted:
> - .xls - Too old and difficult to parse.

**Comment by iffa** [comment]
Totally missed that note, my bad.

**Comment by msageryd** [comment]
I'm migrating to this library from my old home cooked file checking lib. I had a check for old xls files. Was it flawed? Otherwise, please integrate this test in your lib.

```
//Old XLS files
function isExcel(buf) {
  if (!buf || buf.length < 520) {
    return false;
  }

  return (
    buf[512] === 0x09 &&
    buf[513] === 0x08 &&
    buf[514] === 0x10 &&
    buf[515] === 0x00 &&
    buf[516] === 0x00 &&
    buf[517] === 0x06 &&
    buf[518] === 0x05 &&
    buf[519] === 0x00
  );
}
```
