### ISSUE TITLE
Please add this xls-test

### ISSUE THREAD

**Issue by msageryd** [sindresorhus/file-type#349]
I commented in another issue #348 and just realised that it was closed. I'll repeat myself in a new issue.

I'm migrating to this library from my old home cooked file checking lib. I had a check for old xls files. Was it flawed? Otherwise, please integrate this test into your lib.

```
//Old XLS files
function isExcel(buf) {
  if (!buf || buf.length < 520) {
    return false;
  }

  return (
    buf[512] === 0x09 &&
    buf[513] === 0x08 &&
    buf[514] === 0x10 &&
    buf[515] === 0x00 &&
    buf[516] === 0x00 &&
    buf[517] === 0x06 &&
    buf[518] === 0x05 &&
    buf[519] === 0x00
  );
}
```

**Comment by sindresorhus** [comment]
I already commented in https://github.com/sindresorhus/file-type/issues/348 that we don't have any interest in supporting `.xls`.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/file-type/issues/340 would will let you add the check yourself.

**Comment by msageryd** [comment]
Ok, sorry. I interpreted you comment as "too difficult to parse", hence my attached code. Thanks for your reply.
