### ISSUE TITLE
Possible to use file-type as a transform stream in a pipeline()?

### ISSUE THREAD

**Issue by msageryd** [sindresorhus/file-type#350]
Is there any way to use file-type as a transform stream so I can put it in a pipeline along with some other transform streams. The code would be much more readable if I could get rid of the `await FileType.stream()`

I suppose I would have to read the file info via events instead of finding it in `fileTypeStream.fileType`.

My other transform stream is an md5 and filesize calculator. At the end of the pipeline I upload the file to S3.

I'm sorry if this is a stupid question. I still find streams hard to grasp.

**Comment by sindresorhus** [comment]
// @bencmbrook

**Comment by bencmbrook** [comment]
Is this the API you have in mind? Note that you can't guarantee the filetype is available to the writable at the end of your pipeline (for example, if you're writing a file with `fs.createWritableStream` and using filetype to determine the file extension)

```js
const fileTypeTransform = FileType.stream();

fileTypeTransform.on('file-type', fileType => {
  // Handle filetype event asynchronously
  handleFileType(fileType.ext);
});

stream.pipeline(
  readable,
  fileTypeTransform,
  writable,
);
```

**Comment by msageryd** [comment]
Thanks, that was exactly the api I was hoping for. Unfortunately, I really need the file-type information before streaming the file to S3. Am I guaranteed to get the file-type if I await it like this?

```
        const filePipeline = pipeline(fileStream, fileInfoStream, err => {
          if (err) console.error(err);
        });
        fileTypeStream = await FileType.stream(filePipeline);
```

fileInfoStream will emit an md5 sum via an event when the stream if flushed. This is ok to wait for, because I don't need this until later. But I really need the file-type before moving on.

**Comment by bencmbrook** [comment]
So I don't think the pipeline can help you, as you will need the filetype before initializing your `putObject` (or equivalent) stream to S3.

Yes, you are guaranteed* to get the filetype if you await it like that. *Guaranteed from a control flow perspective, but `fileTypeStream.fileType` can be `undefined` if this lib doesn't detect a known filetype.

```js
const filePipeline = pipeline(fileStream, fileInfoStream, err => {
  if (err) console.error(err);
});

const fileTypeStream = await FileType.stream(filePipeline);

if (!fileTypeStream.fileType) {
  // No file type could be detected, fallback to an error or put the binary into S3 depending on use case
}

s3.putObject({
  ...yourParams,
  Body: fileTypeStream,
  Key: `my-file.${fileTypeStream.ext}`,
  ContentType: fileTypeStream.mime,
});
```

**Comment by msageryd** [comment]
Thank you for your very helpful answers.
Closing this now.
