### ISSUE TITLE
Tar detection seems broken

### ISSUE THREAD

**Issue by jongross** [sindresorhus/file-type#352]
### Tar detection on MacOs seems broken

OS: MacOs 10.15.4
hardware: iMac 5k

node version: 13.13.0
file-type version: 14.2.0

I have built a couple different tarballs on various different systems, and none of them are being detected as tar files.

I've stepped through the ID process, and the headers (masked as your code indicates) are just plain old not matching, so it seems to be failing in the header matches, not in the checksum.

Below is a hexdump snippet from the two tar files that aren't being matched:

`hexdump -n 256 pest.tar
0000000 70 72 6f 63 5f 6d 6f 64 75 6c 65 2e 78 6d 6c 00
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000060 00 00 00 00 31 30 30 36 34 34 20 00 20 20 20 20
0000070 20 30 20 00 20 20 20 20 20 30 20 00 20 20 20 20
0000080 37 32 32 32 36 37 37 20 31 31 36 34 31 31 37 30
0000090 33 34 34 20 20 31 32 33 35 37 20 00 30 00 00 00
00000a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000100`

` hexdump -n 256 orig.tar
0000000 2e 2f 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000060 00 00 00 00 30 30 30 37 35 35 20 00 30 30 30 37
0000070 36 35 20 00 30 30 30 30 32 34 20 00 30 30 30 30
0000080 30 30 30 30 30 30 30 20 31 33 36 35 32 36 31 33
0000090 31 35 31 20 30 31 31 33 31 36 00 20 35 00 00 00
00000a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000100`

I was curious if you could help me identify why the tar match is failing for me.

**Comment by sindresorhus** [comment]
Is the `file` command able to identify them?

**Comment by jongross** [comment]
> Is the `file` command able to identify them?

Yes, the `file` command knows what they are.

**Comment by Borewit** [comment]
Can you please provide a sample file @jongross? Zip the tar archive to be able to drop it here. Preferably very small file size.

**Comment by Borewit** [comment]
Related #241

**Comment by jongross** [comment]
@Borewit I have been trying to reproduce the problem in a way that has a very small file size.  The files are generated from a machine that I don't control, and if I crack them open to remove content to make the file size reasonable, bsd-tar or gnu tar tend to repack into a recognizable tar file.
Would it be possible to provide a sample file (large as it is - 15M or so) in another medium?

**Comment by Borewit** [comment]
> Would it be possible to provide a sample file (large as it is - 15M or so) in another medium?

That would allows me to have quick look, so sure you can post it. Maybe via [wetransfer.com](https://wetransfer.com/)?

At the same time I want to ask you to support resolving this issue by figuring out what the recipe for generating this unidentifiable tar file. I don't like to check-in that 15M file for unit testing, and I try to prevent cutting files (keep that part of the file which is currently used for identifying it) for future compatibility.

**Comment by jongross** [comment]
Yeah, I understand the need for a small test case example.  I am working on that part, but it might take me some time.

**Comment by jongross** [comment]
@Borewit here is an example (large file): https://tmptarfile.s3-us-west-2.amazonaws.com/death.es.f5net.com.qkview

Let me know when you have a copy, and I'm going to delete it.

Still working on generating a small example.

**Comment by Borewit** [comment]
> Let me know when you have a copy, and I'm going to delete it.

Got it.

**Comment by jongross** [comment]
Deleted, and still working on your other request when I have time (create a test case sized example).

**Comment by Borewit** [comment]
> @Borewit here is an example (large file): https://tmptarfile.s3-us-west-2.amazonaws.com/death.es.f5net.com.qkview

@jongross, the file you provided is not directly a tar file, but a gzipped tar file.

**Comment by jongross** [comment]
Yes, I gzipped it for transport.

**Comment by Borewit** [comment]
Issue caused because:
* Tar header was checked at a point only 256 of 512 required bytes (TAR header size) had been read.
* Initial tar file was not identifying positive on the sample provided with issue #352, changed the tar signature to `ustar`.

**Comment by Borewit** [comment]
> still working on your other request when I have time (create a test case sized example).

If you can find a smaller sample tar with spaces padded checksum, that would be great:

```js
if (check([0x20], {offset: 148})) {
		return {
			console.log('Houston, we have found the sample tar we have been looking for');
		};
	}
```
_Be aware that `check` is an internal function in file-type._
