### ISSUE TITLE
Browser compatibility questions

### ISSUE THREAD

**Issue by mizvyt** [sindresorhus/file-type#354]
Hi, a very useful library, thanks a lot for the effort.
I am using this in an Angular application like such:

```
// Important: we're importing from file-type/core as we don't
// want to accidentally try to import 'fs'
import { fromBuffer as mimeFromBuffer } from 'file-type/core';
```

Also using an additional polyfill for `Buffer` type, as it's not a natively available on a browser:
```
(window as any).global = window;
// @ts-ignore
window.Buffer = window.Buffer || require('buffer').Buffer;
```

I was essentially looking for a way to be able to determine a MIME type of a file on the client side. It seems to work perfectly on all modern browsers, but on Edge it seems to fail to load this library because of this tiny line of code below:

https://github.com/sindresorhus/file-type/blob/abc699a07d9d6e471b7a65da48ef2564f08ae9bd/core.js#L41

This is ES6 syntax, which is not supported in Edge or any IE browsers.

Two questions:
* Would it be possible to compile and ship an ES5 version of the library code for compatibility?
* Is there a way to not need to polyfill `Buffer` class and use something like `ArrayBuffer` instead? (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)

**Comment by mizvyt** [comment]
Unless my questions is out of scope of this development effort and this library is not supposed to target client-side javascript at all :grin:

**Comment by sindresorhus** [comment]
This comment https://github.com/angular/angular-cli/issues/9214#issuecomment-461983704 sums it up pretty well. It's up to you to transpile. If Angular makes this difficult, it's a problem for Angular to solve.

As for usage without needing `Buffer`. We cannot use just `ArrayBuffer` as it's missing some methods which makes traversal very inefficient.

**Comment by EvgeniyTT** [comment]
> library is not supposed to target client-side javascript at all

Sorry for a stupid question, but I saw the `browser` section and the 'file-type/browser' module, so I assumed that it supposed to work in a browser. Am I wrong, and it won't/is not supposed to work in a browser? What the `browser` part is for in this case?

@mizvyt have you managed to make it work? I have a [similar issue](https://github.com/sindresorhus/file-type/issues/359), but in my case polyfill `global` and `buffer` wasn't enough. How you have solved the issues with `stream`/`process` dependencies? Or you didn't have ones?

Thanks in advance for any help or advice.

**Comment by Borewit** [comment]
> Sorry for a stupid question, but I saw the browser section and the 'file-type/browser' module, so I assumed that it supposed to work in a browser. Am I wrong, and it won't/is not supposed to work in a browser? What the browser part is for in this case?

Although this module is primary designed for Node.js, using it in the browser is possible as well. That is indeed where 'file-type/browser' intended for. It provides the right dependencies and right functions to the **JavaScript module bundler**. Some dependencies, which are typically present in a Node.js environment, but are missing in a browser environment, you may need to pass (polyfill) to your module bundler. Although in some cases it may a bit tricky to configure it, note that this is a pretty common task handled by a module bundler.

In the [dependents](https://github.com/sindresorhus/file-type/network/dependents) you should be able to find other projects running file type in the browser.

**Comment by mizvyt** [comment]
> @mizvyt have you managed to make it work? I have a [similar issue](https://github.com/sindresorhus/file-type/issues/359), but in my case polyfill `global` and `buffer` wasn't enough. How you have solved the issues with `stream`/`process` dependencies? Or you didn't have ones?

I'm importing directly from `file-type/core`. That module does not have any Node.JS specific libraries imported. The only missing type is `Buffer`, which I am creating a polyfill for. I only really need that part of the library, because I'm passing an `ArrayBuffer` of file bytes that were returned by `reader.readAsArrayBuffer()`.

`file-type/browser` requires `file-type/core` at the top, so it's inherently browser compatible.

**Comment by EvgeniyTT** [comment]
@Borewit @mizvyt thank you both for your help and quick response. After some time I gave up using `fromBlob` or `fromStream`  and went the `fromBuffer` way - it works well.

```
import { fromBuffer } from 'file-type/core';
...
const buffer = await uploadedFile.arrayBuffer();
const types = await fromBuffer(buffer);
```
