### ISSUE TITLE
Example code in ES6

### ISSUE THREAD

**Issue by BryanDollery** [sindresorhus/file-type#36]
What a useful library -- ty. But...

While ES6 is cool and all, the vast majority of the world, including most node devs and all browsers, hasn't advanced that far yet. Examples are great because one can cut and paste them, but your examples aren't that useful to most of us. In fact, it rather detracts from the quality and utility of your library. Can you write a couple of ES5 examples?

Ty again.

**Comment by sindresorhus** [comment]
You can copy-paste the example and use it in Node.js 4 and latest Chrome/Firefox/Edge. Not interested in ES5 examples. If you don't understand the ES2015 semantics it's about time to learn.

**Comment by BryanDollery** [comment]
Thanks for contributing to the community.
