### ISSUE TITLE
Possible bug: Stream gets mangled after passing through FileType.fromStream

### ISSUE THREAD

**Issue by mbssantos** [sindresorhus/file-type#362]
Hey 👋 

I'm doing a fairly simple file upload form with Node streams.
Was having some trouble getting the uploaded files to be read correctly after saving them and eventually noticed the stream was coming back mangled after checking the file type.

That's not much to go by so I made a repo to reproduce the issue.

Repo is https://github.com/mbssantos/file-type-issue 
Should be simple to deproduce: `clone` it, `npm i` and run `node index.js`.

I've only checked PDF files and there seems to be different behaviour with PDF versions 1.3 and 1.4.
The 1.3 ends up empty whereas 1.4 gets the mangling I originally found.

Type checking is done correctly for both though.

Apologies if I'm doing something sily here, but I guess others might come across the same problem.

**Edit:**
I was running with version `14.4.0` but have now tested 
v14.3.0
v14.2.0
v14.1.4
v14.1.3
v14.1.2
v14.1.1
v14.1.0

and all have the same issue. 
Version `14.0.0` is also affected but kinda works - Chrome can't open it but Edge can.

Hope this helps!

**Comment by Borewit** [comment]
You cannot consume a ReadStream twice @mbssantos.
In [`broken`](https://github.com/mbssantos/file-type-issue/blob/8e9916b698f9aa5a2ab7d8cff91b4eb497d117a7/index.js#L4) you essentially write everything what is not read yet to an output stream.

What should support you case is [`FileType.stream(readableStream)`](https://github.com/sindresorhus/file-type#filetypestreamreadablestream). Please bear in mind the side effects that method.

**Comment by mbssantos** [comment]
Didn't know that, thanks for pointing it out!
