### ISSUE TITLE
FileType.fromBlob and fs.stat() is not a function 

### ISSUE THREAD

**Issue by vgouda** [sindresorhus/file-type#364]
Hi i was using the file-type library, but i m facing issue with file-type.

First Approach: I was using this code to get file type i m passing full file data, 
(async () => {
    console.log(await FileType.fromFile(fileData));
})();

but I m getting fs.stat() in not a function error.

second Approach:  I was using this code to get file type i m converting file data to blob and i m trying to get file type using fromBlob() but facing 
/*Code
(async () => {
    const blob = file as Blob
  
    console.log(await FileType.fromBlob(blob));
    debugger;
    //=> {ext: 'txt', mime: 'plain/text'}
  })();
*/

but i m getting fromBlob() in not a function error.
![image](https://user-images.githubusercontent.com/53336319/82645700-f02bff80-9c30-11ea-9223-33a63d883144.png)

**Comment by sindresorhus** [comment]
Are you using it in the browser or Node.js? If browser, what build tool?

**Comment by vgouda** [comment]
In react application i m using, this library

**Comment by vgouda** [comment]
accessing this library through node.js

**Comment by Borewit** [comment]
> but I m getting fs.stat() in not a function error.

I doubt if you are running in node.js (server side) with such an error.

If you are running browser side, use the following:
```js
const FileType = require('file-type/browser'); // "/browser" does load the browser specific functions
```

**Comment by vgouda** [comment]
after i m trying 
const FileType = require('file-type/browser');
this code i m facing the issue, 

intakeFileUpload.tsx:91 Uncaught (in promise) TypeError: FileType.fromFile is not a function
    at _callee$ (intakeFileUpload.tsx:91)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:264)
    at Generator.prototype.<computed> [as next] (runtime.js:98)

**Comment by vgouda** [comment]
i dont know why this error is coming in chrome developer tool console, i installed all the node references still facing the same issue

**Comment by Borewit** [comment]
`FileType.fromFile` is only available in Node.js @vgouda .

The browser is not able to access your file system, so that API is not available on the browser side.

The browser side [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object, can be parsed with `FileType.fromBlob`.
