### ISSUE TITLE
Mime type not being detected using fromStream, despite buffer matching the magic number

### ISSUE THREAD

**Issue by JoePassanante** [sindresorhus/file-type#366]
Hello,

Currently using the latest version, 14.5.0.  I'm streaming two images from a URL using the example [here](https://www.npmjs.com/package/file-type). 

I've had this happen with two different images:

[PNG Image](https://images.static.arist.co/5d1315c147dda60e60b6d7b1/unnamed_67503) with magic numbers of  (taken from first chunk of stream) `<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d>` which matches directly with the stated magic numbers on [Wikipedia ](https://en.wikipedia.org/wiki/List_of_file_signatures) of `89 50 4E 47 0D 0A 1A 0A`

[PNG Image](https://images.static.arist.co/5ebe84da14d4b0013f75377d/LD_187570) with magic numbers of  (taken from first chunk of stream) `<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d>`

Code to reproduce:
```javascript
const url = 'https://images.static.arist.co/5ebe84da14d4b0013f75377d/LD_187570'
const got = require('got').default
const FileType = require('file-type')

async function getMimeType({ url }={}) {
	var downloaded = 0
	var progress = 0

	try {
		const stream = got.stream(url)
		stream.on('data', function(chunk) {
			if (downloaded === 0) {
				console.log(chunk)
			}
			downloaded += chunk.length
			progress = stream.downloadProgress.percent
		})
		let results = null
		try {
			results = (await FileType.fromStream(stream)).mime
		} catch (err) {

		}
		stream.destroy()
		return results
	} catch (err) {
		return null
	}
}
getMimeType({url})
```

**Comment by Borewit** [comment]
I think the issue is in your code:

1. The `stream.on` causes `FileType.fromStream` not to be able to read the stram/
2. You are destroying the stream while you are still reading from it, destroy after the promise is resolved or upon failure.
3. `stream.downloadProgress` is not defined

Working code sample:
```js
const url = 'https://images.static.arist.co/5ebe84da14d4b0013f75377d/LD_187570';
const got = require('got').default;
const FileType = require('file-type');

async function getMimeType({ url }={}) {
  let downloaded = 0;

  try {
    const stream = got.stream(url);
    try {
       const result = await FileType.fromStream(stream);
      stream.destroy();
      return result;
    } catch (err) {
      stream.destroy();
      console.error(err.message);
    }
  } catch (err) {
    console.error(err.message);
  }
}

(async () => {
  const res = await getMimeType({url});
  console.log(res);
})();
````

Outputs:
```
{ ext: 'png', mime: 'image/png' }
```

**Comment by JoePassanante** [comment]
Interesting, I'm not getting any of the errors you described

> The stream.on causes FileType.fromStream not to be able to read the stream

stream.on is an event listener as described here: [Node.js v14.4](https://nodejs.org/api/stream.html#stream_event_data)

And "any" number of event listeners can be attached - so the error shouldn't come from here unless the library overrides this. 

> You are destroying the stream while you are still reading from it, destroy after the promise is resolved, or upon failure.

Destroying the stream happens after the await, regardless of it being in a try-catch

A try catch wouldn't make that section of code async.

> stream.downloadProgress is not defined

This is added by the [ npm got module](https://www.npmjs.com/package/got#downloadprogress )

+ the code posted works for jpegs and other types. 

I think this was closed to early. 

The output I get when I run your code, and simply add an event listener is:
```
progress 0.2709460497346009
progress 0.2709460497346009
progress 0.2709460497346009
progress 0.2709460497346009
progress 0.2713556689593965
progress 0.2713556689593965
progress 0.2713556689593965
progress 0.2713556689593965
progress 0.5505794405284088
progress 0.5505794405284088
progress 0.5505794405284088
progress 0.5505794405284088
progress 0.5509890597532044
progress 0.5509890597532044
progress 0.5509890597532044
progress 0.5509890597532044
progress 0.8302128313222167
progress 0.8302128313222167
progress 0.8302128313222167
progress 0.8302128313222167
The value "-640852500" is invalid for option "size"
```
You can see repeating progress, to demonstrate multiple listeners being able to use .on without interfering with each other. 
```javascript
  try {
    const stream = got.stream(url);
    try {
      stream.on('data',(chunk)=>{
        console.log('progress',stream.downloadProgress.percent)
      })
      stream.on('data',(chunk)=>{
        console.log('progress',stream.downloadProgress.percent)
      })
       const result = await FileType.fromStream(stream);
      stream.destroy();
      return result;
    } catch (err) {
      stream.destroy();
      console.error(err.message);
    }
  } catch (err) {
    console.error(err.message);
  }
```

**Comment by Borewit** [comment]
> stream.on is an event listener as described here: Node.js v14.4

> And "any" number of event listeners can be attached - so the error shouldn't come from here > unless the library overrides this.

Maybe, but by using that handler you are setting the Readable stream in _flowing mode_.
While `file-type` is using the more modern operation: _paused mode_. I think that is was the issue. So you essentially started consuming the stream before file-type.

I probably forgot to install the got module, anyway, I don't think it has to do anything with the issue.

**Comment by JoePassanante** [comment]
You might be right here:

> Readable stream in flowing mode.
While file-type is using the more modern operation: paused mode

From NodeJS docs: [](https://nodejs.org/api/stream.html#stream_choose_one_api_style)

> The Readable stream API evolved across multiple Node.js versions and provides multiple methods of consuming stream data. In general, developers should choose one of the methods of consuming data and should never use multiple methods to consume data from a single stream. Specifically, using a combination of on('data'), on('readable'), pipe(), or async iterators could lead to unintuitive behavior.

**Comment by JoePassanante** [comment]
I'm going to close this - removing the `.on('data')` fixed this.  The problem seemed to be a mismatch in the API the library vs I am using for Streams.

For anyone in the future, you can still use `.on('end')` if you want to record when the stream is terminated.
