### ISSUE TITLE
Add `asar` support

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/file-type#375]
[asar](https://github.com/electron/asar#format) is an archive format that was primarily developed to enclose Electron applications. Here's a [zip of a `fixture.asar`](https://github.com/sindresorhus/file-type/files/4823187/fixture.zip) that can be used in the unit tests.

// @sindresorhus

**Comment by sindresorhus** [comment]
Can you link to a source that describes the actual format in technical terms?

**Comment by Richienb** [comment]
@sindresorhus https://github.com/electron/asar#format

**Comment by dyoshikawa** [comment]
I want to contribute about this.
What mime type is asar?

**Comment by Richienb** [comment]
@dyoshikawa `application/asar`

**Comment by dyoshikawa** [comment]
I made PR https://github.com/sindresorhus/file-type/pull/378 for this issue.
