### ISSUE TITLE
.txt detection broken.

### ISSUE THREAD

**Issue by repiatx** [sindresorhus/file-type#376]
it doesnt detect .txt, interesting 👎  😄

**Comment by sindresorhus** [comment]
There's no way to detect `.txt`. A file with plain text could be anything. CSV, HTML, SVG, etc. This package is meant to detect binary file formats.

**Comment by repiatx** [comment]
> There's no way to detect `.txt`. A file with plain text could be anything. CSV, HTML, SVG, etc. This package is meant to detect binary file formats.

so it wont detect html svg csv too ? sorry if i was rude  😢
