### ISSUE TITLE
make minimumBytes = 4100 public

### ISSUE THREAD

**Issue by FranckFreiburger** [sindresorhus/file-type#381]
https://github.com/sindresorhus/file-type/blob/84c26b373863a774dd5fc3dbbb18ff3c2725e25a/core.js#L12

It would be great to export `minimumBytes` in order to make it available to caller code.

eg.
```
res = await fetch(url, { headers: {
	'Range': `bytes=0-${ FileType.minimumBytes }`,
} });

await FileType.fromStream(res.body);

```

**Comment by sindresorhus** [comment]
It was exposed previously but then removed as we now support file types that might be larger. This constant is just an implementation detail for optimization.

**Comment by Borewit** [comment]
@FranckFreiburger,   check the [FileType.fromTokenizer(tokenizer) example](https://github.com/sindresorhus/file-type#filetypefromtokenizertokenizer) which aiming to read as little as possible using range requests. Depending on the file the required range is determined.
