### ISSUE TITLE
Move magic patterns to JSON file

### ISSUE THREAD

**Issue by matthewbauer** [sindresorhus/file-type#39]
I'm thinking something like this:

``` json
[
    {
        "ext": "jpg",
        "mime": "image/jpeg",
        "patterns": [
            {
                "start": 0,
                "match": "FFD8FF"
            }
        ]
    },
    {
        "ext": "png",
        "mime": "image/png",
        "patterns": [
            {
                "start": 0,
                "match": "89504E47"
            }
        ]
    },
    {
        "ext": "gif",
        "mime": "image/gif",
        "patterns": [
            {
                "start": 0,
                "match": "474946"
            }
        ]
    }
]
```

Would that be worthwhile? Just trying to get some input.

**Comment by sindresorhus** [comment]
Why?

**Comment by matthewbauer** [comment]
I guess this would just be reinventing libmagic but it would be helpful to have one large JSON file that can be used/interpreted.

**Comment by sindresorhus** [comment]
Ok, sure if you do a PR. Make sure to preserve the order as a few of the checks are order-dependent.

**Comment by thisconnect** [comment]
I like! Note that the [mime-type](https://www.npmjs.com/package/mime-type) module have the definitions in a single JSON file, they maintain its own repo for the db (https://www.npmjs.com/package/mime-db) 

How would you use multiple "patterns" would you OR them?
That would work for .mp4 
https://github.com/sindresorhus/file-type/blob/14a48a3f27550089463920e9b992a72fe7c934ae/index.js#L128-L138

How would you define something like avi, where you have buf 0-3 AND buff 8-10 ?
https://github.com/sindresorhus/file-type/blob/14a48a3f27550089463920e9b992a72fe7c934ae/index.js#L176

**Comment by alexanderlperez** [comment]
The current way signatures are tested have an inherent logic to them (no pun intended), so anything that moves the complexity away from the the 'schema' of how the tests are structured seems like goldplating the architecture.  

However, @thisconnect @matthewbauer, something that keeps to the simplicity of actual JS *would* be possible, maybe a reference JSON and a method to compare the stored signatures would be ideal, some thing like (ES5ish psuedocode 😅):

``` 
var ref = require('./reference.json');

function testSignature(file, ref_entry) {
... get the ref and any associated offset data and test against the file
}

// test the various mp4 container signatures saved in the JSON reference
if (testSignature(file, ref.mp4_3gp) || testSignature(file, ref.mp4_isom) || testSignature(file, ref.mp4_etc) || ...) {
 return ...
}

// test the avi signature stored as multiple parts
if (testSignature(file, ref.avi[0]) && testSignature(file, ref.avi[1])) {
 return ...
}
```

At a glance, most of the complexity would may stored in the JSON and how it's formatted. Moving past that and it's almost like defining a new configuration language, ie. building an interpreter.  

Thoughts?

**Comment by thisconnect** [comment]
@alexanderlperez 
> defining a new configuration language, ie. building an interpreter.
yes that is exactly the point. reference.json should contain the patterns and the logic otherwise there is no point in doing this at all IMO.

A signature should contain multiple patterns that are OR'ed and each of these have mutliple rules that are AND'ed. The script should iterate through the signature (and make sure to preserve the order) and test each pattern if ever rule is true.

**Comment by billinghamj** [comment]
I also wonder whether it could be done in more of a hash-map kind of arrangement, rather than an array of possible matches which needs to be looped over.

Also it's worth noting that the current method of having static code is likely to be quite a bit faster than running against an array, due to code optimizations. You might want to generate code from the array ahead of time.

**Comment by alexanderlperez** [comment]
Totally agreed.  It's easier to justify breaking out the file data into a JSON file as a separate project at the moment.

**Comment by Prinzhorn** [comment]
> The current way signatures are tested have an inherent logic to them (no pun intended), so anything that moves the complexity away from the the 'schema' of how the tests are structured seems like goldplating the architecture.

I agree 100% with what @alexanderlperez said. I don't see any reason to separate the checks. The only reason would be to brag about how everything is nicely separated and so clean (aka "goldplating"). But separation creates complexity.

Or in other words: I came to this repo, opened the index.js and **immediately** understood what's going on. It's simplicity is beautiful. It's self documenting. It's trivial to port to other languages. Please don't change it just for the sake of change.

**Comment by tmorehouse** [comment]
I could see this being more of a tree structure, starting at byte 0 and matching on that (and maybe using a hex string and/or `**` as a match for any byte.  Longer key strings could be searched first in the JSON hash, and if failing to match the next longest string is matched. If the string key string matches, and has children, then recursively go down to the next node until a leaf is found.

Wouldn't be very human readable, but would be relatively fast.

**Comment by dimapaloskin** [comment]
Hey, guys.
Some time ago I implemented module which has signatures in the json files and also has supporting or/and conditions.

If someone still to be interested: https://github.com/dimapaloskin/detect-file-type

**Comment by mifi** [comment]
The problem with this simple declarative mechanism is that not all common files can be detected this way. Some have more dynamic detection mechanisms.
For example mkv/webm.
See #67 #69

The best thing would be to implement support for libmagic's magic files, so we can reuse all their declaration files. See #68

**Comment by sindresorhus** [comment]
Closing as this would not be feasible for many file formats.
