### ISSUE TITLE
FileType.{extensions,mimeTypes} is undefined in browser build

### ISSUE THREAD

**Issue by qodeboy** [sindresorhus/file-type#390]
Hello,

Documentation states that `FileType.extensions` and `FileType.mimeTypes` should list corresponding lists. But when accessed from a browser build, both properties are undefined.

## Reproducible demo

Consider following code:

```js
import FileType from "file-type/browser";
console.log(FileType, FileType.extensions, FileType.mimeTypes)
```

It results in following: 

![GrqM5D9s4DJxgr 1](https://user-images.githubusercontent.com/543453/92719229-87959980-f36b-11ea-988b-03806c1408e1.jpg)

Here is the demo: https://codesandbox.io/s/charming-edison-7q4p7?file=/src/App.vue

## Expected behaviour: 

List of supported extensions and mime types are being logged.

**Comment by qodeboy** [comment]
Ok, sorted it out. 

I'm using Nuxt + TypeScript and the thing is initially `file-type` has been throwing error

```log
This dependency was not found:                                                                                                                                                          
* fs in ./node_modules/strtok3/lib/FsPromise.js
```

When imported as `import FileType from "file-type";`. But is appears there is a webpack issue when target is set to `node`, see https://stackoverflow.com/questions/39249237/node-cannot-find-module-fs-when-using-webpack. 

So the solution was to add 

```js
node: {
    fs: "empty"
}
```

To the webpack config and import FileType correctly using `import FileType from "file-type";`

Cheers!

**Comment by Haraldson** [comment]
Your ‘solution’ makes it not crash initially, but it will ultimately when trying to use the `fromFile` in a browser, as `fromBlob` isn’t available anymore in Node mode. This is no fix in my opinion, and it’s really weird that documented properties aren’t there when using the `file-type/browser` edition…
