### ISSUE TITLE
One doubt, the file types .txt, .csv are returned as undefined. Can we consider as which all files like csv txt which are having plain text no magic number or header to find MIME type for those the result would be undefined?

### ISSUE THREAD

**Issue by shah20** [sindresorhus/file-type#397]

**Comment by Borewit** [comment]
See https://github.com/sindresorhus/file-type/issues/395#issuecomment-692483532

**Comment by shah20** [comment]
I saw that, i trying to make a way by using this package. So just wanted a confirmation or info that if it is like that, then can I assume it would be undefined for plain files so that I work in that manner?
