### ISSUE TITLE
file-type throws an "unexpected error" in Internet Explorer

### ISSUE THREAD

**Issue by joshuablokland** [sindresorhus/file-type#403]
file-type throws an "unexpected error" inside Internet Explorer when I use the following:

```
import FileType from 'file-type/browser';
...
const fileType = await FileType.fromBlob(file);
```

In our project we are running with `core-js` polyfills enabled. 
I've also tried out `web-streams-polyfill` but that did not work either.

Has anyone else encountered this issue as well? 
If so any suggestions?

**Comment by joshuablokland** [comment]
If anyone runs into this problem, I managed to solve it.
Turned out we are not transpiling our `node_modules` to ES5.

I added the following rule to our `webpack.config.json`

```
module.exports = (env, argv = {}) => ({
    ...,
    module: {
        ...,
        {
            test: /\.jsx?$/,
            exclude: /node_modules[\\/](?!(file-type|peek-readable|readable-web-to-node-stream|strtok3|token-types)[\\/]).*/,
            use: [{
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env']
                }
            }]
        },
        ...
    }
})
```

**Comment by Tindtily** [comment]
> If anyone runs into this problem, I managed to solve it.
> Turned out we are not transpiling our `node_modules` to ES5.
> 
> I added the following rule to our `webpack.config.json`
> 
> ```
> module.exports = (env, argv = {}) => ({
>     ...,
>     module: {
>         ...,
>         {
>             test: /\.jsx?$/,
>             exclude: /node_modules[\\/](?!(file-type|peek-readable|readable-web-to-node-stream|strtok3|token-types)[\\/]).*/,
>             use: [{
>                 loader: 'babel-loader',
>                 options: {
>                     presets: ['@babel/preset-env']
>                 }
>             }]
>         },
>         ...
>     }
> })
> ```

It works.
But it is not a good solution, the lib should offer the es5 version.
