### ISSUE TITLE
Asar support breaks on asar archives where JSON header size >= 240

### ISSUE THREAD

**Issue by timojaask** [sindresorhus/file-type#406]
The support for asar works only on asar archives where JSON header size is less than 240 bytes.

I'm not sure why this limitation was added in the original PR https://github.com/sindresorhus/file-type/pull/378. It looks like the exact logic came from this PR https://github.com/dyoshikawa/file-type/pull/1/files.

@Borewit do you remember if there was a reason why did you limit it to 240?
`if (jsonSize > 12 && jsonSize < 240 && buffer.length >= jsonSize + 16) {`

You can easily break this by creating an asar archive that contains just a few more files and makes the JSON longer than 240 bytes.

**Comment by Borewit** [comment]
> @Borewit do you remember if there was a reason why did you limit it to 240?

Sorry, I don't remember.

**Comment by Borewit** [comment]
I could not find any reason for the 240 header length limit, therefor I will remove it. Thanks for bringing this to our attention @timojaask.
