### ISSUE TITLE
ERROR in ./node_modules/readable-web-to-node-stream/lib/index.js Module not found

### ISSUE THREAD

**Issue by bude10** [sindresorhus/file-type#408]
With Angular@10.1.6 and file-type@16.0.0 and get the following error in console during startup:
`ERROR in ./node_modules/readable-web-to-node-stream/lib/index.js
Module not found: Error: Can't resolve 'stream' in `

The file exists in node_modules directory, nothing seems wrong.
But using an older version helps. The last version, that works without this error, is file-type@12.4.2

Is there any known issue?
Or what am I doing wrong?

**Comment by Borewit** [comment]
@sindresorhus, can you please review this PR: Borewit/readable-web-to-node-stream#298?

**Comment by bude10** [comment]
@Borewit @sindresorhus thanks for taking care!
