### ISSUE TITLE
Question: User file-type check on frontend

### ISSUE THREAD

**Issue by Tzvetelin88** [sindresorhus/file-type#409]
Is it possible to use file-type on frontend JS application?
I was wondering how to check file before uploading process to storage. Should I read file as blob then check it with file-type and then upload to storage?

**Comment by Borewit** [comment]
It is possible to use it in a frond-end application, see https://github.com/sindresorhus/file-type#browser.

Note that a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) is a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob).

If you need to check the file-type prior pushing it to storage is context specific.

**Comment by Tzvetelin88** [comment]
yes, I need to check it prior on pushing and if type is wrong I will not push to storage and return and error.
Should I perform some king of file transformation after I attach the file and then pass it to the file-type#browser?
When I attach the file I have this file object:
![image](https://user-images.githubusercontent.com/9692941/97539724-25503100-19cb-11eb-8d1f-035ea8b95287.png)

and pass it to the example above I got this error:
Uncaught (in promise) TypeError: Failed to construct 'Blob': The object must have a callable @@iterator property.

Thanks

**Comment by Borewit** [comment]
I think something is wrong with the data part of your File object. Normally there is no reason to transform it. You may want to search on the error message.

**Comment by Tzvetelin88** [comment]
I will check that error.
just to ask regarding Frontend check. Should the file be uploaded somewhere to be checked thru the file-type, like the backend check where the file existing in the storage and I can specify `await FileType.fromFile('<file_path>')`, but in case of user side, the file is not uploaded. 

So when I catch the file: <input type="file" name="test" accept="image/png, image/jpeg" /> should I provide to the file-type  e.taget.value ?

**Comment by Borewit** [comment]
Typically you use some upload form to receive a file in your front end. The file probably need to be uploaded to the browser before you parse it. 

For example: https://audio-tag-analyzer.netlify.app/

You can drag and drop audio files into that, but they only end up in your browser. There is no backend dealing with data. This is using [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) which has a very similar API structure as  [file-type](https://github.com/sindresorhus/file-type).

`await FileType.fromFile('<file_path>')` should only be used in a Node.js environment, where the files is stored on the path specified. No way on earth this is ever going to work in your front-end.

If you want to parse a "remote file", things will be more complicated, here you can find some guidance how to remotely parse a file stored on a cloud from Node.js environment: https://github.com/sindresorhus/file-type#filetypefromtokenizertokenizer. Maybe possible from the front-end as well, but only go there if you really know what you are doing.

**Comment by Tzvetelin88** [comment]
regarding `await FileType.fromFile('<file_path>')`, yes, I mentioned backend - in my case nodejs.
Thanks for the examples will check them.
Need to find a way to load the file in browser and then check it.
One of the ways that I have tried is: (frontend with React JS):

`export function testImage() {
    const [getFile, setGetFile] = useState({
        file: ''
    });

    const check = (e) => {
        let reader = new FileReader();
        reader.onload = function (e) {
            setGetFile({ file: reader.result })
        }
        reader.readAsDataURL(e.target.files[0]);
    }

    useEffect(() => {
        if (getFile.file) {
        //getFile.file is : "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAgESAAMAAAA....."
            (async () => {
                const blob = new Blob([getFile.file], {
                    type: 'image/jpg',
                    endings: 'native'
                });

                console.log(blob)
                let gg = await FileType.fromBlob(blob)
                // gg is type blob with size and type but result is "undefined"
                console.log(gg);
            })();
        }
    }, [getFile])

    return (
        <input
            type="file"
            onChange={(e) => check(e)}
        />
    );
}`

![image](https://user-images.githubusercontent.com/9692941/97579701-0ec1ce00-19fb-11eb-8e1b-86f589c689b4.png)

**Comment by Tzvetelin88** [comment]
I have fixed it...
I change `reader.readAsDataURL(e.target.files[0]);`  to `reader.readAsArrayBuffer(e.target.files[0]);`

**Comment by Borewit** [comment]
```js
const blob = new Blob([getFile.file], {
   type: 'plain/text',
  endings: 'native'
});

let getType = await FileType.fromBlob(blob)
```
can be simplified to:
```js
const getType = await FileType.fromBlob(getFile.file)
```

**Comment by Tzvetelin88** [comment]
@chagins I'm reading the official docs: https://www.npmjs.com/package/file-type 
```If you use it with Webpack, you need the latest Webpack version and ensure you configure it correctly for ESM.```

also check the example here for browser usage: https://github.com/sindresorhus/file-type#browser

**Comment by chagins** [comment]
> @chagins I'm reading the official docs: https://www.npmjs.com/package/file-type `If you use it with Webpack, you need the latest Webpack version and ensure you configure it correctly for ESM.`
> 
> also check the example here for browser usage: https://github.com/sindresorhus/file-type#browser

THX! 👍🏻
