### ISSUE TITLE
Getting undefined file type for buffer

### ISSUE THREAD

**Issue by Yusuf023** [sindresorhus/file-type#411]
I'm sending a file from my client to the node js server as a **base 64 data URL**. Here, I'm converting it to a buffer and trying to determine the file type using FileType.fromBuffer. However, I'm always getting it as undefined. 
The implementation looks something like this:

let buffer = Buffer.from(req.body.file);
FileType.fromBuffer(buffer).then(fileType => console.log(fileType));

**Comment by sindresorhus** [comment]
I would recommend doing some debugging yourself. This is most likely a problem with your code.

Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look.
