### ISSUE TITLE
*.docm was detected was *.docx

### ISSUE THREAD

**Issue by Tzvetelin88** [sindresorhus/file-type#413]
file-type detecting ***.docm** as ***.docx.** 
I don't see file-type to support  **docm**   or I miss something? Thanks

**Comment by Richienb** [comment]
To fix this, we need to add a check for [`application/vnd.openxmlformats-officedocument.wordprocessingml.document`](https://www.iana.org/assignments/media-types/application/vnd.openxmlformats-officedocument.wordprocessingml.document) before the check for `.docx` files.

**Comment by Borewit** [comment]
> "docx" is used for macro-free (non-template) documents, while "docm" is used for macro-enabled (non-template) documents.

**Comment by somebody1234** [comment]
actually internally (inside the docm document) docm has `application/vnd.ms-word.document.macroEnabled.main+xml` as indicated by the entry for `/word/document.xml` for `[Content_Types].xml` - however finding that out usually requires decompressing the DEFLATE-compressed entry so i'm not sure how viable this is

**Comment by Borewit** [comment]
> actually internally (inside the docm document) docm has `application/vnd.ms-word.document.macroEnabled.main+xml` as indicated by the entry for `/word/document.xml` for `[Content_Types].xml` - however finding that out usually requires decompressing the DEFLATE-compressed entry so i'm not sure how viable this is

Good to know, but that is unfortunately a bridge to far.
