### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in '..../node_modules/strtok3/lib'

### ISSUE THREAD

**Issue by haarshjani** [sindresorhus/file-type#414]

**Comment by ibohatyrchuk** [comment]
@haarshjani, as I understand your application is a browser app.
So just use browser version of the library.
`import * as fileType from 'file-type/browser';`

**Comment by garvit-rajput** [comment]
Any update here?

**Comment by Borewit** [comment]
In principle [file-type](https://github.com/sindresorhus/file-type) is written for Node.js, which offers the [fs API](https://nodejs.org/api/fs.html).

If your are using file-type in a browser, make sure you use it as described in [readme.md#browser](https://github.com/sindresorhus/file-type/blob/master/readme.md#browser).
