### ISSUE TITLE
No file type retrieved when reading from Buffer

### ISSUE THREAD

**Issue by jfix** [sindresorhus/file-type#418]
I am trying to use the `file-type` module for an image that exists as  base64-encoded string that is loaded into a `Buffer`, but `undefined` is returned. 

The test case is below. The whole code (including the base64-encoded PNG image) can be found here:
https://runkit.com/jfix/5fc7b2ae8fd621001c660894

```javascript
const FileType = require('file-type');
const b64 = "....";
(async () => {
    try {
        const buffer = Buffer.from(b64, 'utf8');
        const fileType = await FileType.fromBuffer(buffer);
        console.log(`${JSON.stringify(fileType)}`);
    } catch (e) {
        console.log(e.message);
    }
})();
```

The returned `fileType` for this image is `undefined`. When decoding, for example as a data URL `data:image/png;base64,iVBORw0KG...`, the image is correctly displayed in the browser.

**Comment by sindresorhus** [comment]
```diff
-const buffer = Buffer.from(b64, 'utf8');
+const buffer = Buffer.from(b64, 'base64');
```

?

**Comment by jfix** [comment]
Oh yes! 🤦 Thank you and sorry for the noise!

**Comment by ehalca** [comment]
I have the same issue. https://runkit.com/ehalca/6040bfd7f4b46c001a305a52
