### ISSUE TITLE
something wrong of .eot filetype

### ISSUE THREAD

**Issue by Gaubee** [sindresorhus/file-type#42]
![image](https://cloud.githubusercontent.com/assets/2151644/11340450/e326d136-9238-11e5-8cf5-1291ed881538.png)

**Comment by sindresorhus** [comment]
// @junmer

**Comment by junmer** [comment]
@Gaubee can you provide the font file? thx

**Comment by Gaubee** [comment]
@junmer https://drive.google.com/file/d/0B0uxvG4ejitiZlJDSGVmOWxRV3M/view?usp=sharing
