### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by wwhgtt** [sindresorhus/file-type#420]
![image](https://user-images.githubusercontent.com/8405520/101328895-97117980-38ab-11eb-90fc-a1adce3c3a04.png)
![image](https://user-images.githubusercontent.com/8405520/101328935-a5f82c00-38ab-11eb-8956-9351e2a7e8aa.png)

android 7.1   browser

**Comment by wwhgtt** [comment]
options = {
		offset: 0,
		...options
	};

**Comment by wwhgtt** [comment]
Uncaught SyntaxError: Unexpected token ...                            core.js:41

**Comment by wwhgtt** [comment]
android 7.1 browser

**Comment by sindresorhus** [comment]
It's up to you to transpile/polyfill for older browsers. We only support Node.js and modern browsers.
