### ISSUE TITLE
Support for Estonian digital-signed documents

### ISSUE THREAD

**Issue by Yevgeniuz** [sindresorhus/file-type#421]
.asice -  ASiCE container with mime-type "application/vnd.etsi.asic-e+zip"
.asics - ASiCS container with mime-type "application/vnd.etsi.asic-s+zip"
.bdoc - BDOC 2.1 container with mime-type "application/vnd.etsi.asic-e+zip"

All of them are recognized as .zip.

**Comment by Borewit** [comment]
This looks to me a very specific case. The aim of file-type is to recognize common used binary files. The zip detection is presumably not wrong, as this is most likely the container format. Feel free to re-open the issue, with more arguments and fixtures (samples of small files representing the file-type to be supported).
