### ISSUE TITLE
Support Microsoft Compiled HTML Help

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/file-type#422]
> [**Microsoft Compiled HTML Help**](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help) is a Microsoft proprietary online help format, consisting of a collection of HTML pages, an index and other navigation tools. 

Filename extension: `chm`
Media type: [`application/vnd.ms-htmlhelp`](https://www.iana.org/assignments/media-types/application/vnd.ms-htmlhelp)

The magic number is the text [`ITSF`](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help#File_format) in ASCII.

**Comment by sindresorhus** [comment]
PR welcome
