### ISSUE TITLE
Don't support elf file?

### ISSUE THREAD

**Issue by fbs2016** [sindresorhus/file-type#425]
I try to parse an elf file but it return undefined and can't find elf file from "Supported file types".

**Comment by sindresorhus** [comment]
What is an `elf` file?

**Comment by fbs2016** [comment]
Like *.out/*.o file:
sh-5.0$ file hello.out
hello.out: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), with debug_info, not stripped

**Comment by SpraxDev** [comment]
According to Wikipedia
> In computing, the *Executable and Linkable Format* (**ELF**, formerly named *Extensible Linking Format*), is a common standard file format for executable files, object code, shared libraries, and core dumps.

There's sadly no issue template where I can see what info is needed for a new type to be added but I'll try my best:

**Magic numbers** (hex): `7f 45 4c 46`
**Mime type**: `application/x-elf` (Apperantly `application/x-coredump`, `application/x-executable`, `application/x-object` and `application/x-sharedlib` are valid too but less common as they require parsing the file header)
**File extensions** (hard to say as it is used with a lot of variety): `.so`, `.o`, `.elf`, `.bin`

##

You can find some additional information on https://manpages.debian.org/stretch/manpages/elf.5.en.html

**Comment by somebody1234** [comment]
```js
  if (check([0x7F, 0x45, 0x4c, 0x46])) {
    return ['', 'application/x-elf'];
  }
  ```
should work. not sure what to do about file extensions; generally when you're checking the filetype of a binary it probably won't have an extension

**Comment by Marinell0** [comment]
Was this fixed with #514 ?

**Comment by Borewit** [comment]
I think [ELF](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format) has been implemented:

https://github.com/sindresorhus/file-type/blob/41100737d3ee2aa4887beea37f61c8ea2b35c558/core.js#L789-L794

**Comment by regamboa** [comment]
Hi, folks:

I had posted a comment to Sindre via Twitter, who suggested that I repeat it here. The ELF file format is the standard executable format for Linux/Unix, the same way that the Portable Executable format is for Windows. Typically in Unix land, one doesn't use file extensions for executables. Instead, you need to check headers and magic numbers as you have been doing. You managed to spot the magic number, but what you might not realize is that it spells out Unicode character 0x7f followed by 'ELF'.

There's a C library called BFD (binary file descriptors), which is part of the binutils project (https://www.gnu.org/software/binutils/) that makes file checking quite a bit easier.Binutils is also the home for the GNU assembler (gas) and is considered a core part of all Linux distributions. It's also available for Windows via Cygwin and Mac, as well as other OS platforms.

If you want more details on the ELF file format specifically, note that the specification doesn't exist on its own. It's part of the Unix ABI (Application Binary Interface) specification at http://www.sco.com/developers/devspecs/gabi41.pdf. Chapters 4 and 5 provide relevant details on the ELF format.

I've been programming on Linux for...eeek, a couple of decades now, so if you need more information, please feel free to contact me at robygamboa@gmail.com.
