### ISSUE TITLE
Support ICC profile

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/file-type#430]
> [ICC profile](https://en.wikipedia.org/wiki/ICC_profile)

Filename extension: `icm`\
Media type: [`application/vnd.iccprofile`](https://www.iana.org/assignments/media-types/application/vnd.iccprofile)

Magic numbers: `4B 43 4D 53`

**Comment by IgorWiecz** [comment]
This is from the ICC spec (https://www.color.org/specification/ICC.1-2022-05.pdf):
![image](https://github.com/sindresorhus/file-type/assets/91321846/0f112e05-fdd0-4e93-823e-48f3ded6bb2a)

**Comment by yakov116** [comment]
This issue can be closed

**Comment by Borewit** [comment]
Implemented in #601
