### ISSUE TITLE
Support Windows Event Viewer file

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/file-type#431]
> [Windows Event Viewer](https://en.wikipedia.org/wiki/Event_Viewer) file

Filename extension: `evt`\
Media type: `application/octet-stream`? (See the [specification](https://github.com/libyal/libevt/blob/main/documentation/Windows%20Event%20Log%20(EVT)%20format.asciidoc))

Magic numbers: `4C 66 4C 65`

**Comment by sindresorhus** [comment]
Seems very niche. Do you actually need this?

**Comment by Richienb** [comment]
Niche indeed. I'm just putting this here in case someone else needs this, then all the info they'll need to add it will be easy to reach. Is there a better place to store a repository of metadata like this?

**Comment by sindresorhus** [comment]
A closed issue for this is fine by me. I don't want to maintain such a list, but feel free to make a new repo with signatures if that's something you want to maintain.
