### ISSUE TITLE
Application is not loading in IE after installing file-type

### ISSUE THREAD

**Issue by kristinamancheva** [sindresorhus/file-type#435]
Hi, our Angular 8 application is not loading in IE after installing file-type npm package. We get the following error 
![browserErr](https://user-images.githubusercontent.com/14290367/106999556-b54e0580-6786-11eb-92f6-0bcd174d212a.png).
Are we missing something?
Thanks in advance,
Kristina

**Comment by Borewit** [comment]
It looks like a JavaScript feature which is not supported by IE.

Transpiling to Internet Explorer compatible JavaScript is something you will have to care of yourself.

Maybe you find some clues here: sindresorhus/file-type#354
