### ISSUE TITLE
Read blob in nodejs

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/file-type#437]
Nodejs have introduced buffer.Blob and we are about to get them from fs soon also

but they have not introduced the FileReader and likely never will. cuz there are some new file reading methods on the blob now with `.stream()`, `.arrayBuffer()`, and `.text()` that can return promises
so i was thinking maybe you could replace this hole function and just use `blob.arrayBuffer()` instead and maybe polyfill `blob.prototype.arrayBuffer()` if it dose not exist

https://github.com/sindresorhus/file-type/blob/2cc0869dcb4381b2223d6759e3f5a8542b1e7975/browser.js#L18-L45

I have also another concern, is it really necessary to read the hole blob into memory?
isn't the first and last 1000 bytes or something only needed?

it would seem more efficient to do something like:
```js
chunk = new Blob([
  blob.slice(0, 4500),
  blob.slice(-4500)
]).arrayBuffer()
```

I would aslo suggest that you use Uint8Array, ArrayBuffer and DataView instead of using nodes Buffer as that would lower the browser bundle and not drag in any of nodes core modules.

I would also suggest that you make your `fromStream` method acceptable of a AsyncIterator that yields Uint8Arrays instead of relying on either node streams or whatwg streams or nodes EventEmitter since it could lower the bundle even a lot further
since node stream are already async iterable. and whatwg streams are too but no browser have implemented it.

**Comment by jimmywarting** [comment]
Hmm, i quite like what you are doing but i would like a un-opinionated layer of the magic number - kind of how [mime-db](https://www.npmjs.com/package/mime-db) is to [mime](https://www.npmjs.com/package/mime). mime-db is just pure JSON and dose not contain any logic to remain as un-opinionated as possible. and mime adds a api layer on top of it.

Not saying you have to go and make some new npm module called magic-db or something - just a json file within your project would also be enough so one could do `require('file-type/magic.json')` or something - that would be nice 🙂

**Comment by Borewit** [comment]
> I would also suggest that you use Uint8Array, ArrayBuffer and DataView instead of using nodes Buffer as that would lower the browser bundle and not drag in any of nodes core modules.

As you also correctly indicated, at the very beginning in the dependency tree: https://github.com/Borewit/token-types/issues/245, I propose to investigate the suggestion starting from there.

>I would also suggest that you make your fromStream method acceptable of a AsyncIterator that yields Uint8Arrays instead of relying on either node streams or whatwg streams or nodes EventEmitter since it could lower the bundle even a lot further
since node stream are already async iterable. and whatwg streams are too but no browser have implemented it.

Sounds interesting as well.

> just a json file within your project would also be enough so one could do require('file-type/magic.json')

That would suite those file type detections based on simple magic number.
