### ISSUE TITLE
Edge Legacy (44): Expected identifier, string or number

### ISSUE THREAD

**Issue by carter-et** [sindresorhus/file-type#438]
```FileType.fromBlob(blob)``` implements logic w/ `...x`. This isn't supported in some legacy browsers, and can cause issues like seen here. Same logic is fine on Chrome.
https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number

_This is my first time raising an issue, please let me know if I'm being rude or if there is a community standard I should be following._

_Thanks for the awesome package, - Ethan_

**Comment by sindresorhus** [comment]
We only support modern Node.js versions and modern browsers. It's up to you to transpile/polyfill for older browsers.
