### ISSUE TITLE
Support DWG File

### ISSUE THREAD

**Issue by bireycikan** [sindresorhus/file-type#440]
[DWG file](https://en.wikipedia.org/wiki/.dwg)

Filename extension: dwg, dws, dwt
Media type: application/acad

Magic numbers: 41 43

**Comment by Ephigenia** [comment]
@bireycikan I’ve opened a PR for this file format and also tested it on a random DWG file from the net which works fine.

While verifying that 41 43 is correct I also found this list here: https://gist.github.com/ldong/f334b9dcd421c99e094d which states that 41 43 31 30 is also correct.

**Comment by somebody1234** [comment]
re: media type... wikipedia says `image/vnd.dwg`, [autodesk](https://forge.autodesk.com/ja/node/1650) says `https://forge.autodesk.com/ja/node/1650`

**Comment by somebody1234** [comment]
as for the headers for DWGs - it seems to be just the version numbers on the [wikipedia page for dwg](https://en.wikipedia.org/wiki/.dwg) - in the case of AC10XX versions (well, AC1015 and above - not sure where you'd be able to find files older than that), anyway

**Comment by somebody1234** [comment]
relevant:
[libredwg tests for header](https://github.com/LibreDWG/libredwg/blob/280ef56d1b38298947e1cd5d43edfb68203845e2/test/unit-testing/common_test.c#L79-L92)
[raw headers in libredwg](https://github.com/LibreDWG/libredwg/blob/f46b3f0fa33bc4359a8a3f0c120ec54d84d6f8b7/src/common.c#L33-L91)
