### ISSUE TITLE
Zip File Type Determination Slow When Using fromTokenizer Method

### ISSUE THREAD

**Issue by valeeum** [sindresorhus/file-type#443]
When running a zip file through the following code, it takes a minute to determine fileType of a 1.4MB zip file and hangs for a file that is 24MB large without completion.  I read a few other threads suggesting to use Buffer to read but unsure how to handle when using the fromTokenizer method.  

```js
        const s3 = new AWS.S3({ apiVersion: "2006-03-01" });
        const s3Tokenizer = await makeTokenizer(s3, {
          Bucket: bucket,
          Key: key,
        });
        const fileType = await FileType.fromTokenizer(s3Tokenizer);
```

**Comment by Borewit** [comment]
> When running a zip file through the following code, it takes a minute to determine fileType of a 1.4MB zip file and hangs for a file that is 24MB large without completion.

The purpose of [`@tokenizer/s3`](https://github.com/Borewit/tokenizer-s3) is to increase the efficiency compared to the conventional way of reading a file entirely and then parse it. As you demonstrated, this selective pulling of chunks is not always more efficient. The zip file is parsed by file-type from the beginning to end searching for filenames indicating a more specific file type than zip. That is causing so many partial reads, it getting that slow. I am not sure if this detection can improved.

To read from a Buffer you can use [FileType.fromBuffer(buffer)](https://github.com/sindresorhus/file-type#filetypefrombufferbuffer).
