### ISSUE TITLE
MPEG sync check at odd offset required?

### ISSUE THREAD

**Issue by somebody1234** [sindresorhus/file-type#445]
https://github.com/sindresorhus/file-type/blob/fd1e72c8624018fe67a50edcd1557f153260cdca/core.js#L1345

no idea what it's actually supposed to be.

**Comment by sindresorhus** [comment]
What exactly is the logic error?

**Comment by somebody1234** [comment]
`start < 2 && start < (buffer.length - 16)`?
if it's working as intended, maybe converting to `Math.min` to make it consistent with other places in the file might be good

**Comment by Borewit** [comment]
The reason it is there is to search of the sync words on add starting value. Which is actually only at offset 1 in addition to 0. 
And most MPEG decoders can handle an arbitrary amount of garbage preceding the MPEG frames, but there is no reason it should be there. 
In principle the MPEG stream can be preceded by an ID3 header, but this has already been covered with an recursion.

I am note sure why this still there actually, I think it is no longer needed.
