### ISSUE TITLE
vcard are considered as a ics calendar

### ISSUE THREAD

**Issue by mdartic** [sindresorhus/file-type#446]
Hello,

I try the lib on a `.vcf` file, that begin with `BEGIN:VCARD`, and file-type return `{
  "ext": "ics",
  "mime": "text/calendar"
}`.

Maybe it's related to the [detection of ICS](https://github.com/sindresorhus/file-type/blob/main/core.js#L914-L919).

Would it be better to detect `ics` files with `BEGIN:VCALENDAR` ? That would allow to detect `vcf` files with `BEGIN:VCARD` ?

**Comment by mdartic** [comment]
I create the PR https://github.com/sindresorhus/file-type/pull/451
Please check it if you have some time :-)

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/file-type/pull/451.
