### ISSUE TITLE
Can file-type recognize text/xml mime type?

### ISSUE THREAD

**Issue by yarynakorduba** [sindresorhus/file-type#447]
Hi!
I wonder: is it possible to validate the files with `text/xml` mime type? From what I've seen in the library, the list of MimeTypes only includes `application/xml` mime. Is `text/xml` omitted? Or are such files treated as `application/xml` files?

Thank you in advance for the answer :)

**Comment by sindresorhus** [comment]
From the top of the readme:

> This package is for detecting binary-based file formats, not text-based formats like .txt, .csv, .svg, etc.

**Comment by sindresorhus** [comment]
The best way to detect XML-based formats is to run it through an XML parser. Example: https://github.com/sindresorhus/is-svg/blob/034967d4053dd6ca907a6bfeb047cd61b4c12f0a/index.js

**Comment by Borewit** [comment]
Add-on for file-type to support XML based formats: [@file-type/xml](https://github.com/Borewit/file-type-xml)
