### ISSUE TITLE
unshift stream support

### ISSUE THREAD

**Issue by twiggy** [sindresorhus/file-type#452]
A few issues have pointed out that the stream becomes broken\altered after to fromStream is called. 

its a pretty serious side effect that wouldn't be obvious at all.

we are currently working around this issue by calling stream.read(xxxx) and then stream.unshift. Maybe unshift could be an argument to stream.read() ... or maybe the chunk read could be passed back. 

For us we get a stream from the http request, want to detect file type, but then immediately need to pass the stream to AWS's s3 sdk ... bit weird and we could probably just write the file, but unshift seems to work for now.

```js	
let leadingChunk = stream.read(4100);
let {ext, mime} = await fileType.fromBuffer(leadingChunk);
stream.unshift(leadingChunk);
```

**Comment by Borewit** [comment]
> A few issues have pointed out that the stream becomes broken\altered after to fromStream is called.

I think you mean that the concept of a stream has been misunderstood in other issues. `fromStream` reads from a stream, and then the stream get (partially) consumed. That is how streams work. 

I do understand the need to peek ahead, determine the right file type from the stream, and read from the stream as if nothing happened. For that use case [`stream(readableStream)`](https://github.com/sindresorhus/file-type#filetypestreamreadablestream) has been designed. Which is very similar to the example you provided. You directly see limitations, how much data will you buffer (this should be better documented, need to finalize #434).

Related: 
* An attempt overcome the limited buffer length in `stream()`: #300
* Similar misunderstanding related to consuming streams: #426 

> For us we get a stream from the http request, want to detect file type, but then immediately need to pass the stream to AWS's s3 sdk ... bit weird and we could probably just write the file, but unshift seems to work for now.

Writing the file first sounds like reasonable solution to me. You simply do not know how much of the file you need to determine it's file type. The fact that we can determine the file type for many files with the very first few bytes, does not take away the fact that for some files we need much more data.

**Comment by Borewit** [comment]
Related to #399.
