### ISSUE TITLE
Code examples provided in typing definition files have syntax errors

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#471]
Following _import_ style, as found in embedded examples, is a kind of mix between TypeScript & JavaScript, I think.
```js
import FileType = require('file-type');
```

**Comment by sindresorhus** [comment]
No, it's valid TypeScript syntax. However, I want to move to ESM, which will make this question moot: https://github.com/sindresorhus/file-type/pull/468#issuecomment-884835841

**Comment by Borewit** [comment]
Okay 👍🏻
