### ISSUE TITLE
Object returned is null

### ISSUE THREAD

**Issue by DaAwesomeP** [sindresorhus/file-type#48]
My code hasn't changed at all, but in `3.3` and `3.4`, the `fileType()` function returns `null`. My test was with a PNG. I tried both `readChunk()` (asynchronous) and `readChunk.sync()` (synchronous).

**Comment by sindresorhus** [comment]
Can you submit a failing test or share the PNG you tried?

**Comment by DaAwesomeP** [comment]
@sindresorhus Sure!

Test: https://travis-ci.org/AliasIO/Wappalyzer/builds/101977143 
Test Source: https://github.com/AliasIO/Wappalyzer/blob/master/bin/wappalyzer-validate-icons

**Comment by DaAwesomeP** [comment]
@sindresorhus I found the culprit: [anchorCache.png](https://github.com/ioli/Wappalyzer/blob/6e8257906e425f7f2cb62dd9aac24c2aa6517ed7/src/icons/anchorCache.png). It's just a file with a linebreak.

Thank you for your quick response.
