### ISSUE TITLE
DNG is falsely detected as TIFF

### ISSUE THREAD

**Issue by partheseas** [sindresorhus/file-type#480]
I have a couple of test images I've been working with to test something I'm working on, which uses the file-type library. All of my DNG images seem to get falsely picked up as TIFF images (even though it looks like there's an explicit check for DNG in the code).

I've tested with images from three different cameras (a Leica M10, a Nikon D5100, and a Pentax K-70 to be specific.) and would be happy to provide some files.

**Comment by sindresorhus** [comment]
It would be great if you could provide some samples.

**Comment by partheseas** [comment]
https://wormhole.app/ROkvA#5mHM2BDIeffreZiXYLncPw

^ Link is kind of short-lived but should work

**Comment by Borewit** [comment]
I had the look to the issue. DNG is a specialized format of TIFF. 
So this is in principle not wrong, but it would be indicating it is a DNG file would be better.

If we are trying to figure out if a TIFF is a DNG simple magic byte detection, like we are doing now, is not going to be enough. In other words the current detection is to simplistic.

References I used:
* https://wwwimages2.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.5.0.0.pdf
* https://www.loc.gov/preservation/digital/formats/fdd/fdd000073.shtml
* https://www.awaresystems.be/imaging/tiff/faq.html   

I started making the TIFF detection smarter, by actually reading the TIFF tags and their contents, PR: #480.
