### ISSUE TITLE
Docs are off with what users get from NPM 

### ISSUE THREAD

**Issue by Njaah-0** [sindresorhus/file-type#484]
This was merged 29 days ago https://github.com/sindresorhus/file-type/pull/472. However, there's still no release for this so latest version you get is using old API. If user then comes to GitHub to read the docs, it can be quite confusing.

My suggestions is that short notice about this is added to README. Unless you plan on making the new release in a very near future, of cource

**Comment by sindresorhus** [comment]
It's expected knowledge that the readme you see when landing on a repo is dev. This is how most project work. You should look at the correct tag or npm page for docs for the latest version.

**Comment by Njaah-0** [comment]
Yeah, it was just a suggestion as it's quite common to end up on GitHub page instead of NPM and major API rewrites are not very common so I think people don't so often worry about differences between latest release and master. And in my experience major breaking changes are often mentioned in docs so I thought I would suggest it here too.

Thanks for the fast reply.
