### ISSUE TITLE
Type detection failing for webm format file

### ISSUE THREAD

**Issue by Abhinav-grd** [sindresorhus/file-type#485]
I have a ubuntu screen Recording File of webm format for which type detection fails

File - https://drive.google.com/file/d/1g14wtH7qNpzfA1eMVqYCjPHBgQhs8nNU/view?usp=sharing

I am using ```FileType.fromBuffer(filedata);```

**Comment by Borewit** [comment]
Doc-type is incorrectly read due to trailing null-octets, which should be supported according the standard.

Ref: [EBML 11.1.3. Terminating Element Data](https://tools.ietf.org/id/draft-ietf-cellar-ebml-03.html#terminating-element-data)
