### ISSUE TITLE
Type detection fails for JPG file 

### ISSUE THREAD

**Issue by Abhinav-grd** [sindresorhus/file-type#487]
I am following the example -
Determine file type from a Buffer, which may be a portion of the beginning of a file:

```
import {fileTypeFromBuffer} from 'file-type');
import readChunk from 'read-chunk';

const buffer = readChunk.sync('Unicorn.png', 0, 4100);

console.log(await fileTypeFromBuffer(buffer));
//=> {ext: 'png', mime: 'image/png'}
```

But type detection is failing for some **JPG** file, using the same number of bytes (**4100**).

I don't have the file as the file type detection was done client side, 

Just want to know if file data at the end of file is required to detect **JPEG or JPG** file type

**Comment by Abhinav-grd** [comment]
Found the answer, sorry should have done a little more research,
From wikipedia:

    JPEG image files begin with FF D8 and end with FF D9.

http://en.wikipedia.org/wiki/Magic_number_(programming)

**Comment by Borewit** [comment]
We conclude it's a jpg if the file starts with `FF D8 FF`:

https://github.com/sindresorhus/file-type/blob/d556d4e8dbdc0ba96737793de83af503cd74a86a/core.js#L140-L145
