### ISSUE TITLE
Do you accept entries that don't have MIME?

### ISSUE THREAD

**Issue by T1st3** [sindresorhus/file-type#49]
I'm thinking of RPM files (which loosely are to Fedora & friends what DEB files are to Debian and Ubuntu). These files can be detected with magic numbers like other file-types, but to my mind, don't have a proper MIME.

**Comment by sindresorhus** [comment]
All entries should have a MIME, but I'm happy to just invent one if you can't even find an unofficial one somewhere on the web. Could be `application/x-rpm`, like `deb`: https://github.com/sindresorhus/file-type/blob/2bcbd763aa26de0430c4cef70cf15f11a6b236c6/index.js#L382
