### ISSUE TITLE
Keep CommonJS API function names

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#494]
I propose to keep the old style API function names, so `fromBuffer` instead of `fileTypeFromBuffer`. 
Maybe I mess the point, but I failed to see any reason why these function need to be made kind of global unique as part of this transition.
I think by sticking to old API, we will ease the transition from CommonJS to ECMA Modules for users.

Let's discuss #493 first, as this may solve some method classes in core.js and better separate internal (private) functionality from exposed (public) functionality.

**Comment by sindresorhus** [comment]
Imagine thousands of lines into a file, you see a call to `fromBuffer`. What does it mean? It needs some context. Previously, we had the namespace `fileType.` for that.

**Comment by sindresorhus** [comment]
> I think by sticking to old API, we will ease the transition from CommonJS to ECMA Modules for users.

People have to change each import and callsite anyway.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#readable-named-exports

**Comment by Borewit** [comment]
> Imagine thousands of lines into a file, you see a call to fromBuffer. What does it mean? It needs some context. Previously, we had the namespace fileType. for that.

Not sure what you mean with that. but what I propose is the following, to replace CommonJS style

```js
const FileType = require('file-type');
````
with ES style
```js
import * as FileType from 'fileType';
```
or
```js
const FileType = await import('file-type');
```

that way `FileType.fromBuffer()` does not need to change into  `FileType.fileTypeFromBuffer()` or into `fileTypeFromBuffer()` depending on the way it is imported. I think that is more consistent and prevent unnecessary long method names.

**Comment by sindresorhus** [comment]
`fileTypeFromBuffer()` is shorter than `FileType.fromBuffer()`.

**Comment by sindresorhus** [comment]
I think `import * as FileType from 'fileType';` is an anti-pattern. The package author should decide whether the package makes sense as individual imports or a default export namespace.

**Comment by sindresorhus** [comment]
Of course we could have made it `import FileType from 'fileType';`, but I think it makes more sense to use named exports when a package export multiple "main" APIs. Named exports also help with tree-shaking.

**Comment by Borewit** [comment]
> I think import * as FileType from 'fileType'; is an anti-pattern. 

Is it? I guess this the essence of this discussion. If this should be avoided at all costs, I see a reason to change. 

I think this acts as convenient namespace kind of mechanism.  The Node.js API is exposed like this. 

>  Named exports also help with tree-shaking.

Hmm, I see that. At a minimum what we want to achieve is that Node.js stuff is falls of the tree, one way or another to allow maximum flexibility of this package. Yet given the Node.js is already seperated from browser, there is not a lot which could be eliminated.

**Comment by sindresorhus** [comment]
> Is it? I guess this the essence of this discussion. If this should be avoided at all costs, I see a reason to change.

Wildcard import can be useful if a package exports ambiguous named exports or a lot of the named exports cause naming conflicts. It's mostly been used a bridge to import CommonJS packages into ESM since CommonJS default export did not translate to default ESM import. Wildcard can also be useful to re-export stuff between modules internally in the package.

> The Node.js API is exposed like this.

The Node.js API is not a good example, as it does what it does for legacy reasons. The Node.js API actually supports both default import and named import for most APIs for that reason.

**Comment by Borewit** [comment]
I forgot about the default exports, can we used that instead?

```js
import FileType from 'fileType';
````

You probably don't like that, as it makes it harder to shake out individual methods.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/file-type/issues/494#issuecomment-922446671

**Comment by sindresorhus** [comment]
I generally prefer default exports, but in this case, I thought named exports where valuable, both for tree-shaking, and also since there really are 4 main APIs, not one.

**Comment by sindresorhus** [comment]
This is now released: https://github.com/sindresorhus/file-type/releases/tag/v17.0.0

Named export is the way to handle things in ESM when you have multiple main exports. I know it's different from how it's been done before.

**Comment by sindresorhus** [comment]
Also, FYI: https://github.com/sindresorhus/file-type/runs/4315230576?check_suite_focus=true
