### ISSUE TITLE
Undefined fileTypeFromBlob in browser?

### ISSUE THREAD

**Issue by cain** [sindresorhus/file-type#495]
VERSION: 16.5.3

Hi, im new to this npm module so please let me know if im missing something or incorrect :) This is only looking at the browser not node.

The readme for browser says:
```
import {fileTypeFromBlob} from 'file-type';
```
Which for me results in undefined on the frontend??

See example: https://codesandbox.io/s/cool-thunder-58k3x?file=/src/index.js

Removed from readme:
https://github.com/sindresorhus/file-type/commit/287e361099e2bc2caab3e0e2eb3ab5087221729e#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15

**Comment by cain** [comment]
I spent 45mins trying to figure out why it wasnt working, so might be worth updating the docs 😅

**Comment by sindresorhus** [comment]
Make sure you're reading the docs for the version you're using. The readme in the repo reflects the latest development version (this is how most projects on GitHub work).

**Comment by cain** [comment]
@sindresorhus fair enough my mistake, i just always assumed main branch is up to date with the latest version with some sort of dev branch

**Comment by sindresorhus** [comment]
The new release is out: https://github.com/sindresorhus/file-type/releases/tag/v17.0.0
