### ISSUE TITLE
FileType.fromFile htm/html file returns undefined ！

### ISSUE THREAD

**Issue by luobin100** [sindresorhus/file-type#498]
hi, there.  
I use FileType.fromFile against a htm or html file, returns undefined. 

file-type version：16.5.3
node version: v10.16.3

### this is the html file (archived by zip):
[New Issue · sindresorhus_file-type.html.zip](https://github.com/sindresorhus/file-type/files/7294952/New.Issue.sindresorhus_file-type.html.zip)

### this is my code:
```node
const FileType = require('file-type');

(async () => {
    var file = '/yourpath/New Issue · sindresorhus_file-type.html';
    const type = await FileType.fromFile(file);
    console.log(type);
})()
```

**Comment by sindresorhus** [comment]
From the top of the readme:

> This package is for detecting binary-based file formats, not text-based formats like .txt, .csv, .svg, etc.
