### ISSUE TITLE
file-type does not work in browsers

### ISSUE THREAD

**Issue by steeply** [sindresorhus/file-type#505]
I get different kinds of errors when using file-type v.17

1. 
`import {fileTypeFromBlob} from 'file-type';`
Error:  Attempted import error: 'fileTypeFromBlob' is not exported from 'file-type'.
 
2.
`import {fileTypeFromStream} from 'file-type';`
Error: 
./node_modules/file-type/core.js
 Module not found: Can't resolve 'node:buffer' 

This happens on all browsers Chrome, Yandex, Safari
Judging by the Issues, the problem is not only with me.

**Comment by baiy** [comment]
I have the same problem

**Comment by Borewit** [comment]
I think this the same issue as #502, please see my response: https://github.com/sindresorhus/file-type/issues/502#issuecomment-989819146

**Comment by jankapunkt** [comment]
I wonder why with the new versions these dependencies are introduced anyway?

**Comment by Borewit** [comment]
> I wonder why with the new versions these dependencies are introduced anyway?

Although that statement is a bit vague, I guess you will find your answer here: #248
