### ISSUE TITLE
Detect SOF55 marker to distinguish JPEG-LS from baseline JPEG

### ISSUE THREAD

**Issue by hackermd** [sindresorhus/file-type#506]
The library currently checks the first three bytes of the file (``0xFF``, ``0xD8``, and ``0xFF``) to determine whether it is a JPEG file:

https://github.com/sindresorhus/file-type/blob/bb4f8225672b9392ae9e959fc2eb56c7579e5574/core.js#L154-L159

However, to distinguish between baseline JPEG and JPEG-LS the forth byte should also be checked. It it is `0xF7` ("SOF55" or "JPG7" segment), then the file is a JPEG-LS rather than JPEG file and `image/jls` should be returned instead of `image/jpeg`.

**Comment by hackermd** [comment]
It may also be a good idea to check for `0xE8` ("APP8" segment) to further distinguish SPIFF from baseline JPEG.

**Comment by Borewit** [comment]
Sounds good to me, why don't you create a PR?
Can you link to some supporting documentation or reference material?

**Comment by Borewit** [comment]
Small reminder @hackermd

**Comment by somebody1234** [comment]
not sure this is required, afaict neither jpeg-ls nor spiff have a different file extension (or even mimetype)

**Comment by Borewit** [comment]
I found this information: [JPEG Lossless Compression (ISO/IEC 14495), File type signifiers and format identifiers](https://www.loc.gov/preservation/digital/formats/fdd/fdd000151.shtml#sign).

Which describes the _SOF55_ maker, which is actually encoded as `JPG7` at `0xF7`. But the way I read it, more conventional to use the `0xFFF7` at offset 2, which is a marker to indicate the _improved lossless baseline_.
