### ISSUE TITLE
Enforce alphabetical order for supported file types list

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/file-type#511]
I don't want it alphabetical until we have some kind simple script that can enforce it. Otherwise, I'm stuck having to comment about the order on every other pull request.

https://github.com/sindresorhus/file-type#supported-file-types

**Comment by votruongan** [comment]
I think that you can sort the `Supported file types` in `readme.md` once, and write a test to ensure the `Supported file types` in `readme.md` is alphabetically ordered. From then on, every PR will have the description line in the `readme.md` placed appropriately by the author them self. After that, their PR will be checked by the written test. No script needed to run.

Just like how npm enforce alphabetical order: https://github.com/npm/npm-expansions
