### ISSUE TITLE
Require of ES Module not supported

### ISSUE THREAD

**Issue by YagoBiermann** [sindresorhus/file-type#515]
Hello there, i'm using typescript and my package.json is set to module, everything works fine but when i try to import this package like `import { fileTypeFromFile } from 'file-type'`, it throws me an error and say to import with dynamic import, although even with dynamic import the error remains.

![Screenshot 2021-12-24 160623](https://user-images.githubusercontent.com/55931376/147370237-5b5dfb7f-fbb6-496c-8fb8-3725f2509969.png)

some tips to workaround with this?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
