### ISSUE TITLE
fileTypeFromBlob is not exported from index.js

### ISSUE THREAD

**Issue by farid-cognosante** [sindresorhus/file-type#521]
According to the docs for versions 17.x.x the fileTypeFromBlob should be exported from main module 'file-type' instead of 'file-type/browser', but looking at index.js and core.js 'fileTypeFromBlob' is not exported.

**Comment by sindresorhus** [comment]
It's only available in the browser:

https://github.com/sindresorhus/file-type/blob/e4a809e38ccf6b4fdfa457fecf816b4f9f0dbc40/package.json#L16-L17

**Comment by farid-cognosante** [comment]
I tried to import it in my react app like 'import { fileTypeFromBlob } from 'file-type';' but it says:
Attempted import error: 'fileTypeFromBlob' is not exported from 'file-type'.

How should i import this in a react app?

**Comment by sindresorhus** [comment]
> How should i import this in a react app?

This is not really the place to ask for support about React or CRA. It sounds like either your build tool does not support [export conditions](https://nodejs.org/api/packages.html#conditional-exports) or you have not configured your project correctly.

**Comment by tripolskypetr** [comment]
Still not fixed. The whole tool is unusable

**Comment by tripolskypetr** [comment]
For some unknown reasons that import condition worked in vite-react app

```
import { fileTypeFromBlob } from "file-type/core";
```
