### ISSUE TITLE
NextJs Support 

### ISSUE THREAD

**Issue by vusaalab** [sindresorhus/file-type#522]
Tried to use it on the next js, any Idea how to fix this.

```
./pages/test.js:45:0
Module not found: Package path ./browser is not exported from package /Users/nilanga/Development/office/nft-auction/node_modules/file-type (see exports field in /Users/nilanga/Development/office/nft-auction/node_modules/file-type/package.json)
  43 | 
  44 | import { useState } from 'react';
> 45 | import {fileTypeFromStream} from 'file-type/browser';
```

**Comment by sindresorhus** [comment]
Please read the release notes when you upgrade a package: https://github.com/sindresorhus/file-type/releases/tag/v17.0.0

**Comment by vusaalab** [comment]
Thanks for quick replay 

But I tried this no luck

my version   "file-type": "^17.1.1",

`node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.`

**Comment by Borewit** [comment]
Please check issue #502 @vusaalab.
