### ISSUE TITLE
Makes my hero run out of memory while running

### ISSUE THREAD

**Issue by BimoSora** [sindresorhus/file-type#523]
I've tried your code, when run through heroku and upload 100MB file it reads "heroku memory exhausted"

bot.hears(new RegExp(`^[${bot.prefix}](url) (https?:\/\/.*)`,""),async (ctx) => {
  if(ctx.from.id == Number(process.env.ADMIN) || ctx.from.id == Number(process.env.ADMIN1) || ctx.from.id == Number(process.env.ADMIN2) || ctx.from.id == Number(process.env.ADMIN3) || ctx.from.id == Number(process.env.ADMIN4)){
    const url = ctx.text.replace('/url', '').trim();
    if (!url.length) return ctx.telegram.sendMessage(ctx.chat.id, 'No valid url found ')
    await ctx.telegram.sendMessage(ctx.chat.id,'Upload start')
    const buffer = await got(url).buffer()
    const { mime } = await FileType.fromBuffer(buffer)
    let filename2 = ``;
    try {
      filename2 = new URL(url).pathname.split('/').pop();
    } catch (e) {
        console.error(e);
    }
    if (mime.startsWith('video')) {
        await ctx.telegram.sendDocument(ctx.chat.id,buffer,{
          fileName : filename2
        }, {
        })
        await ctx.telegram.sendMessage(ctx.chat.id,'Upload successful')
    } else if (mime.startsWith('image')) {
        await ctx.telegram.sendDocument(ctx.chat.id,buffer,{
          fileName : filename2
        }, {
        })
        await ctx.telegram.sendMessage(ctx.chat.id,'Upload successful')
    } else if (mime.startsWith('application')) {
        await ctx.telegram.sendDocument(ctx.chat.id,buffer,{
          fileName : filename2
        }, {
        })
        await ctx.telegram.sendMessage(ctx.chat.id,'Upload successful')
    } else {
        await ctx.telegram.sendMessage(ctx.chat.id,'File type not allowed')
    }
  }
})

**Comment by Borewit** [comment]
This is not the way to report an issue, this is throwing your problem over the wall.

**Comment by Borewit** [comment]
@BimoSora, to file an issue, you need to change the way you communicate. 

There is clear guidance in the template. Describe the conditions, write a proper introduction, provide the fixture causing issues. We are not interested in irrelevant parts of your code and the memory size of your computer.

As contributor you are obliged to follow its [contributing guidelines](https://github.com/sindresorhus/file-type/blob/e4a809e38ccf6b4fdfa457fecf816b4f9f0dbc40/contributing.md) and [code of conduct](https://github.com/sindresorhus/.github/blob/cd98fc4d6288efde63f64f072973b235dcd63eb8/code-of-conduct.md).
