### ISSUE TITLE
PDF is not detected correctly if it starts with a UTF-8 BOM byte sequence

### ISSUE THREAD

**Issue by tamas-eppel-mediamarkt** [sindresorhus/file-type#527]
Hello,

I have a PDF generated by `Oracle11gR1 AS Reports Services` - `Oracle PDF driver`. We receive this from a third party. This document has three additional bytes at the beginning of the file, and because of this the file-type check fails: returns undefined. However the linux `file` command, or a PDF viewer recognizes the file.

I have attached a file, which shows this problem.

```
❯ file ~/Downloads/test.pdf
/home/teppel/Downloads/test.pdf: PDF document (UTF-8), version F.1, 1 pages (zip deflate encoded)
```

[test.pdf](https://github.com/sindresorhus/file-type/files/7898147/test.pdf)

**Comment by Borewit** [comment]
The PDF file starts with the [UTF-8 BOM byte sequence](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8): `0xEF,0xBB,0xBF`.

**Comment by issuefiler** [comment]
A 8-MB PDF file I’ve got starts with

```
0A255044462D312E340D0A25E2E3CFD30D0A312030206F626A0D0A3C3C0D0A2F54797065202F5061
67650D0A2F4D65646961426F78205B20302030203539352E3332203834312E3932205D0D0A2F5265
736F7572636573203C3C202F466F6E74203C3C202F4631203320302052202F463220342030205220
2F4633203520302052202F4634203620302052203E3E202F4578744753746174650D0A3C3C202F47
5337203720302052202F475338203820302052203E3E202F584F626A656374203C3C202F496D6167
6539203920302052202F496D6167653131203130203020520D0A2F496D6167653133203131203020
52202F496D616765313520313220302052202F496D616765313720313320302052202F496D616765
313920313420302052202F496D61676532310D0A313520302052202F496D61676532332031362030
```
```

%PDF-1.4
%����
1 0 obj
<<
/Type /Page
/MediaBox [ 0 0 595.32 841.92 ]
/Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R /F4 6 0 R >> /ExtGState
<< /GS7 7 0 R /GS8 8 0 R >> /XObject << /Image9 9 0 R /Image11 10 0 R
/Image13 11 0 R /Image15 12 0 R /Image17 13 0 R /Image19 14 0 R /Image21
15 0 R /Image23 16 0
```

And `file-type` gives me an `undefined` for that.

**Comment by issuefiler** [comment]
Ah, I see. `25 50 44 46 2D`, `%PDF-` is the signature and a “U+00`0A` LINE FEED” cut it up. That’s why `file-type` couldn’t see it.

Ha, alright. I’m going to just remove the preceding `0A` if any.
