### ISSUE TITLE
PDF Files cause `fromStream` to never finish

### ISSUE THREAD

**Issue by crossan007** [sindresorhus/file-type#532]
Using 16.5.3, I'm seeing an issue where an `await`'ed call to `fromStream` with a stream of a PDF file never actually resolves

e.g.:
```js
const fileType = await FileType.fromStream(stream);
```

I haven't yet been able to test the 17.x release series due other blocking dependencies.

It seems that removing the `await` from line 592 of `node_modules\file-type\core.js` causes the function to return properly; and suggests a reference to https://github.com/Borewit/strtok3/issues/551

i.e. this "works":
```js
if (checkString('%PDF')) {
	await tokenizer.ignore(1350);
	const maxBufferSize = 10 * 1024 * 1024;
	const buffer = Buffer.alloc(Math.min(maxBufferSize, tokenizer.fileInfo.size));
	tokenizer.readBuffer(buffer, {mayBeLess: true});
```
and this doesn't:
```js
if (checkString('%PDF')) {
	await tokenizer.ignore(1350);
	const maxBufferSize = 10 * 1024 * 1024;
	const buffer = Buffer.alloc(Math.min(maxBufferSize, tokenizer.fileInfo.size));
	await tokenizer.readBuffer(buffer, {mayBeLess: true});
```

**Comment by crossan007** [comment]
Edit: This seems to only appear when the stream supplied to the `fromStream` method is a `PassThrough()` which has been piped into by a separate stream which was also `pipe`'d elsewhere.  

Maybe the bug is not in this library

**Comment by crossan007** [comment]
It seems like the `async read` in `peek-readable`'s (a dependency of `strtok3`) `StreamReader.js` library here is not detecting that the piped stream is actually readable until it ends.


Here's some sample code to demonstrate the effects:
```
import {default as FileType} from "file-type";
import * as fs from 'fs';
import internal, { PassThrough, Readable } from "stream";
import { default as Axios, AxiosRequestConfig } from "axios"

interface StreamFilterResult {
  filterName: string
  pass: boolean,
  data: any,
  timedOut: boolean
}

export interface StreamFilter  { 
  filterName: string,
  callback(stream: PassThrough) : Promise<StreamFilterResult>
}


const getFileType: StreamFilter= {
  filterName: "getFileType",
  callback: async (stream) => {
    const fileTypeP = FileType.fromStream(stream);
    /*
      // UNCOMMENT THIS to force the stream to end once it's readable; this forces peek-readable's StreamReader.read to actually consume data
      stream.on("readable",()=>{
      stream.end();
    });*/
    const fileType = await fileTypeP
    return {
      filterName: "getFileType",
      pass: true,
      data: {
        fileType: fileType
      },
      timedOut: false
    }
  }
}

async function process() {

  let realFileSaveStream = new PassThrough();
  
  console.log("fetching file from url")
  const response = await Axios({
    mehod:"get",
    url: "https://www.mouser.com/pdfDocs/WS2812B-2020_V10_EN_181106150240761.pdf",
    responseType: "stream"
  } as AxiosRequestConfig)
  
  console.log("fetched file from url")
  const axiosResponseStream = response.data as Readable

  axiosResponseStream.pipe(realFileSaveStream, {end: true});
  let resultPromises: Promise<StreamFilterResult>[] = [];

  let pt = new PassThrough();
  axiosResponseStream.pipe(pt, {end: true});

  // There could be other filters here; so just emulate an array for consistenty
  resultPromises.push(new Promise<StreamFilterResult>(async (resolve,reject) => {
    // resolve this promise if we don't get data
    const q = setTimeout(
        ()=>{ 
          pt.end();
          resolve({
            filterName: getFileType.filterName,
            pass: true,
            data: "Timed out waiting for " + getFileType.filterName,
            timedOut: true
          }); 
        }, 3000)
      const result = await getFileType.callback(pt)
      clearTimeout(q);
      resolve(result);
    }))

  const results = await Promise.all(resultPromises);

  console.log(results[0]);
}

process();
```

**Comment by Borewit** [comment]
Very much appreciate your detailed analysis @crossan007. need to find some time to get my head around this one...

**Comment by crossan007** [comment]
@Borewit  Thanks!  

It's entirely possible that I have an incorrect/incomplete understanding of NodeJS streams; I've read a little about back-pressure, and I'm not sure I fully grok how it relates to pipes and `PassThrough` streams in an asynchronous context.  That said; if I've done something silly, I welcome that feedback :-)

I should also note that commenting-out ` axiosResponseStream.pipe(realFileSaveStream, {end: true});` causes the `FileType.fromStream` call to return quickly (with similar results to the ` stream.on("readable",()=>{stream.end(); })` workaround)  since that makes the `PassThrough` stream consumed by `FileType` to not be "multiplexed"

Additionally the `{end: true}` parameter on the `pipe` calls seem to have no effect

**Comment by Borewit** [comment]
> Edit: This seems to only appear when the stream supplied to the fromStream method is a PassThrough() which has been piped into by a separate stream which was also pipe'd elsewhere.

Consuming a single stream twice is very tricky business. In principle you should have one stream producer and exactly one stream consumer. A stream is not infinite data lake, the producer will be slowed down to adapt to the consumer, back pressure.  I think you can have 2 consumers of a stream, as long as either of the consumers can wait for the other to consume the data, and that the slowest consumer will keep reading. If the consumer start to wait for each-other, for example to determine the file-type, you have created a dead-lock. If consumer A should determine the file-type and consumer B needs that file-type + the context, that is not going to fly. It probably works if the file-type can be determined from the first few bytes, but if you try that with a file-type which require further analysis, e.g. PDF, you run into the dead-lock siutation.

I am not much of genius myself, I naively tried that: #300.

**Comment by crossan007** [comment]
My attempt at multiplexing this stream is to pass it through a set of independent asynchronous "filters" first (before actually writing the stream to its target "save location").

Each of these filters is able to operate on the stream independently, and returns basically a "keep" or "trash" response (among a few other things).  As long as no filters indicate "trash," I pipe the stream to the storage.

Presently, each of these filters only needs to look at the first few bytes to determine keep/trash.

**Comment by Borewit** [comment]
> Presently, each of these filters only needs to look at the first few bytes to determine keep/trash.

Problem is that file-type does not necessary read the very first few bytes. I think the concept of validating the file within the stream is not very strong, depending on the file size, and what you exactly want to achieve.

Just an example, probably not your use case, but let's say you upload a DVD, and you can only figure out in the last few bytes that the DVD contains a virus (it is trash), it does not make sense to keep that entire thing in memory. By doing that you probably created a vulnerability rather solved one. Just write it to a temporary location, consider that DVD as quarantined until it is fully validated.

**Comment by Borewit** [comment]
[fileTypeStream(), in v16 this was stream()](https://github.com/sindresorhus/file-type#filetypestreamreadablestream-options), is probably the closest thing to work around your issue. But it comes at a price, it a has a limited sample size preventing the read to much at the cost of some file type determination.

**Comment by crossan007** [comment]
@Borewit  thanks for the tips.

I think we can close this issue
