### ISSUE TITLE
Babel transpilation error

### ISSUE THREAD

**Issue by Pyroarsonist** [sindresorhus/file-type#534]
Importing `fileTypeFromBuffer` using babel transpiler with Node `v16.13.1` throws an error, am I doing something wrong? (I also tried using dynamic import and give the same error)

Error message: `Instead change the require of index.js in $FILE_PATH to a dynamic import() which is available in all CommonJS modules`

file-type version: `17.1.1`

babel deps:
   ```
    "@babel/cli": "^7.14.8",
    "@babel/core": "^7.15.0",
    "@babel/eslint-parser": "^7.15.0",
    "@babel/eslint-plugin": "^7.14.5",
    "@babel/node": "^7.14.9",
    "@babel/plugin-transform-modules-commonjs": "^7.15.4",
    "@babel/preset-env": "^7.15.0",
```

babel.rc:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-modules-commonjs",
      {
        "allowTopLevelThis": true,
        "loose": true,
        "lazy": true
      }
    ]
  ]
}
```

file-type `v16.5.3` works without issues

**Comment by Borewit** [comment]
See #533
