### ISSUE TITLE
How to check mime type of url without downloading the file?

### ISSUE THREAD

**Issue by Br3ikros** [sindresorhus/file-type#540]
Hi. I'm sorry if this sounds dumb but I really struggle to understand documentations in general and I'm a newbie.

I have an URL. e.g.:    https://lh3.googleusercontent.com/jhguEP2guLV-HuWjKUhtbqB24AkIAv94uY2XMIdw-xRXxYg0TVFA1CWvZtQmW8pzrZBnDHMGSU656QA3wokLpTbq4OdXXvYVcRYf

and I want to use this library to check its mime-type, but without downloading the whole image because that takes time....

What should I do?

Also, why doesn't "require" work for the latest versions of this library? It still works for version 16.5.0 but then around after that it stops working.

**Comment by DanishSiraj** [comment]
Read the url as a stream that gives response very fast :thinking: 

try this
```
import {fileTypeFromStream,fileTypeFromBuffer} from 'file-type';
import axios from 'axios';

const url = 'https://lh3.googleusercontent.com/jhguEP2guLV-HuWjKUhtbqB24AkIAv94uY2XMIdw-xRXxYg0TVFA1CWvZtQmW8pzrZBnDHMGSU656QA3wokLpTbq4OdXXvYVcRYf';

const test = async () => {
const response = await axios({
  method: 'get',
  url,
  responseType: 'stream',
    maxContentLength: 1000,
});

//console.log(response.data)
const fileType = await fileTypeFromStream(response.data);
console.log(fileType);
};




test()


```
