### ISSUE TITLE
Unable to get file-type to run in browser (modules strtok3/core and token-types not found)

### ISSUE THREAD

**Issue by MiteshGandhi2893** [sindresorhus/file-type#541]
We are using 
Angular 11.2.9, 
Chrome Version 100.0.4896.127 (Official Build) (64-bit) ,
file-type version 17.1.1, 
webpack version 4.44.2.

we have used solution from [502](https://github.com/sindresorhus/file-type/issues/502#issuecomment-990255477) to solve node:buffer error to run the library in browser.
After doing above, we are getting below mentioned errors.
```
Error: ./node_modules/file-type/core.js
Module not found: Error: Can't resolve 'strtok3/core' in '/home/demo/node_modules/file-type'

Error: ./node_modules/file-type/core.js
Module not found: Error: Can't resolve 'token-types' in '/home/demo/node_modules/file-type'
```

Are there any instructions available for getting this package to work in angular version 11.2.9 ?

**Comment by sindresorhus** [comment]
You need to make sure you're using the latest Webpack version, that your project is ESM, and that you have configured Webpack correctly for ESM.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
