### ISSUE TITLE
Either make this package browser capable or declare it pure node

### ISSUE THREAD

**Issue by barbalex** [sindresorhus/file-type#542]
See:
- https://github.com/vitejs/vite/issues/7863#event-6496020819
- https://github.com/sindresorhus/file-type/issues/502 (solves part of the issue, but only for devs using webpack)
- https://github.com/sindresorhus/file-type/issues/541

**Comment by sindresorhus** [comment]
It should work fine in the browser if these conditions are met: https://github.com/sindresorhus/file-type/issues/541#issuecomment-1139446248

I have added a note to the readme.
