### ISSUE TITLE
Support for `txt`

### ISSUE THREAD

**Issue by countless-integers** [sindresorhus/file-type#55]
It'd be usefull to have support for `.txt` files (or am I missing something here).

**Comment by sindresorhus** [comment]
It's not as easy as you think, but should be possible.

http://stackoverflow.com/questions/567757/how-do-i-distinguish-between-binary-and-text-files

**Comment by countless-integers** [comment]
Yeah, it's more interesting than it looks :). As long as it has BOM chars then it's easy, but it gets interesting without them. Linux's `file` seems to work, I'll try to read through that code.

**Comment by GGG-KILLER** [comment]
I think that this [StackOverflow Answer](http://stackoverflow.com/a/567993/2671392) might be related to the subject as it shows the file.c code related to recognizing readable text or not:

```c
/* Make sure we are dealing with ascii text before looking for tokens */
for (i = 0; i < nbytes - 1; i++) {
   	if (!isascii(buf[i]) ||
   	    (iscntrl(buf[i]) && !isspace(buf[i]) &&
   	     buf[i] != '\b' && buf[i] != '\032' && buf[i] != '\033'
	    )
	)
	return 0;	/* not all ASCII */
}
```

and maybe use [Unicode Checking](http://stackoverflow.com/a/567771/2671392) for unicode text files?

**Comment by rushglen** [comment]
+1 would be useful if we could determine if a file was 'text/plain', 'text/html' etc from the binary

**Comment by fider** [comment]
Unfortunately it is not possible to **unambigiously** distinguish txt and binary file basing on it's binary content.
Plain text files doesn't contain any meta data, everything is handled by OS, so you can't be sure in case of uploaded file - such check is invalid.
Some kind of "fuzzy" detection can be done on level of specific OS, but in case of usage of this module (detection of uploaded file type) it is invalid.

I propose to close this issue.

**Comment by sindresorhus** [comment]
I agree with @fider.
