### ISSUE TITLE
Cannot find module 'node:stream' or its corresponding type declarations

### ISSUE THREAD

**Issue by dpopp07** [sindresorhus/file-type#550]
I've just updated the `file-type` dependency in a TS package I maintain from v7 to v17. I made the necessary code updates but I cannot build my code with TS - I get several errors, all coming from `file-type` or associated packages from within `node_modules`. Every error is the same: `Cannot find module 'node:stream' or its corresponding type declarations.` and it occurs in 5 places:
- `node_modules/file-type/core.d.ts:1:42`
- `node_modules/file-type/index.d.ts:1:42`
- `node_modules/peek-readable/lib/StreamReader.d.ts:2:26`
- `node_modules/strtok3/lib/core.d.ts:3:26`
- `node_modules/strtok3/lib/ReadStreamTokenizer.d.ts:3:26`

Any idea why I might seeing this? I'm not ruling out that it could be an issue in my environment but I'm not seeing any issue in my code, just in the dependencies.

I've tried with Node versions `14.17.5`, `16.16.0`, and `18.6.0`.
I've also tried with TypeScript versions `4.7.4` (latest) and `3.8.3` (what we normally use for compatibility).

I would appreciate any insight here!

Screenshot of all the errors:
<img width="1471" alt="Screen Shot 2022-07-26 at 3 26 41 PM" src="https://user-images.githubusercontent.com/9168931/181108939-a8e701ee-4964-4570-acc8-22097cfbc9fe.png">

**Comment by gochoe** [comment]
Same for me. it works fine @16.5.3

**Comment by Borewit** [comment]
From version file-type version 16 to 17, it changed from a CommonJS to ES-Module. To isolate the issue, you may want to try the latest 16.x first. Can you create a simple repo reproducing the issue @dpopp07?

**Comment by Borewit** [comment]
From version file-type version 16 to 17, it changed from a CommonJS to ES-Module. To isolate the issue, you may want to try the latest 16.x first. Can you create a simple repo reproducing the issue @dpopp07?

**Comment by dpopp07** [comment]
@Borewit thanks for the reply. Everything is working fine with 16.5.4, I ran into these issues when trying to use v17. I should be able to create a simple repo to reproduce, good idea. I'll try to do that soon

**Comment by dpopp07** [comment]
Okay @Borewit I created [a simple project to reproduce](https://github.com/dpopp07/file-type-issue-demo/tree/main).

While I was putting this together, I learned that installing `@types/node` actually resolves the issue. So there's a fairly easy workaround. I just want to see if this is supposed to be a necessary sibling dependency in order to use this package with TypeScript. It doesn't work "out of the box".

**Comment by Borewit** [comment]
Adding `@types/node` to Node.js TypeScript project is a common thing, as that kind of enables the types for the Node.js API. `@types/node` is defined in [peek-readable](https://github.com/Borewit/peek-readable) as a [development dependency](https://github.com/Borewit/peek-readable/blob/c6f445d14da483e1b83bfe0099600cdc24c7f2a6/package.json#L47) as well. I don't think there is a good way I can automatically let you inherit `@types/node` typings via the dependent modules,
