### ISSUE TITLE
The v16.5.4 tag is the same as v17.1.2

### ISSUE THREAD

**Issue by carlosperate** [sindresorhus/file-type#551]
- https://github.com/sindresorhus/file-type/compare/v16.5.4...v17.1.2
- https://github.com/sindresorhus/file-type/releases/tag/v16.5.4
- https://github.com/sindresorhus/file-type/releases/tag/v17.1.2

Just checking in case this wasn't done on purpose, as any breaking change from v17.x would also be applicable when upgrading from v16.5.3 to v16.5.4:
- https://github.com/sindresorhus/file-type/releases/tag/v17.0.0

In my case, I got a dependabot PR and noticed this while looking a the version diff, but I think most people would not really expect these kind of breaking changes going up one "patch release".

**Comment by Borewit** [comment]
I second that the delta between [v16.5.4...v17.1.4)](https://github.com/sindresorhus/file-type/compare/v16.5.4...v17.1.4) is suspiciously small @sindresorhus . Looks like [v16.5.4 tag](https://github.com/sindresorhus/file-type/releases/tag/v16.5.4) is done wrong.

The NPM release is fine, it includes the Matroska security fix with `&& mask !== 0`.

**Comment by Borewit** [comment]
Fixed the tag / release: [16.5.4](https://github.com/sindresorhus/file-type/releases/tag/v16.5.4), which now corresponds to [NPM file-type/v/16.5.4](https://www.npmjs.com/package/file-type/v/16.5.4).

Change:
Before: v16.5.4 tags commit 99cb0198bf3e55cfeda0c407607dddbab8875d91
Now: v16.5.4 tags commit b5fe3b9596711a42c0141d97a11e4f0fa5fcc7a0

**Comment by carlosperate** [comment]
Thanks @Borewit!
Does that mean that the release in NPM was correctly set to commit b5fe3b9596711a42c0141d97a11e4f0fa5fcc7a0 and the issue was just in the git tag here?

**Comment by Borewit** [comment]
That is what indeed what I believe what the issue was @carlosperate.
