### ISSUE TITLE
Would it be better to return the file extension with a period?

### ISSUE THREAD

**Issue by 7anshuai** [sindresorhus/file-type#555]
From Wikipedia:
> A **filename extension**, **file name extension** or **file extension** is a suffix to the [name](https://en.wikipedia.org/wiki/Filename) of a [computer file](https://en.wikipedia.org/wiki/Computer_file) (e.g., `.txt`, `.docx`, `.md`).

When the `ext` without a period(`.`), i need write code like this:

```javascript
import path from 'path';
import {fileTypeFromFile} from 'file-type';

const filetype =  await fileTypeFromFile('Unicorn.png'));
// {ext: 'png', mime: 'image/png'}

const pathname = path.format({ dir: '/path/to/somewhere', name: 'Unicorn', ext: filetype?.ext ? '.' + filetype?.txt : '' });
// /path/to/somewhere/Unicorn.png
```

With a period(`.`):
```javascript
const filetype =  await fileTypeFromFile('Unicorn.png'));
// {ext: '.png', mime: 'image/png'}

const pathname = path.format({ dir: '/path/to/somewhere', name: 'Unicorn', ext: filetype?.ext });
// /path/to/somewhere/Unicorn.png
```

If the `ext` has a period, it's convenient to use it.

**Comment by sindresorhus** [comment]
The extension *is* `png`. The dot is just the separator. Same as the filename is not `/Unicorn.png`, since `/` is the path separator.

https://github.com/nodejs/node/issues/44343
