### ISSUE TITLE
CommonJS and ESM - support both

### ISSUE THREAD

**Issue by ollydixon** [sindresorhus/file-type#556]
I see the issue logged here https://github.com/sindresorhus/file-type/issues/535

We updated and come across the issue, was very annoying to debug.

But like 99.9% of Typescript libraries, why not support both? So NPM install won't matter :-)

**Comment by sindresorhus** [comment]
There are no plans to bring back CommonJS support. TypeScript has full ESM support now.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by ollydixon** [comment]
I understand, but NPM packages won't be bleeding edge for many years.

@sindresorhus a big majority of projects are still on CommonJS because many essential packages won't upgrade on NPM.

Adding duel support is fairly standard at the moment.

Out of 100s of packages we use this one is the only recent one that complains, isn't it a bit silly to ignore us?

**Comment by sindresorhus** [comment]
> a big majority of projects are still on CommonJS because many essential packages won't upgrade on NPM.

You can use CommonJS from ESM, so I don't see why that's a problem.

> Adding duel support is fairly standard at the moment.

I don't think it is, but neither of us have any stats of this.

Also read please read: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849#gistcomment-3850849

Dual packages come with a lot of problems too.

> Out of 100s of packages we use this one is the only recent one that complains, isn't it a bit silly to ignore us?

There are two ways forward if you don't intend to move to ESM:
1. Use version 16 of this package.
2. Use [await import(…)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports), which can import ESM from CommonJS.

**Comment by ollydixon** [comment]
I'll keep using 16. I can see from the issue that many people feel the same way as me.

**Comment by sindresorhus** [comment]
I'm going to lock this issue as I cannot spend lots of time discussing this any time someone has a problem with our choice to use ESM. I hope you understand.
