### ISSUE TITLE
image/apng is not an actual MIME type

### ISSUE THREAD

**Issue by didinele** [sindresorhus/file-type#559]
See: https://www.iana.org/assignments/media-types/media-types.xhtml

This is problematic, as we use this package to infer the mime type of a file the user passes in (in the context of a library), which we then send upstream to a REST API, which deliberately throws a 4xx error in response.

It doesn't seem fitting to me to yield unofficial MIME types, but if it won't be removed, I suppose we'll simply manually map `image/apng` to `image/png`.

**Comment by Borewit** [comment]
It had a quick look and it seems that the intention was to register `image/apng`

As it is an extension to the PNG format `image/png` is reasonable.

`image/vnd.mozilla.apng` seems to be registered. 

Reverences: 
- #215
- [Bugzilla: Add image/apng MIME type so it can be used with `picture` type switching.](https://bugzilla.mozilla.org/show_bug.cgi?id=1160200)
- [Registration of `image/vnd.mozilla.apng`](https://www.iana.org/assignments/media-types/image/vnd.mozilla.apng)](https://www.iana.org/assignments/media-types/image/vnd.mozilla.apng)
