### ISSUE TITLE
.aac audio file incorrectly detected as video/mp4

### ISSUE THREAD

**Issue by elr0berto** [sindresorhus/file-type#566]
[audio.aac.zip](https://github.com/sindresorhus/file-type/files/10323169/audio.aac.zip)

Attached example aac audio file.

**Comment by Borewit** [comment]
The file you attached is not `.acc` file, it is an `.m4a` file AAC encoded audio stream.
An `.aac` file is using [ADTS](https://wiki.multimedia.cx/index.php/ADTS)

In line with that, when I try to open this file with Foobar2000:

> Unable to open item for playback (This is an M4A file, please rename it in order to play it):

For the reason this file is detected as `video/mp4` and not as `video/m4a`, see #343

**Comment by elr0berto** [comment]
Ok, i stopped using file-type to detect if a file is audio. Instead using ffmpeg to see if the file can be converted to mp3 or not.

**Comment by Borewit** [comment]
> Ok, i stopped using file-type to detect if a file is audio. Instead using ffmpeg to see if the file can be converted to mp3 or not.

Alternatively you could consider using [music-metadata](https://github.com/Borewit/music-metadata), which dives a bit deeper in audio tracks in comparison to [file-type](https://github.com/sindresorhus/file-type).
