### ISSUE TITLE
Dependencies are not found 

### ISSUE THREAD

**Issue by Ryan044** [sindresorhus/file-type#574]
dependencies not found... 

These dependencies were not found:

* read-chunk in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/orders/OrderShipmentInfoPdf.vue?vue&type=script&lang=js&
* strtok3 in ./node_modules/file-type/index.js

**Comment by sindresorhus** [comment]
This is not a problem with this package. Looks like a problem with `cache-loader`.
