### ISSUE TITLE
Cannot import the module

### ISSUE THREAD

**Issue by zlayine** [sindresorhus/file-type#577]
Hello, 
I'm trying to use this library and when i try to import it i get this issue

<img width="609" alt="image" src="https://user-images.githubusercontent.com/58786497/216589240-632e4de8-bc2a-4be8-877c-8c92cc2ec5bd.png">

here is the code i use
```
import { fileTypeFromFile } from 'file-type';

export default async function nameTest(file) {
    const type = await fileTypeFromFile(file);
    console.log(type);
}
```

Does anyone know what causing this issue

**Comment by sindresorhus** [comment]
That method is only available on Node.js. You must ensure your bundler has the correct config.

**Comment by cloudymeatball** [comment]
In your tsconfig, you need
```
{
    "module: "node16",
    "moduleResolution": "node16"
}
```
or other node settings as specified [on the typescript documentation](https://www.typescriptlang.org/tsconfig#moduleResolution)
