### ISSUE TITLE
Merge is-svg into file-type

### ISSUE THREAD

**Issue by nodesocket** [sindresorhus/file-type#58]
With the recent announcement of [multiple code execution vulnerabilities](https://imagetragick.com/) in ImageMagick, people should be using this package instead of blindly looking at the mime-type.

Any reason why `svg` detection is a [seperate package](https://github.com/sindresorhus/is-svg) though? Would be great to have a single package and API for this?

**Comment by sindresorhus** [comment]
It's in the readme:

> SVG isn't included as it requires the whole file to be read, but you can get it here.

All the other detections can be done by reading the initial bytes in a file, but the SVG check requires reading the whole file. I just didn't want to ruin the purity with one check, but I'm open to consider adding an additional method that supports more formats, but requires reading the whole file.

**Comment by raphaelokon** [comment]
I think there is a potential use-case here … for example checking for non-binary text files like `.svg, .html, .css, .js …` … tho this likely requires parsing those files or statically analyzing them (like is-svg does).
