### ISSUE TITLE
Next.js, Typescript seems not work with conditional exports

### ISSUE THREAD

**Issue by luukvankooten** [sindresorhus/file-type#585]
I'm using this in my next js application but if I use the following line:

```ts
import { fileTypeFromBlob } from 'file-type';
```

typescript is giving the following error:

``` 
3:10  error   '"file-type"' has no exported member named 'fileTypeFromBlob'. Did you mean 'fileTypeFromFile'? ​typescript(2724)
```

And if use the following import:

```ts
import { fileTypeFromBlob } from 'file-type/browser';
```
Then typescript is compleetly happy

but then i'm getting a error from next.js in my browser

```
Module not found: Package path ./browser is not exported from package /node_modules/file-type (see exports field in /node_modules/file-type/package.json)
```

Anybody an idea how to fix this?

**Comment by yonghui666** [comment]
> 我在我的下一个 js 应用程序中使用它，但是如果我使用以下行：
> 
> ```ts
> import { fileTypeFromBlob } from 'file-type';
> ```
> 
> 打字稿给出以下错误：
> 
> ```
> 3:10  error   '"file-type"' has no exported member named 'fileTypeFromBlob'. Did you mean 'fileTypeFromFile'? ​typescript(2724)
> ```
> 
> 如果使用以下导入：
> 
> ```ts
> import { fileTypeFromBlob } from 'file-type/browser';
> ```
> 
> 然后打字稿就很开心了
> 
> 但后来我在浏览器中收到来自 next.js 的错误
> 
> ```
> Module not found: Package path ./browser is not exported from package /node_modules/file-type (see exports field in /node_modules/file-type/package.json)
> ```
> 
> 有人知道如何解决这个问题吗？

请问你解决了吗

**Comment by jstdk** [comment]
I think this plugin does not support Typescript, I just raised: https://github.com/sindresorhus/file-type/issues/600

**Comment by sindresorhus** [comment]
This is a problem with Next.js or your TypeScript config, not this package.


https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

> Add ["module": "node16", "moduleResolution": "node16"](https://www.typescriptlang.org/tsconfig#module) to your tsconfig.json. ([Example](https://github.com/sindresorhus/tsconfig/blob/main/tsconfig.json))
