### ISSUE TITLE
Not all mp4 are recognized

### ISSUE THREAD

**Issue by sam1111** [sindresorhus/file-type#60]
Hi,

I am attaching an mp4 file which is not getting recognized correctly. the mimetype returned by module comes as undefined.
[videoplayback.mp4.zip](https://github.com/sindresorhus/file-type/files/398775/videoplayback.mp4.zip)

**Comment by t1st3** [comment]
Getting some info about the file with [mediainfo](https://mediaarea.net/en/MediaInfo), I get this kid of output:
```
General
Complete name                            : videoplayback.mp4
Format                                   : dash
Codec ID                                 : dash
File size                                : 4.57 MiB
```

I don't know much about `mp4` files, but it appears that `dash` maybe something else but related to `mp4`. Wikipedia has 2 separate pages about `mp4` and `dash`:
* [mp4](https://en.wikipedia.org/wiki/MPEG-4_Part_14)
* [dash](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP)

Seems that `dash` is a different codec from traditional `mp4` while keeping the same extension.

**Comment by mifi** [comment]
I have added DASH as mp4 (as `file` identifies it).

65f0017d8a418dd217e8eec9250c2d9f04578f56

However there are still many other mp4 variants not yet detected by file-type, see #99
