### ISSUE TITLE
build fix

### ISSUE THREAD

**Issue by Munkhuumn** [sindresorhus/file-type#608]
require() of ES Module ~\\node_modules\\file-type\\index.js from ~\\graphql-service\\dist\\utils\\files\\fileType.js not supported.\nInstead change the require of index.js in ~\\dist\\utils\\files\\fileType.js to a dynamic import() which is available in all CommonJS modules.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
