### ISSUE TITLE
fileTypeFromBase64

### ISSUE THREAD

**Issue by phaux** [sindresorhus/file-type#610]
We need to know the mime type before we can parse it using fetch data url.

```js
const type = fileTypeFromBase64(base64string) // add this

const blob = await fetch(`data:${type.mime};base64,${base64string}`)
    .then(resp => resp.blob())
```

**Comment by sindresorhus** [comment]
You can easily convert Base64 to a Buffer. I don't think this is common of enough need to support built-in.

```js
Buffer.from(b64string, 'base64');
```

**Comment by phaux** [comment]
But `Buffer.from` is node only :/

**Comment by sindresorhus** [comment]
https://stackoverflow.com/questions/21797299/convert-base64-string-to-arraybuffer

**Comment by phaux** [comment]
Yeah I know, but the fetch data url method is async and better on front-end where you want consistent 60fps. Just sayin
