### ISSUE TITLE
Got this build error: Could not resolve "node:buffer"

### ISSUE THREAD

**Issue by dinghaoz** [sindresorhus/file-type#614]
> ✘ [ERROR] Could not resolve "node:buffer"
> 
>     node_modules/file-type/core.js:1:21:
>       1 │ import {Buffer} from 'node:buffer';
>         ╵                      ~~~~~~~~~~~~~
> 
>   The package "node:buffer" wasn't found on the file system but is built into node. Are you trying
>   to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

I am using node.js

**Comment by sindresorhus** [comment]
This is a problem with your bundler config.
