### ISSUE TITLE
When I download `file-type` into the webpack 3 project, running the error message requires installation  `strtok3`

### ISSUE THREAD

**Issue by cMing1997** [sindresorhus/file-type#616]
### The BUG behavior
```
 When I download `file-type` into the webpack 3 project, running the error message requires installation  `strtok3`
but, It is possible to downgrade the version to 10
```

### Downloaded version：
 ```
    18/17
``` 
### Runtime Environment
```
webpack：^3.6.0
```
###  Error Info
```
This dependency was not found:

* strtok3 in ./node_modules/file-type/index.js

To install it, you can run: npm install --save strtok3
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\DumpStack.log.tmp'
```

### Expect
```
If you are sure that the latest versions are required for the webpack version, it is expected to be explained in readme
```

**Comment by sindresorhus** [comment]
This is something you need to bring up no the Webpack issue tracker.

**Comment by cMing1997** [comment]
> This is something you need to bring up no the Webpack issue tracker.
But the `strtok3`  it's already inside `node_modules `，The error will still be reported, no packet loss occurred
When I run 'npm install-save Strtok 3' , an error is still reported, so I raise the issue

**Comment by cMing1997** [comment]
> This is something you need to bring up no the Webpack issue tracker.

But the strtok3 it's already inside node_modules ，The error will still be reported, no packet loss occurred
When I run 'npm install-save Strtok 3' , an error is still reported, so I raise the issue
