### ISSUE TITLE
Uncaught SyntaxError: The requested module does not provide an export named 'fileTypeFromBlob' in browser

### ISSUE THREAD

**Issue by squivix** [sindresorhus/file-type#619]
I'm using this library in the broswer with Vite and Vue, and there seems to be certain imports not included for the browser.

When I try to import:

```ts
import {fileTypeFromBlob} from "file-type";
```

I get:
```
Uncaught SyntaxError: The requested module does not provide an export named 'fileTypeFromBlob' in browser
```

It seems the export was removed from `browser.js` in 1c75cfb. I don't know why.

**Comment by sindresorhus** [comment]
It was not removed. It was simply changed to be re-exported from `core.js`. The problem here is your Vite config, not this package.
