### ISSUE TITLE
mimetype of certain PNGs mislabeled as "text/plan"

### ISSUE THREAD

**Issue by jvnlwn** [sindresorhus/file-type#621]
In a recent release of filestack-js (v 3.29.0) https://github.com/filestack/filestack-js/commit/ec8a95001647bd1f5fc2d2a68f55da26b541e0b5, a bug was introduced when [upgrading](https://github.com/filestack/filestack-js/compare/v3.28.0...v3.29.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R50) their file-type dependency.

When uploading _certain_ PNGs via the filestack-js API, a PNG's mimetype might be mislabeled as "text/plan" rather than "image/png".

Here is a PNG which produced the error:

![winding-path-banner](https://github.com/sindresorhus/file-type/assets/5227102/32e97896-f530-4f8a-b635-cc702db6910e)

I cannot currently point to a change in file-type responsible, or provide a reproduction with file-type as I'm quite unfamiliar with this codebase.

The bug cannot be reproduced with filestack-js v 3.28.0, hence my suspicion leads me to file-type.

**Comment by sindresorhus** [comment]
I tried adding the image to our tests and it's correctly detected as PNG.

**Comment by jvnlwn** [comment]
@sindresorhus thank you for checking on that. It seems likely then that the bug lies with filestack-js. Will continue investigating with them, thanks!

**Comment by jvnlwn** [comment]
@sindresorhus there could still be an issue with file-type which maybe you can help determine.

Once again, looking at the changes in filestack-js, especially take note of [these changes](https://github.com/filestack/filestack-js/compare/v3.28.0...v3.29.0#diff-297ac89b35f351e5588ae70ac56afe74ea63f974d33a45e4de1d2497f02651ddR21-R110).

In my testing with filestack-js, using the file in this issue's description, I hit the exception caught from file-type's `fromBuffer` method.

In the console, I see the warning:
> An exception occurred while processing the buffer: Buffer is not defined

The "Buffer is not defined" error could only be coming from file-type, no?

**Comment by midmarch** [comment]
file-type is primary written for Node.js and has a dependency on node:Buffer.. At this time it required you properly shim the Buffer requirement in a non Node.js environment.

**Comment by Borewit** [comment]
file-type is primary written for Node.js and has a dependency on node:Buffer.. At this time it required you properly shim the Buffer requirement in a non Node.js environment.

**Comment by jvnlwn** [comment]
Thanks @Borewit, that makes sense. Guessing the behavior is expected in filestack-js – maybe they intend for the library to be used in either a Web or Node.js env.
