### ISSUE TITLE
FileType returns undefined on pdf file

### ISSUE THREAD

**Issue by Datodia** [sindresorhus/file-type#622]

**Comment by sindresorhus** [comment]
You will need to share a file that reproduces the issue (preferably as small as possible).

**Comment by Datodia** [comment]
const fileTypeReader = await import('file-type')
const fileInfo = await fileTypeReader.fileTypeFromBuffer(content)

content is buffer

console.log(fileInfo.mime) //expected application/octet-stream //actual is undefined

**Comment by theabhinavdas** [comment]
@sindresorhus came across this issue today, happens with this file:
[1000503577.pdf](https://github.com/sindresorhus/file-type/files/15457696/1000503577.pdf)

**Comment by Borewit** [comment]
> @sindresorhus came across this issue today, happens with this file: [1000503577.pdf](https://github.com/sindresorhus/file-type/files/15457696/1000503577.pdf)

This file is not recognized because the file is prefixed with the following lines:
```
--fa92d6cf-98aa-4886-8eeb-667d510d131a
Content-Disposition: form-data; name=file; filename="test document - doc upload.pdf"; filename*=utf-8''test%20document%20-%20doc%20upload.pdf

````
I suspect those lines are not part of the original PDF, but are added during the upload process.
