### ISSUE TITLE
Detect NEF format, the result is image/tiff

### ISSUE THREAD

**Issue by wuxiashuangji** [sindresorhus/file-type#624]
NIKON D610, AF-S Nikkor 24-120mm f/4G ED VR

arraybuffer:

0x4D4D002A 00000008 001C00FE 00040000

**Comment by wuxiashuangji** [comment]
arrayuffer

**Comment by wuxiashuangji** [comment]
NIKON D850, AF-S Nikkor 105mm f/1.4E ED

arraybuffer:

0x49492A 0008000000 1C00FE00 04000100

**Comment by wuxiashuangji** [comment]
NIKON D3, AF-S Zoom-Nikkor 14-24mm f/2.8G ED

arraybuffer:

0x49492A00 08000000 B00FE000 4000100

**Comment by wuxiashuangji** [comment]
@mceachen

**Comment by mceachen** [comment]
I gave up using this library for mimetype detection of raw image file formats--there are so many variants that getting them all correct is close to impossible. I'm using [exiftool-vendored](https://github.com/photostructure/exiftool-vendored.js) now.

**Comment by Borewit** [comment]
If someone could give PR #670 a try, that would be great.

```shell
npm install https://github.com/sindresorhus/file-type.git#improve-nef-detection
```

To understand how Nikon identifies the _Nikon Electronic Format_ (NEF), and to test the implementation, providing sample pictures are appreciated.

> 0x49492A00 08000000 B00FE000 4000100

Please note that this signature is invalid, seems to have 1 byte to many.
