### ISSUE TITLE
The requested module '/node_modules/.vite/deps/file-type.js?v=74b3d8f6' does not provide an export named 'fileTypeFromBlob'

### ISSUE THREAD

**Issue by SheldonWBM** [sindresorhus/file-type#625]
Issue:
From the browser console:
```
The requested module '/node_modules/.vite/deps/file-type.js?v=74b3d8f6' does not provide an export named 'fileTypeFromBlob'
```
Environment:
Vite: 5
React: 18
Yarn: 4 with PnP modules

This issue is similar to issue #619  where the solution is vague. 
Is the "re-export" method compatible with Plug n' Play modules?
Is the potential issue with the `vite.config` the way modules are optimized (i.e. `optimizeDeps`)?
Is there a working example with Vite and Yarn PnP?

**Comment by sindresorhus** [comment]
This package has the correct config. The problem is with one of your tools and you should ask on their support channels instead.

**Comment by LancerComet** [comment]
> This package has the correct config. The problem is with one of your tools and you should ask on their support channels instead.

@sindresorhus 

![image](https://github.com/sindresorhus/file-type/assets/10321350/8e586a99-0ba3-4848-be31-ca8a0623d695)
![image](https://github.com/sindresorhus/file-type/assets/10321350/2738a6e9-01c3-4551-a156-8b8094f7b59d)
