### ISSUE TITLE
Add support for .eml aka message/rfc822

### ISSUE THREAD

**Issue by davidpanic** [sindresorhus/file-type#626]
When trying to recognize .eml files `undefined` is returned instead of `{ "ext": "eml", "mime": "message/rfc822" }` which obviously means the format is not recognized. running the same file through the linux `file` utility returns `RFC 822 mail, ASCII text, with CRLF line terminators`.

[Here](https://github.com/file/file/blob/adcb31603724d75e6e2b3cc0dd5d26d39821c168/magic/Magdir/mail.news#L41) is how the file utility recognises the files.

Since there's many more magic file definitions in the Magdir, it might be a good idea to support those and expand the list of supported types to a way bigger set than currently supported.

**Comment by Borewit** [comment]
This package is for detecting binary-based, `.eml`, aka message/rfc822,  is a text based format.
