### ISSUE TITLE
Add support for ES module "require" syntax

### ISSUE THREAD

**Issue by JRiggles** [sindresorhus/file-type#634]
When trying to include `file-types` using `require` syntax
```
const fileType = require('file-type');
```
 it fails with the following error:
```
ReferenceError: require is not defined in ES module scope, you can use import instead
```
I'm working on an existing codebase that uses `require`, so I can't easily work with
```
import { fileTypeFromFile } from 'file-type';
```
Any help / advice is welcome!

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by JRiggles** [comment]
Heard, thanks Sindre! I'll see what I can figure out.
