### ISSUE TITLE
19.1.0 does not export `fileTypeFromTokenizer`

### ISSUE THREAD

**Issue by matt-kunze-nutrien** [sindresorhus/file-type#637]
This works with the prior `19.0.0` release and is still on the documentation page, so I'm guessing it's just an oversight.

Seems like this was introduced here: https://github.com/sindresorhus/file-type/commit/b815b5e173dd9f521311615eb33e955181030ca9#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L14

removing the passthrough exports from `core.js` omits that function (and potentially others) from the bundle. The type declarations still export it however

**Comment by sindresorhus** [comment]
// @Borewit
