### ISSUE TITLE
Automate generation of the release notes

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#642]
@sindresorhus, if you are interested, I can automate the generation of the release notes as a draft using [release-drafter](https://github.com/release-drafter/release-drafter).

It essentially collects all changes based on the PR, since the last release. It generates a draft release, only visible to contributors, which you can use a starting point to, or use as is, to write release notes.

Using labels, assigned to PR's, you can categorize pull requests, or ignore pull requests. 

Result of the release notes should be something like:

> ## Changes
> 
> ## 🎨 Improvements
> 
> - Add support for ID3v2.3 / ID3v2.4 GRP1 (iTunes) tag @scottgarner (#2054)
> 
> ## 🐛 Bug Fixes
> 
> - Fix ID3v2.3 \& ID3v2.4 `USLT` mapping to `common.lyrics` @Borewit (#2050)
> 
> ## NPM release
> NPM release: [music-metadata@8.3.0](https://www.npmjs.com/package/music-metadata/v/8.3.0)

I cannot demo this on a PR, as the configuration of the needs to be on the default branch.
Enabling the release notes is non-intrusive, there is nothing it will take over, there is nothing what prevents you to ignore draft, and release your own way.

**Comment by sindresorhus** [comment]
I already automate it with [`np`](https://github.com/sindresorhus/np), and I prefer that workflow.

**Comment by Borewit** [comment]
> I already automate it with [`np`](https://github.com/sindresorhus/np), and I prefer that workflow.

I am not surprised
