### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED when file-type used in nest.js

### ISSUE THREAD

**Issue by robertok-weiji** [sindresorhus/file-type#661]
Hi,

I'm using file-type in nest.js and I've this error, using the last 19.4.1 version.

```
nest start
node:internal/modules/cjs/loader:597
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in D:\dev\olhos\nest-test\node_modules\file-type\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:590:36)
    at Module._findPath (node:internal/modules/cjs/loader:667:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\dev\olhos\nest-test\src\app.controller.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

To simply reproduce the problem:

```
npm i -g @nestjs/cli
nest new nest-test
cd nest-test
npm i file-type
```

Edit the sample controller, scaffolded from nest.js:

```
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import { fileTypeFromFile } from 'file-type';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  async getHello(): Promise<string> {
    return (await fileTypeFromFile('Unicorn.png')).mime;
  }
}
```

`nest start`

Any idea?
Thanks

**Comment by sindresorhus** [comment]
You need to open an issue on Nest.js instead. This package is configured correctly. They probably don't properly support the `exports` field in package.json.

**Comment by RobertBeilich** [comment]
Coincidently had the same problem the same day, just a couple hours earlier :D Following up here to share what I've found:

The problem lies on neither side. It's Typescript, which compiles the dynamic import down to a `require`, which in turn obviously does not work.
Here are some options to circumvent it: https://github.com/TypeStrong/ts-node/discussions/1290

If you choose Option 1 (or Option 2 respectively), you need to declare the complete path to this module, as it (at least to my understanding) does not define a default properly.

@sindresorhus I'm not sure about the implications, so maybe you can evaluate it. If you add `default` entries for the exports, you can properly import the module with the given method above, without the need for the complete path. Does that break something else in a different setup, or can you easily add that?

```diff
diff --git a/package.json b/package.json
index 08f1ca3..ef6f98f 100644
--- a/package.json
+++ b/package.json
@@ -15,16 +15,19 @@
 		".": {
 			"node": {
 				"types": "./index.d.ts",
-				"import": "./index.js"
+				"import": "./index.js",
+				"default": "./index.js"
 			},
 			"default": {
 				"types": "./core.d.ts",
-				"import": "./core.js"
+				"import": "./core.js",
+				"default": "./core.js"
 			}
 		},
 		"./core": {
 			"types": "./core.d.ts",
-			"import": "./core.js"
+			"import": "./core.js",
+			"default": "./core.js"
 		}
 	},
 	"sideEffects": false,
```

**Comment by Borewit** [comment]
Our formal recommendation is to switch your module to ESM.

Maybe redundant to the solutions already provided [here](https://github.com/TypeStrong/ts-node/discussions/1290), this is a workaround which worked for me:

```ts
import * as path from 'path';

/**
 * Import 'file-type' ES-Module in CommonJS Node.js module
 */
(async () => {
  const { fileTypeFromFile } = await (eval('import("file-type")') as Promise<typeof import('file-type')>);

  const type = await fileTypeFromFile(path.join('..', 'fixture', 'fixture.gif'));
  console.log(type);
})();
```
Which is part of full working demo, using `file-type` 19.4.1, [can be found here](https://github.com/Borewit/file-type-example/blob/f56b36b1648819a847fec59ebb16736742e87ea8/ts-commonjs/index.ts#L1-L11)

**Comment by RobertBeilich** [comment]
Which is fine in theory, but does not work in the context of a nest application, as nest (sadly) explicitly is not switching away from commonjs. And obviously, depending on the size of your project, this might not be feasible or even possible, regardless

Your solution works in a similar fashion as the ones provided in the ts-node discussion, by skipping the transformation of the import to require, with the difference of using eval, which always is a red flag, even if you hardcode it.

I would rather use one of the provided solutions and have `file-type` properly define its exports, which it isn't according to the [guidelines](https://nodejs.org/api/packages.html#conditional-exports):

> When using environment branches, always include a "default" condition where possible. Providing a "default" condition ensures that any unknown JS environments are able to use this universal implementation, which helps avoid these JS environments from having to pretend to be existing environments in order to support packages with conditional exports. For this reason, using "node" and "default" condition branches is usually preferable to using "node" and "browser" condition branches.


PS: your typing can be simplified
```diff
-  const { fileTypeFromFile } = await (eval('import("file-type")') as Promise<typeof import('file-type')>);
+  const { fileTypeFromFile } = await eval('import("file-type")') as typeof import('file-type');
```

**Comment by Borewit** [comment]
> I would rather use one of the provided solutions and have file-type properly define its exports, which it isn't according to the [guidelines](https://nodejs.org/api/packages.html#conditional-exports):
>
>> When using environment branches, always include a "default" condition where possible. Providing a "default" condition ensures that any unknown JS environments are able to use this universal implementation, which helps avoid these JS environments from having to pretend to be existing environments in order to support packages with conditional exports. For this reason, using "node" and "default" condition branches is usually preferable to using "node" and "browser" condition branches.

That is exactly what we have done (line #20):

https://github.com/sindresorhus/file-type/blob/988bf4bc9f9bc98e8f3360da4dfa36e5caa455b3/package.json#L16-L23

The change you propose adding more `default` conditions is **not** at environment branches level.

**Comment by Borewit** [comment]
> PS: your typing can be simplified
>
> -  const { fileTypeFromFile } = await (eval('import("file-type")') as Promise<typeof import('file-type')>);
> +  const { fileTypeFromFile } = await eval('import("file-type")') as typeof import('file-type');

✅ 👍🏻

**Comment by Borewit** [comment]
> To my understanding this applies transitively, so you need the default in the nesting, as well.

Not to my understanding, in none of the examples provided by the [guidelines](https://nodejs.org/api/packages.html#conditional-exports) this is done.

A `require` (CommonJS) entry point is not present, so not be resolvable.

**Comment by RobertBeilich** [comment]
It's not done because in all of the examples there is a top level default and in none of them the default is nested itself. Which on the other hand you have done and should therefore provide a default in the default by applying the given rules transitively or strictly adhere to the examples in the guideline and not define a nested default.

It's going down the tree and if it does not find something it goes up and then down again if another entry matches, but in the end it needs to find a path that leads to a file, which does not happen for default, as the only options there are import and type. And with it's options exhausted it fails.

Partially correct. A require is not present, so it should not be resolvable that way explicitly, but you should have a default entrypoint, so
> that any unknown JS environments are able to use this universal implementation, which helps avoid these JS environments from having to pretend to be existing environments in order to support packages with conditional exports

And this default entry point will get hit by the commonjs resolver if present

But we are going in circles here. Either you believe me that the default is not reached (and hence noz configured) properly (which is proven by the commonjs resolver failing to hit it) or you don't, I can't force you 🤷

**Comment by Borewit** [comment]
Example how you can use **file-type** in [NestJS](https://nestjs.com/):

```ts
import { Injectable } from '@nestjs/common';
import {loadEsm} from "load-esm";

type FileTypeModule =  typeof import('file-type');

// Helper function, to convert Base64 String to Uint8Array
function base64ToUint8ArrayModern(base64: string): Uint8Array {
  return new Uint8Array([...atob(base64)].map(char => char.charCodeAt(0)));
}

@Injectable()
export class AppService {

  private fileType: FileTypeModule;


  async getFileType(): Promise<string> {

    const fileType = await loadEsm<FileTypeModule>('file-type');

    // Base64 encoded PDF file content
    const pdfDataBase64 = 'JVBERi0xLjQKMSAwIG9iago8PC9UeXBlIC9DYXRhbG9nCi9QYWdlcyAyIDAgUgo+PgplbmRvYmoKMiAwIG9iago8PC9UeXBlIC9QYWdlcwovS2lkcyBbMyAwIFJdCi9Db3VudCAxCj4+CmVuZG9iagozIDAgb2JqCjw8L1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovTWVkaWFCb3ggWzAgMCA1OTUgODQyXQovQ29udGVudHMgNSAwIFIKL1Jlc291cmNlcyA8PC9Qcm9jU2V0IFsvUERGIC9UZXh0XQovRm9udCA8PC9GMSA0IDAgUj4+Cj4+Cj4+CmVuZG9iago0IDAgb2JqCjw8L1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1R5cGUxCi9OYW1lIC9GMQovQmFzZUZvbnQgL0hlbHZldGljYQovRW5jb2RpbmcgL01hY1JvbWFuRW5jb2RpbmcKPj4KZW5kb2JqCjUgMCBvYmoKPDwvTGVuZ3RoIDUzCj4+CnN0cmVhbQpCVAovRjEgMjAgVGYKMjIwIDQwMCBUZAooRHVtbXkgUERGKSBUagpFVAplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA2IAowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMDA1NyAwMDAwMCBuIAowMDAwMDAwMTEzIDAwMDAwIG4gCjAwMDAwMDAyNTcgMDAwMDAgbiAKMDAwMDAwMDM2NCAwMDAwMCBuIAp0cmFpbGVyCjw8L1NpemUgNgovUm9vdCAxIDAgUgo+PgpzdGFydHhyZWYKNDU0CiUlRU9GCg==';

    const detection = await fileType.fileTypeFromBuffer(base64ToUint8ArrayModern(pdfDataBase64));

    return `Hello file-type detection! ${JSON.stringify(detection)}`;
  }
}
````
