### ISSUE TITLE
fileTypeFromFile cannot be imported

### ISSUE THREAD

**Issue by BalazsManus** [sindresorhus/file-type#662]
![image](https://github.com/user-attachments/assets/0564c415-aea6-47c4-92dc-5f86da3ef552)
![image](https://github.com/user-attachments/assets/f59779b1-4393-4053-b5a8-dd74111c5da3)
Node version: v22.3.0
NPM version: 10.8.1

**Comment by sindresorhus** [comment]
From the readme:

> **This package is an ESM package. Your project needs to be ESM too. [Read more](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).**
