### ISSUE TITLE
MKV detected as WebM

### ISSUE THREAD

**Issue by mifi** [sindresorhus/file-type#67]
It seems that the check in this library is too simple, because the strings "matroska" and "webm" are not always in a fixed position.

libmagic (used by the unix "file" utility) detects it correctly. Looking at its source, it does a search for the string "webm" and "matroska" preceded by \x42\x48 and a wildcard byte, in the first 4096 bytes of the file.

See source: https://github.com/threatstack/libmagic/blob/master/magic/Magdir/matroska

This would however require more complex checking logic. And I don't know if it's the scope of this project to be as exact as possible in detection.

At the very least I think that the checking code should be changed so that it FIRST tries to match the "webm" magic string, and if it fails to match that it should fallback to matroska (given that the first 4 bytes match of course.) The way it works now, it falls back to WebM, which is a very limited subset of matroska.

See attached mkv file:
[test.mkv.zip](https://github.com/sindresorhus/file-type/files/606313/test.mkv.zip)

**Comment by sindresorhus** [comment]
I want this module to be as exact as possible. I have no problem adding extra logic to achieve that. 

PR welcome :)

**Comment by mifi** [comment]
Cool! Are you also open for upping the required node version to, say 4? Because working with buffers in 0.10 is not very pleasant, I think

**Comment by mifi** [comment]
The holy grail would be to build JS a parser for the magic database and bundle it in the module, so we don't have to reimplement all the formats manually in code... But that's no trivial task unfortunately.

**Comment by sindresorhus** [comment]
> Are you also open for upping the required node version to, say 4? Because working with buffers in 0.10 is not very pleasant, I think

Done: https://github.com/sindresorhus/file-type/commit/2bea1a2b3e701c302fea92cf269b01ad0101b2ff

> The holy grail would be to build JS a parser for the magic database and bundle it in the module, so we don't have to reimplement all the formats manually in code...

Oh yeah. That would be so much better. Although this module already covers most of the common formats. Mind opening an issue about that? Maybe someone someday will see it and take the challenge.
