### ISSUE TITLE
Add support for universal modules

### ISSUE THREAD

**Issue by united-power-dev** [sindresorhus/file-type#674]
### Description

I tried for 2 hours and couldn't get this to work on my app, none of the solutions provided were either understandable or worked. I ended up just uninstalling it and looking for a different solution. It is not possible to set up in most cases unless it's a fresh repo that you start up as ESM yourself, thus making this un-accessible to many users.

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
