### ISSUE TITLE
no ai logo

### ISSUE THREAD

**Issue by easrng** [sindresorhus/file-type#676]
### Description

the ai logo in the readme feels very offputting, could you please remove it or replace it with a non-ai logo?

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by sindresorhus** [comment]
I don't see the problem with it. Happy to replace it if anyone comes up with something better, AI-generated or not.
