### ISSUE TITLE
Incorrect MIME type for Opus files.

### ISSUE THREAD

**Issue by scgehin** [sindresorhus/file-type#677]
### Description

Opus files are given the MIME type "audio/opus", which is not correct. The problem originates from #53, which incorrectly references the RFC for RTP payloads.
The correct MIME type for Opus files is "audio/ogg; codecs=opus", as seen in sections 9 and 10 of [this RFC](https://www.rfc-editor.org/rfc/rfc7845) defining the Opus file format.
This issue appears to be the root cause of thelounge/thelounge#4429.

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### ESM (ECMAScript Module) Requirement Acknowledgment

- [ ] My project is an [ESM project](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and my `package.json` contains the following entry: `"type": "module"`.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by Borewit** [comment]
I agree @scgehin, do you want to create a PR to improve the MIME type mapping?
