### ISSUE TITLE
Support for .xlsm, .ppsm, .ppsx, .vsdx, .docm file types

### ISSUE THREAD

**Issue by sunder-asuri** [sindresorhus/file-type#683]
### Description

I am trying to upload files in my project.
Is there a way to support .xlsm, .ppsm, .ppsx, .vsdx, .docm these file-types which are macro enabled using this package ?

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by sunder-asuri** [comment]
@sindresorhus Can i  please get any insights regarding whether this is possible or not? 
Any help would be greatly appreciated

**Comment by sindresorhus** [comment]
The supported file types are listed in the readme. We welcome contributions for additional file types.

**Comment by sunder-asuri** [comment]
@sindresorhus  I would like to have support for these 5 file types
1. XLSM, .ppsm, .ppsx, .vsdx, .docm

**Comment by Borewit** [comment]
If the are files, which are not recognized, please reopen this issue, and submit sampled. Preferably small samples.
