### ISSUE TITLE
Time Complexity of Detecting Image File Type

### ISSUE THREAD

**Issue by yanal97** [sindresorhus/file-type#685]
### Description

Any idea on the time complexity of detecting Images File Types from a Buffer? Can this be added in the logs of the package?

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by Borewit** [comment]
That functionality already exist, see example [ _determine file type from a Uint8Array/ArrayBuffer, which may be a portion of the beginning of a file_](https://github.com/sindresorhus/file-type?tab=readme-ov-file#nodejs).
