### ISSUE TITLE
Detect animated image

### ISSUE THREAD

**Issue by styfle** [sindresorhus/file-type#686]
### Description

I see that APNG support was added in PR https://github.com/sindresorhus/file-type/pull/215 which is great to detect the difference between a static PNG and animated PNG. This works great because they each have their own file extension and mime type.

However, I can't seem to find any way to differentiate static vs animated WebP images because the file extension and mime type are the same for both.

Is that possible using this package? If not, consider this a feature request 😃 

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by sindresorhus** [comment]
Maybe we could add a `isAnimatedImage` property in addition to `ext` and `mime`. That could be useful for GIF too.

**Comment by styfle** [comment]
Yeah that would be great! 

In particular, I'm looking to replace [`is-animated`](https://github.com/qzb/is-animated) which supports GIF, PNG, WebP, but it would also be great to support AVIF as well.

**Comment by Borewit** [comment]
Maybe handy for some users, but putting that in we move to an unclear scope.

What makes _isAnimatedImage_ a relevant file property in module which detects the file type? Why not add the _width_ and _height_, or the _bitrate_ for audio files.

**Comment by styfle** [comment]
I see what you mean.

Perhaps additional metadata would be opt-in onl. That way, existing use cases that only need the file type can early exit once that’s determined.
