### ISSUE TITLE
Arrow functions are not compatible with UglifyJS or IE11

### ISSUE THREAD

**Issue by cveilleux** [sindresorhus/file-type#70]
The latest 4.0.0 release uses arrow functions but that is not quite ready for prime time.

http://caniuse.com/#feat=arrow-functions

Also, UglifyJS does not support arrow functions.

We bundle our javascript with Webpack and use UglifyJS to minify our final bundle. The 4.0 release breaks because of the arrow functions.

Progress is good and tolling support for arrow function will get more and more widespread, but I suggest may be adding a warning on the 4.0 release / branch that some users might prefer to stay on the 3.x branch?

**Comment by sindresorhus** [comment]
Nah, the main target is Node.js. Up to you to transpile if you want it in the browser. Relevant discussion: https://github.com/facebookincubator/create-react-app/issues/1125#issuecomment-264217076
