### ISSUE TITLE
Cannot read properties of undefined (reading 'call') in react

### ISSUE THREAD

**Issue by Mrcxt** [sindresorhus/file-type#701]
### Description

<img width="557" alt="image" src="https://github.com/user-attachments/assets/a86f5e0b-a78c-4826-837b-abfaa647af68">

![image](https://github.com/user-attachments/assets/919a6077-6971-45e2-bdd5-ceab40b611e4)

![image](https://github.com/user-attachments/assets/e9c2fe06-1ad9-4705-9d34-fc3cb848448e)

![image](https://github.com/user-attachments/assets/f3721da8-a2f5-4c16-897c-c8a03284393a)

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### ESM (ECMAScript Module) Requirement Acknowledgment

- [X] My project is an [ESM project](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and my `package.json` contains the following entry: `"type": "module"`.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by Borewit** [comment]
Which version of **file-type** are you using @Mrcxt ?

I cannot correlate the stack-trace with the code of file-type. 
`new Readable` or `new ReadableWebToNodeStream2` does not seem to be part of the file-type code.
 
Can you create a repo, which can reproduce this issue?

**Comment by Borewit** [comment]
If you can provide additional information to reproduce the issue, you can re-open it.
