### ISSUE TITLE
Make it bundle-friendly/modular

### ISSUE THREAD

**Issue by laszbalo** [sindresorhus/file-type#74]
Factored out the tests for images, so I can include only the image modules into my bundle.
If you are interested, then I can do it for all file types and can submit a PR.
This is how it works at the moment: https://github.com/sindresorhus/file-type/compare/master...laszbalo:master

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/file-type/issues/70 and https://github.com/sindresorhus/file-type/pull/71.

**Comment by sindresorhus** [comment]
Nah. There's so little code in here. Makes no practical difference.
