### ISSUE TITLE
Blender file support

### ISSUE THREAD

**Issue by webbrandon** [sindresorhus/file-type#77]
I have a project that will now need to process `blend` files.  It would be wonderful to not have a customization that needs to figure this exception out.

Ref: http://www.atmind.nl/blender/mystery_ot_blend.html

**Comment by sindresorhus** [comment]
Sure. Seems like it's easy to add. Just need to detect `BLENDER` (in bytes) at the start of the file. Pull request welcome.

**Comment by webbrandon** [comment]
thank you!  I will try and get to add this when I have a moment.

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/file-type/commit/07571ddcf7d8c3bad4c5530af8c9d0451ae9e09d.
