### ISSUE TITLE
Compatibility with Create React App project

### ISSUE THREAD

**Issue by jimmoy** [sindresorhus/file-type#82]
I've created a ReactJS app:
```
$ create-react-app MyProject
```

Then added file-type:
```
$ yarn add file-type
```

Started using it in my app:
```
const fileType = require('file-type')
...
const image = Buffer.from(b64EncodedImage, 'base64') 
const meta = image && fileType(image)
const dataUri = meta && `data:${meta.mime};base64,${b64EncodedImage}`;
...
<img src={dataUri} ... />
```

Works fine, good MIME type, image is working, etc., but then I go to build and get errors:
```
$ npm run build
Creating an optimized production build...
Failed to compile.

static/js/main.52805dda.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/file-type/index.js:3,0]
```

Looks like in this context it doesn't like that arrow function at the beginning? I am a webpack and js/build newb so I'm not sure how to resolve this. Thoughts?

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446

In short, you have 2 options. The first one is use an older version, 3.9.0 should work. The second one is, use something like https://github.com/SamVerschueren/babel-engine-plugin

**Comment by mifi** [comment]
However using `babel-engine-plugin` is not possible in create-react-app without ejecting, as i understand it.

**Comment by SamVerschueren** [comment]
Yes you're probably right, same story with Angular CLI.

**Comment by sindresorhus** [comment]
It's still up to those tools to handle this, not every single module.

**Comment by mifi** [comment]
I absolutely agree. Just can't seem to find a good solution to this problem. And the discussion doesn't really belong here, because it's a CRA issue.

And @sindresorhus, you could probably put a banner on all your npm modules `README.md` saying you only support node >= 4 / ES6, and users need to transpile on their own. That way you don't have to waste time on all these issues being created. Or a `.github/ISSUE_TEMPLATE.md`

**Comment by SamVerschueren** [comment]
It's an auto reply, doesn't take too long...
