### ISSUE TITLE
MKA detected as MKV

### ISSUE THREAD

**Issue by cyorobert** [sindresorhus/file-type#83]
Hey,

This library is great, thanks for all of the hard work. I noticed that it's detecting mka (audio) files as mkv (video). Is this the expected behavior?

Thanks!

**Comment by mifi** [comment]
Is mka a separate format from mkv? or just different extension?

**Comment by thebravyone** [comment]
Seems like mkv, mka (audio only), mks (subtitles only), mk3d (stereoscopic video) and webm extensions share all the same container.

**Comment by mifi** [comment]
Why do you need to distinguish between these?

**Comment by Anaphase** [comment]
Yeah, I'm having the same issue -`video/webm` files are being detected as `video/x-matroska`. I need to distinguish between the two because my API allows `.webm` uploads but not `.mkv` uploads.

**Comment by cyorobert** [comment]
I need to distinguish between the 2 because I receive 2 separate posts from an API that will send an mka and an mkv, but does not send the extension information.

**Comment by siddo420** [comment]
I hit this bug today .. i'm displaying audio and video content differently so need to distinguish b/w th e2

**Comment by mifi** [comment]
Is unix "file" utility able to distinguish between the two?

**Comment by cyorobert** [comment]
@mifi running `file audio.mka --mime-type` outputs video/x-matroska. Based on that, I would say no, the unix utility cannot.

**Comment by mifi** [comment]
Then I don't really know how to distinguish between the two.

**Comment by cyorobert** [comment]
@mifi Definitely fair, I think you can close this. Thanks for the input!
