### ISSUE TITLE
Changelog please

### ISSUE THREAD

**Issue by dr-dimitru** [sindresorhus/file-type#93]
Hello there,

Great lib, but easy to get lost in releases, can't find why major version got bumped to 5.
It will be great to have Histroty.md or Chanhelog.md on the repository. Or at least describe commits, like [here](https://github.com/sindresorhus/file-type/commit/a5b4b21440e59225238b37deeac7cdae5698a0a3) I see it's `v5.0.0`, but why? What is changed?

Thank you.

**Comment by SamVerschueren** [comment]
We focus on a clean commit history which perfectly shows what changed between versions. https://github.com/sindresorhus/file-type/commits/master

**Comment by dr-dimitru** [comment]
@SamVerschueren what was the reason for major version update? What may break on my end? Or you simply not following semver?

**Comment by alrra** [comment]
> what was the reason for major version update?

@dr-dimitru See: https://github.com/sindresorhus/file-type/pull/85.

**Comment by SamVerschueren** [comment]
If you looked at the [commit](https://github.com/sindresorhus/file-type/commit/eabdf3d21448cc967f4d53410f3fee68574d6090), you would've seen it for yourself. Updating the font media types can easily break someone's application if they rely on the exact type.

**Comment by dr-dimitru** [comment]
@alrra thank you.
@SamVerschueren I see no trouble with having a file describing versions history. Or as I see you regularly update [releases](https://github.com/sindresorhus/file-type/releases) and each can have a brief changes description.

Consider as a suggestion. Thank you.
